### ISSUE TITLE
Address pending comments in the evidence parsers

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#1574]
From the new pipeline of the evidence parsers, I've collected these comments to be tackled in successive PRs. Feel free to add any features we may want to introduce.

- [x] Removal of the `setting.py` in favour of `configuration.yaml`
- [ ] Address the fact that we have to run the pipeline from the root directory
- [ ] Review the necessity of the `fetch` rules in a similar way as this Genetics Portal script: https://github.com/opentargets/genetics-v2d-data/blob/master/snakefiles/study_and_top_loci_tables.Snakefile
- [ ] Integrate all dependencies into one single file
- [ ] Maintain a consistent style of the code in line with the rest of our codebase
- [ ] Make it compatible with Python 3.9.
- [ ] Give a twist to storing all files in `tmp`, as Snakemake creates a temporary local directory following the structure of the remote directory. We could save the step of copying all the files to `tmp`.
- [x] Where do we want to store the log file?
- [x] Review the satellite files usefulness (`ontology_config.ini`, .`gitignore`,...).
- [ ] Update the README
- [ ] Dockerise the module
- [x] Orphanet: drop evidence where `targetFromSourceId` is null. 

Pending tickets:
- [x] PROGENy evidence parser issues: #713

Unify the handling of:
- [ ] Argument parsing
- [x] Ontology mapping
- [x] Spark configuration
- [x] Evidence string validation
- [x] Output of summary statistics (number of evidence, distinct targets and diseases)

When outputting final evidence, don't coalesce(0) — instead concatenate JSONs within the parser. This approach had been discussed & confirmed during the stand-up meetings.

**Comment by DSuveges** [comment]
There are a few new things, which don't have ticket at the moment, but should be scoped at some point in the future:
- [ ] The config yaml file has references to other repositories and it requires their release. It needs to be refactored so versions will only needs to be set once. Eg.
```yaml
used_versions:
  efo: "v.3.50.0"
  curation: "23.02"
  json_schema: "2.2.10"
```

- [ ] We need to re-write the environment again... we are getting deprecation warning:
```
  DEPRECATION: stopit is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for stopit ... done
  DEPRECATION: connection-pool is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for connection-pool ... done
  DEPRECATION: pyspark is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for pyspark ... done
  DEPRECATION: future is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for future ... done
  DEPRECATION: pandarallel is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for pandarallel ... done
  DEPRECATION: snakemake is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for snakemake ... done
```

**Comment by DSuveges** [comment]
We can consider dropping impc evidence that are not mapped to EFO. Currently there are ~50k of them.
