### ISSUE TITLE
Incorporate literature step to ETL

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#1793]
As a developer I want all the ETL steps to be in a single repository to improve code reuse and maintainability. 

## Background

The [ETL](https://github.com/opentargets/platform-etl-backend/) hosts all of the data processing steps except for [literature](https://github.com/opentargets/platform-etl-literature/).

Now that the circular dependencies have been resolved (see opentargets/platform#1919) there should be no further stoppers to integrating the two ETL repositories.

The Spark Sessions for Literature and the ETL were slightly different. We might need to use a different spark session for literature as for the rest of the ETL. Assume it works for now, and we'll address it when we start encountering errors. The most recent changes to the session configuration is in [this commit](https://github.com/opentargets/platform-etl-backend/commit/2dfe073)

## Tasks

- [x] Move the literature logic/readme to the ETL
- [x] Update the `Configuration.scala` and `reference.conf` files in the ETL to support the new step.
- [x] In the `reference.conf` update the DAG to include the new step
- [x] Update the `Main.scala` file to include the new step 
- [x] Archive the literature repository
- [x] Decouple the grounding dataset and the literature index (see Cinzia's comment below)

## Acceptance tests

How do we know the task is complete? 

1. When I consult `/documentation/current_etl_full.puml` I see a new step literature which has not introduced any circular dependencies
2. When I run the ETL step `literature` I get the same outputs as if I were to run the current `literature` pipeline.

**Comment by d0choa** [comment]
This task will definitely streamline our process. We might need to consider the challenges adding literature will introduce. 2 main things come to mind:
- computationally @mkarmona did a good job on performance. He reported 1.5h in the last run but I ignore how big the resources allocated were compare to a regular ETL run. Simply, something to think about.
- storage - some inputs and outputs are orders of magnitude bigger than the current ETL datasets. This might pose risks to POS handling of some of the datasets (e.g. FTP).

**Comment by cmalangone** [comment]
Be aware of the following fact:
*) Literature generates the **grounding for the EPMC evidence**. The Data team uses the grounding output and it generate the EPMC evidence. 
We need to **decouple the action of grounding and the generation of the literature index** (CH)
