### ISSUE TITLE
Analyse ChEMBL's Dailymed indications

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#1799]
Patricia from ChEMBL has provided the new indications dataset that they are expecting to use in ChEMBL30. Their pipelines have changed, so the data needs to be analysed.

## Background
Currently, ChEMBL's indications dataset is the result of manual curation. Tim has been working on a pipeline to systematise the extraction of drug/indication annotation by NLP means. 

As discussed on the previous meeting (23/09), they are expecting to use the results of this pipeline which contains an assessment of more than 27k Dailymed references. The data has not yet been QC'd and they are in the process now. 

## Files
`gs://ot-team/irene/chembl/DAILYMED_DISEASE_ChEMBL_ML.tsv`

## Tasks
I want to compare the results with their production indications dataset.

- [ ] Expand the ontology to account for the difference in granularity between datasets.
- [ ] Compare coverage against the manually curated indications set.
- [ ] Take a sample of the new indications and look for false positives.
- [ ] See if all the marketed drugs are covered.

**Comment by d0choa** [comment]
Happy to close this @ireneisdoomed if you think it's no longer relevant
