### ISSUE TITLE
Add drug mapping step to the ETL

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#1821]
As a **developer** I want **to build logic in the ETL to map drugs** because **I want to reference drugs annotated in some of the Platform datasets to the IDs in the drug index.**

## Background

The Cancer Biomarkers evidence generation has a step where the annotated drugs are mapped to a ChEMBL ID if possible. For this purpose, the drug index is used.
This is not limited to only evidence. A similar case happens with the chemical probes parsing, where the production drug index is also used to map probes to resolvable molecules.

Since the data generation is a step prior to the ETL, I would like the ETL to be able to map fields containing drugs to the respective molecule in the drug index so that everything is in sync and is done systematically.

## Tasks
Some items I can think of. We could convert them to independent issues.

- [ ] BE: Add logic to the ETL where `drugId` is the the result of successfully mapping a field with the fields: drug name (`name`) or drug inchikey (`inchiKey`).
- [ ] BE: Implement that logic in the cancer biomarkers evidence.
- [ ] BE: Implement that logic in the chemical probes target annotation.
- [ ] Data: Communicate new name to ChEMBL
- [ ] Data: Adapt schema
- [ ] Data: Remove code where the drug index is a dependency

## Acceptance tests

How do we know the task is complete? 

1. Evidence submitted by ChEMBL will have the drug annotation under `drugFromSource`.
2. The evidence set post ETL has the `drugId` field populated after mapping `drugFromSource`. 
3. Chemical probes in target has the `drugId` field populated after mapping `chemicalProbes.inchiKey`

I'm scoping this as room for improvement and to make it explicit. I am happy to know whatever input you might have. @opentargets/be-team @opentargets/data-team @d0choa
