### ISSUE TITLE
Biomarkers: Extract variant consequences from the variant description string

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#1860]
As a **developer** I want **to clean strings describing biomarkers** because **there is valuable data in the variant description that can be extracted** and because **it'll lead to an improvement of readability or post-processing of the reported string.**

## Background

Some biomarkers coming from the new `Cancer Biomarkers`data source may present lengthy variant names with useful information regarding their functional consequence that can be extracted and fed into the respective field.

There are 28 variants where `consequence` is mentioned in the string.

`NOTCH1` represents the dirtiest of them all. ([link](https://main--platform-app.netlify.app/evidence/ENSG00000148400/EFO_0000311)):
![image.png](https://images.zenhubusercontent.com/5f75e0f36450e0760fe97777/0a9fa73c-3d0e-4819-a303-51ca37ac9cd5)

## Tasks

- [ ] Study how feasible it is to extract a reliable set of consequences from these strings
- [ ] Map such consequences to an SO ID
- [ ] Improve the overall look of the string describing the variant

**Comment by d0choa** [comment]
This never happened isn't it?

**Comment by ireneisdoomed** [comment]
@d0choa No, I never prioritised it.
Taking the example above I am also not exactly sure how we would interpret it: I understand this is describing 5 different mutations happening at NOTCH1 with 5 different functional effects. However, the change in the aa composition is given for the same position so we don't have further info on which are the actual mutations.

We would gain annotation for 28 biomarkers.
