### ISSUE TITLE
Remove 'Connections' step from ETL

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#1895]
As a **developer** I do not want redundant steps cluttering the code base because it makes it harder to understand what the system is doing. 

When looking at `Main.scala` in the [ETL](https://github.com/opentargets/platform-etl-backend/) there is a step called `connections`. This was an experiment accidentally committed and the master branch and needs to be removed.

## Tasks

- [ ] Update `Main.scala` and any other files using the logic to remove all references to the functionality.
- [ ] Confirm the configuration file has no mention of this step
- [ ] Confirm the documentation has no mention of this step.
