### ISSUE TITLE
Create Validation Lab evidence page summary widget and detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/issues#1898]
To support the beta launch of the partner preview Platform, we have new data generated by the Validation Lab to integrate and score as evidence.

As the data is still a work-in-progress and not yet available from the API, I have created an example JSON file with fake data and the fields that will be exposed by the API.

```
{
  "data": [
    {
    "datasourceId": "ot_crispr_validation",
    "dataTypeId": "ot_validation_lab",
    "projectId": "OTAR015",
    "projectDescription": "CRISPR Cas9 Target ID",
    "targetFromSource": "BRAF",
    "targetId": "ENSG00000157764",
    "diseaseFromSourceMappedId": "EFO_0000365",
    "diseaseId": "EFO_0000365",
    "diseaseLabel": "colorectal adenocarcinoma",
    "resourceScore": 60.0,
    "confidence": "significant",
    "expectedConfidence": "significant",
    "diseaseCellLines": [
      {
        "name": "CL-1",
        "id": "SIDM00000"
      }
    ],
    "biomarkers": [
      {
        "name": "MSI",
        "description": "Microsatellite instability"
      },
      {
        "name": "B1-mut",
        "description": "Biomarker 1 mutation"
      },
      {
        "name": "B2-mut",
        "description": "Biomarker 2 mutation"
      },
      {
        "name": "B3-mut",
        "description": "Biomarker 3 mutation"
      },
      {
        "name": "B4-mut",
        "description": "Biomarker 4 mutation"
      },
      {
        "name": "CRIS-A",
        "description": "CRIS-A category"
      }
    ],
    "validationHypotheses": [
      {
        "hypothesis": "MSI",
        "description": "Microsatellite stability."
      }
    ],
    "statisticalTestTail": "upper tail",
    "contrast": "Loss of cell viability vs control",
    "studyOverview": "CellTitreGio measurement"
    }
  ]
}
```
[validation-lab-data-v1.json.zip](https://github.com/opentargets/platform/files/7925300/validation-lab-data-v1.json.zip)

Using the example JSON, can we please build a summary widget and detail view to display the Validation Lab data?

### Summary widget

- [x] Display "Open Targets Validation CRISPR" and the FontAwesome lock-icon and tooltip component used elsewhere (e.g. #1718)

- [x] Display the number of entries

![Partner Preview Platform - Validation Lab Data Integration - Draft - v2](https://user-images.githubusercontent.com/7490258/150778765-59c56243-d287-46d6-903d-9bf8116e7519.png)

### Detail view

![Partner Preview Platform - Validation Lab Data Integration - Draft - v2 (1)](https://user-images.githubusercontent.com/7490258/150787829-07ea44ba-784d-48c1-be33-b977b1795bd3.png)

- [x] Display the "OTAR Validation Lab" datatype chip

- [x] Display a placeholder section description and link the source "Open Targets" label to the Open Targets Intranet available at http://home.opentargets.org/:

> Data generated by select primary OTAR projects that have undergone orthogonal experimental validation, associating **TARGET-NAME** and **DISEASE-NAME**. Source: [Open Targets](http://home.opentargets.org/)

- [x] Create a data table based on the [design specification](https://docs.google.com/presentation/d/1I1bC79RThz8uiRSg0tWKiMhRY4WzaeHdlTHSz1jKmIU) 

| Reported disease | OTAR primary project | Contrast | Cell line | Cell line biomarkers | Effect size | Hit | Primary project hit | Validated observation | Validated hypothesis |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | 

- [x] Reported disease: show the `diseaseLabel` value and link to the disease profile page using the `diseaseId` field (note: in the final implementation, `diseaseId` will be resolvable object)

- [x] OTAR primary project: show the `projectDescription` field and the `projectId` field and hyperlink both strings to the Open Targets Intranet using the following link construct - `http://home.opentargets.org/` + `projectId`

- [x] Contrast: show the `contrast` field and add a tooltip at the end that shows the `studyOverview` field

- [x] Cell line: show the `diseaseCellLines.name` field and link to the Cell Models Passport website using the following link construct - `https://cellmodelpassports.sanger.ac.uk/passports/` + `diseaseCellLines.id` (note: `diseaseCellLines` is an array, but for now only has one object)

- [x] Cell line biomarkers: for each entry in the `biomarkers` array, display the `name` as a chip in green `#407253` and an on-hover tooltip that shows the `description` field

- [x] Effect size: show the `resourceScore` field

- [x] Hit: using the `confidence` field, if the value is `significant` display the [FontAwesome check-circle icon](https://fontawesome.com/v5.15/icons/check-circle?style=solid) in green `#407253`; otherwise, display the [FontAwesome times-circle](https://fontawesome.com/v5.15/icons/times-circle?style=regular) in grey `#e0e0e0`

- [x] Primary project hit: using the `expectedConfidence` field, if the value is `significant` display the [FontAwesome check-circle icon](https://fontawesome.com/v5.15/icons/check-circle?style=solid) in green `#407253`; otherwise, display the [FontAwesome times-circle](https://fontawesome.com/v5.15/icons/times-circle?style=regular) in grey `#e0e0e0`

- [x] Validated observation: if the value in the `confidence` field matches the value in the `expectedConfidence` field (both are either "significant" or both are "not significant"), display the [FontAwesome check-circle icon](https://fontawesome.com/v5.15/icons/check-circle?style=solid) in green `#407253`; otherwise, if the value in the `confidence` field does not match the value in the `expectedConfidence`, display the [FontAwesome times-circle](https://fontawesome.com/v5.15/icons/times-circle?style=regular) in grey `#e0e0e0`

- [x] Validated hypothesis:  for each entry in the `validationHypotheses` array, display the `name` as a chip in green `#407253` and an on-hover tooltip that shows the `description` field

**Comment by andrewhercules** [comment]
Based on conversation with the Validation Lab team, we have adjusted the design specification to improve readability and to highlight novel insights generated by the team.

![Partner Preview Platform - Validation Lab Data Integration - Draft - v2 (1)](https://user-images.githubusercontent.com/7490258/153611716-509c1d55-965f-495f-9766-8d62722a98c5.png)

Based on the implementation above, can we please make the following changes?

- [ ] Change the section description:

> Data generated for targets identified in selected OTAR primary projects and have undergone independent prioritisation and orthogonal experimental validation in the Open Targets Validation Lab (OTVL), associating **TARGET** and **DISEASE**. Source: [Open Targets Validation Lab](http://home.opentargets.org/OTAR2059)

- [ ] For the source link, please use `http://home.opentargets.org/OTAR2059`

- [ ] Remove the "Validated observation" and "Validated hypothesis" columns

- [ ] In the "Cell line biomarkers" column header, remove the "Available as seen in the cell lines" subtext

- [ ] Include the "API query" option in the table download options list

- [ ] Above the data table, include a new table/section with the title of "OTVL biomarker assessment for TARGET". In this section, display the list of biomarkers returned by the API (details TBC) and have a legend that shows the expected/observed status of the biomarkers (details TBC)

**Comment by DSuveges** [comment]
These issues are covered test here: [link](https://partner-platform.opentargets.org/evidence/ENSG00000181449/EFO_0005842)
