### ISSUE TITLE
Updating the logging design of the evidence generation pipeline

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#1914]
As a **[user]** of the [evidence data source parser](https://github.com/opentargets/evidence_datasource_parsers) pipeline I want to see parser specific logfiles for each run for quick troubleshooting.

## Background

Currently only one logfile is specified for all the rules. This is not good, given the rules running parallel might overwrite the same file. Also the logfile is always empty as the stderr is not directed into the logfile. 

## Tasks — original description
- Define a basic log file: `logFile = f"{config['global']['logDir']}/evidence_parser-{timeStamp}"`
- Define the parser specific logfile for each rule:

```Python
    log:
        GS.remote(logFile + f"-cancer_biomarkers.log")
```
- Properly direct logs into the files in the command section of each rules:
```Python
    shell:
        """
        python modules/EPMC.py \
          --cooccurrenceFile {input.inputCooccurences} \
          --output {output.evidenceFile} 2> {log}
        opentargets_validator --schema {params.schema} {output.evidenceFile} 2> {log}
        """
```

## Tasks — updated description
- [x] Investigate possible solutions to the problem
- [x] Make the logs for individual parsers local
- [x] Upload the logs to Cloud Storage within the 'all' rule
- [x] Gzip the logs before upload
- [x] Verify local run
- [x] Verify remote run

## Environment fixes
- [x] Update opentargets-validator to v0.8.0
- [x] Update Snakemake to v7.3.0
- [x] Pull opentargets-validator through PIP

## Datasource specific issues
- [x] Investigate EPMC validation errors
- [ ] Repeat full pipeline run
- [ ] Verify that the errors highlighted in the PR no longer apply

## Acceptance tests
1. Run complete snakemake pipeline - the pipeline should not fail
2. Check that the logfiles are properly generated
3. Check if the logfiles are not empty
