### ISSUE TITLE
Update Drug step in ETL to remove dependency on Chembl Evidence file.

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#1919]
As a developer I want to remove the dependency on the evidence file in the drug step to enable the integration of the literature pipeline into the ETL.

## Background

The Drug step in the ETL has as one of it's inputs the ChEMBL evidence file. This file is used to add two fields to the Molecule output: `linkedTargets` and `linkedDiseases`. 

This is unnecessary because that same information is already included elsewhere in the Drug index. `linkedDiseases` can be obtained using Indication, and `linkedTargets` can be obtained using Mechanisms of action. 

This will remove the dependency of drug on Evidence, freeing us to generate literature in the ETL. 

Blocking opentargets/platform#1793

## Tasks

- [ ] Update the Molecule output of the ETL (part of the Drug step) to generate the fields `linkedTargets` and `linkedDiseases` using the Indication and Mechanism of Action indexes. 
- [ ] Update the configuration to:
  - [ ] remove the evidence file input for Drug
  - [ ] update the DAG to reflect the changed dependency. 
- [ ] Update the documentation to show there is no longer a dependency on Evidence for the Drug step.

## Acceptance tests

1. When I resolve the DAG for the Drug step, the Evidence step is not included.

**Comment by JarrodBaker** [comment]
This issue was solved a bit different to the proposed solution in the ticket. I used the raw evidence file provided by the data-team. Since this has no dependencies anywhere else in the ETL it breaks the circular dependency we wanted to avoid and also avoided adding in any new untested logic.

**Comment by ireneisdoomed** [comment]
@JarrodBaker Please, can you clarify [this](https://github.com/opentargets/platform-etl-backend/pull/265#discussion_r973026290)?

**Comment by JarrodBaker** [comment]
This needs to be reworked due to a bug identfied by @Ireneisdoomed.

Linked targets seems relatively straight forward to solve using the mechanisms of action data. 
The following query (tested against several drugs) seem to show that we can generated the linked target data from the mechanism of action data without loss: a more systemic check will need to be made. 
```
query drugTargets {
  drug(chemblId: "CHEMBL79"){
    mechanismsOfAction {
      rows {
        targets {
          id
        }
      }
    }
    linkedTargets{
      count
      rows {
        id
      }
    }
  }
}
```
Linked diseases is more complicated because the evidence output file (used for linked diseases) and the indications seem to differ in their counts. 

```
query drugApprovedInds {
  drug(chemblId: "CHEMBL112"){
  	indications {
      rows{
        disease {
          id
        }
      }
      count
    }
    linkedDiseases {
      count
      rows {
        id
      }
    }
  }
}
```
This might not be an issue, as the field `linkedDiseases` is not used anywhere on the FE.
