### ISSUE TITLE
Integrate genetics pipeline into platform ETL

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#1924]
As a developer all ETL tasks to be in a single repository to make use of shared resources/logic.

## Background

The [genetics pipeline](https://github.com:opentargets/platform-genetics) provides ETL services for the Genetics platform. It is referred to as 'data joining' in the [documentation](https://genetics-docs.opentargets.org/technical-pipeline/pipeline-description).

There are 9 steps whose relationships are highlighted in this [schematic](https://github.com/opentargets/genetics-pipe/blob/master/documentation/step_dependencies.puml)

## Tasks

- [ ] Update ETL to include 9 new steps, each specifying a configurable input/output path as is done for existing ETL steps.
- [ ] Add genetics DAG to configuration specifying to include new steps
- [ ] Add field to configuration which can either be `genetics` or `platform` and specifies which DAG to use when running pipeline.
- [ ] Port steps from Genetics ETL to Platform ETL and update to use common helper functions and step structure. 
  - For instance, each step in the genetics pipeline currently hard-codes the write mode, whereas in the platform ETL we have this as a configurable field.
  - Platform steps generally have an `apply` and `compute` method, whereas there isn't much consistency in the genetics project.

## Acceptance tests

1. When I run the ETL with the configuration option `project=genetics`, the DAG resolves the correct order of execution so that each output is generated in the correct order.
2. Running the ETL genetics pipeline produces the same outputs as running the Genetics pipeline.

**Comment by mbdebian** [comment]
Genetics is taking a different direction with this
