### ISSUE TITLE
Automate generation of Genetics Platform images

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#1925]
As a developer I want a standardised way to create disk images for the Genetics Platform (GP) so I don't have to run lots of manual steps.

## Background

GP requires two disk images to be available to create the infrastructure: Elasticsearch and Clickhouse. These images are preloaded with the data necessary to serve the platform. 

Currently the process to generate these images is defined by the following sequence:

- [ ] Using the [genetics backend project](https://github.com/opentargets/genetics-backend.git) start two VMs: one each 
  for ES and Clickhouse using the helper scripts: `infrastructure/gcp/genetics/create-clickhouse-node.sh` and 
  `infrastructure/gcp/genetics/create-elasticsearch-node.sh`
- [ ] export variables for the two created VMs:(bind the internal GCP IP address, this assumes you're in a GCP VM yourself.)
  - `export ES_HOST=$(gcloud compute instances list | grep -i run | grep elasticsearch | awk '{ print $4 }' | tail -1)`
  - `export CLICKHOUSE_HOST=$(gcloud compute instances list | grep -i run | grep clickhouse | awk '{ print $4 }' | tail 
    -1)`
- [ ] run the script `loaders/clickhouse/create_and_load_everything_from_scratch.sh` in the `genetics-backend` 
  repository, providing a link to the input files. 
  - `./create_and_load_everything_from_scratch.sh gs://genetics-portal-dev-data/22.01.2/outputs`
- [ ] Once loading is complete, 'bake' the instances so that we can deploy the images using Terraform.
  - Find the latest running image: `gcloud compute instances list --project=open-targets-genetics-dev | grep -i run | 
    grep [elasticsearch|clickhouse] | awk '{ print $1 }' | tail -1`
  - Bake image using scripts in `genetics-backend/gcp/bake_[es|ch]_node.sh` with the image found above. These create 
    disk images which we can deploy using the Terraform defined in the [genetics terraform repo](https://github.com/opentargets/terraform-google-genetics-portal)
  
This process is quite slow (over 6 hours) and error prone since there are several steps which must be completed in the correct order. 

The POS uses similar [logic](https://github.com/opentargets/platform-output-support/tree/main/terraform_create_images), and can be used as 'inspiration' in GOS.

Note: we can speed this up by using separate scripts for loading ES and CH rather than the `create_and_load_everything_from_scratch` script which does one after the other. 

## Tasks

- [ ] Implement `images` task in GOS in a similar fashion as in the POS.

## Acceptance tests

1. When I run `make images` from the GOS repository two disk images are created which can be deployed using the Infrastructure project.
