### ISSUE TITLE
Port Genetics `Variant-Index` to ETL

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#1929]
As a developer I want all of the ETL steps in the same place where they can share common logic, configuration. 

## Background

The Genetics ETL is outdated and needs to be modernised. The `variant-index` step (step) is one of two which does not have any internal dependencies (the other being `variant-gene`) thus making it a good candidate for early extraction. 

The removal of this step will also mean we can deprecate [the script in the `genetics-backend`](https://github.com/opentargets/genetics-backend/blob/81d09bf5c70c534a59940eddfcd9c8566d2b2ec1/makeLUTs/create_genes_dictionary.py) repository which had to be manually run before the genetics pipeline. 

The step will have two inputs:
- `conf.variant-index.raw` in the genetics pipeline `application.conf`
- the Target index from the ETL. 

The step will have a single output:
- `variant-index.path` in the genetics-pipeline `application.conf`

### Internal dependences in the genetics pipe

Several steps in the genetics pipe use the output of the step as an input, albeit indirectly as they call an internal `load` method which retrieves the files stored in `variant-index.path`. Since we will still run this step first, no down-stream steps should break. 

### Intermediate `gene` index

The Genetics pipe currently creates a temporary data frame of genes based on Ensembl data. The only field which is not available on the `target` index is `tss`. 

This is created in the aforementioned script with: `df['tss'] = df.apply(lambda row: row['start'] if row['fwdstrand'] else row['end'], axis=1)` which is equivalent in Spark to `df.withColumn("tss", when(col("fwdstrand") === 1, col("start").otherwise(col("end"))`

## Tasks

- [x] Update configuration DAG to make explicit dependency on `target`.
- [x] Add configuration section
- [x] Port logic
  - [x] The `gene` index in the step should be created using the output of the ETL `target` step.
- [x] Update documentation (readme and step dependency graphs)
- [ ] Update deployment documentation in genetics pipe.
- [ ] Remove code from `genetics-pipe`

**Comment by d0choa** [comment]
I would like to use this opportunity to rescope the variant-index. There are different design principles that we might want to revisit to slim down the index and potentially including not only common but also rare variants. Also @DSuveges has some enhancements to use a newer GnomAD version that were never merged.

**Comment by JarrodBaker** [comment]
The gene input file used in the variant index step is generated by this python [script](https://github.com/opentargets/genetics-backend/tree/master/makeLUTs). The output has the following shape:

```
root
 |-- biotype: string (nullable = true)
 |-- chr: string (nullable = true)
 |-- description: string (nullable = true)
 |-- end: long (nullable = true)
 |-- exons: string (nullable = true)
 |-- fwdstrand: long (nullable = true)
 |-- gene_id: string (nullable = true)
 |-- gene_name: string (nullable = true)
 |-- start: long (nullable = true)
 |-- tss: long (nullable = true)
```
