### ISSUE TITLE
Harmonizing gene index generation between the Platform and Genetics Portal

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#1946]
As a **developer** I want **a unified process** to generate a **shared data model of genes** for the release of the Platform and the Genetics Portal.

## Background

The two product use different, but very similar gene model, that should be unified to slim down generation process to avoid code duplication, duplication of effort, and unnecessary discrepancies.

## Tasks

- [ ] Find out key differences between the two indices.
- [ ] Implement a shared pipeline that produces all required fields within the data model.
- [ ] Map new fields with old APIs to ensure the data picked up.

## Acceptance tests

1. The new pipeline generates gene index
2. The new gene index contains all the fields required by the Genetics Portal and the Platform.

**Comment by d0choa** [comment]
Duplicate of #1947
