### ISSUE TITLE
Designing a shared variant data model for the Platform and Genetics Portal

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#1948]
As a **developer** I want to get a **unified variant model** for the Genetics Portal and Platform.

## Background

On the Platform, a growing number of evidence sources have variant information, however at this point variant information is just an annotation. Having a variant entity would be highly advantageous as it would allow linking evidence from different sources. Also this would allow to share disease/target evidence (eg. from ClinVar) on the variant page on the Genetics Portal.

The review of the variant index's role in the Genetics Portal would also be advantageous as there's a good reason to assume the size of the variant index can be rationalized that would lead to a better coverage and a more manageable size.  

## Tasks

- [ ] Find out exactly where the variant index is used in the genetics Portal release process.
- [ ] Find out exactly where the variant index is used in the genetics Portal website.
- [ ] Came up with a workflow that generates a variant index that captures all variants on which we have association data on the Genetics Portal or evidence on Platform.
- [ ] Implement backend and frontend requirements for using a variant index on the Platform.

## Acceptance tests

1. The new pipeline generates variant index that captures all variants we have information for on GEnetics Portal and Platform.
2. The new index should be provide all necessary fields used by the Genetics Portal release or the frontend itself.

**Comment by d0choa** [comment]
Moving to a feature prioritisation document. Not immediate work is expected
