### ISSUE TITLE
Updating JSON evidence schema for the new datasources introduced for the partner preview

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#1966]
As a **developer** I want to **validate evidence sets for the partner preview**

## Background

For the partner preview, there are three new evidence sets: encore, ot_crispr, validation lab. The description of these datasets is required in the json schema to allow their validation. As of 2022.02.21 the data model is finalized, so there's a point to make these updates.

Also the PheWAS catalog is removed, which should be reflected by the json schema.

During the development of the parsers for the partner preview it has been identified that targets with lower cased characters cannot be resolved and all rendered as 

## Tasks

- [x] Adding schema for ot_crispr
- [x] Adding schema for the validation lab
- [x] Adding schema for encore
- [x] Removing schema for PheWAS Catalog (as this datasource is retracted)
- [x] Validation rule to enforce capitalized target labels.

## Acceptance tests

1. [x] Successfully validate crispr evidence
2. [x] Successfully validate validation lab evidence
3. [x] Successfully validate encore evidence
