### ISSUE TITLE
Standardise development infrastructure

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#1976]
As a developer I want a safe place to roll-out new infrastructure and releases in an automated way.

## Background

To support testing and development of the platform/portal, we need to have additional private infrastructure running so that we don't accidentally break anything in production. This development infrastructure is currently in two duplicated forms: 

1. App Engine (AE) running an API with VMs providing CH and ES instances
2. `xyz` which is a full copy of the production version using less powerful machines.

The front-end uses AE for testing because it provides a stable URL for netlify. 

We want to remove the AE instance and the associated VMs because they are all manually managed and are prone to falling out of sync with the `xyz` versions which are managed via Terraform.

## Tasks

- [x] Clean-up: remove AE from GCP and related files, notes in API repository
- [x] Provide FE with stable URL for developmental API: proposed is `https://platform.dev.opentargets.xyz/` and a similar one for genetics
- [ ] (Ambitious!) Update Travis so that when a new API is tagged it gets deployed to the development environment automatically.

**Comment by mbdebian** [comment]
We'll leave the automation from source code to deployment for its own issue and process, as it's not trivial.
