### ISSUE TITLE
Deprecate use of App Engine 

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#1978]
As a developer, I want an easy to use development environment to increase deployment speeds.

## Background

Currently there is duplicate infrastructure for the platform which increases the risk of versions being out of sync, increases running costs, and makes releases more complex than they need to be. The current infrastructure is represented below: 

![OT_deploy-Current_Platform_deployment.png](https://images.zenhubusercontent.com/5ec7caaa0e8174edc9bdf7a6/12a7c177-86ef-4ad8-b803-3159d911770d)

When deploying new versions of the platform it is necessary to update the infrastructure using Terraform and also manually make an App-Engine deployment. The infrastructure deployed by Terraform is a reflection of what would appear in production if we promoted the release, so should also be the infrastructure used for development and testing. We would like the infrastructure to look like:

![future-Future Platform deployment.png](https://images.zenhubusercontent.com/5ec7caaa0e8174edc9bdf7a6/c838a383-a2b2-4e6e-9d3d-94811ef2bb79)

The `xzy` infrastructure will no longer include metadata (release version) in the URL and instead will remain fixed. Netlify will be able to be used as before. There will be an exposed web application running on the development infrastructure and will reflect the UI as it would appear _should we agree that the development infrastructure can be released_. 

## Tasks

- [x] Update the development deployment to use a fixed URL: proposed are `https://api.platform.dev.opentargets.xyz` and `https://platform.dev.opentargets.xyz/` for the API and platform UI respectively.
- [x] Configure Netlify to use the correct endpoint.
- [x] Shut-down AppEngine and clean up old VMs
- [x] Clean up API repository of `yaml` files, README, etc. 

The same changes would be made to the Genetics set-up. 

How does that sound to you @carcruz , @LucaFumis , @mbdebian ?
