### ISSUE TITLE
UK Biobank Exome data from GSK collaboration

### ISSUE THREAD

**Issue by edm1** [opentargets/issues#2088]
GSK are finalising their analysis of rare variant tests for over 700 traits using the whole exome sequence data from 50K individuals from UK Biobank. They would like to share their data with us, to be made available through Open Targets immediately after accessibility restrictions are lifted (early March 2019).

This would be a great opportunity for Open Targets, as most people working in the field will be using this data in the coming months.

Steps:
- [ ]  Plan what the UKB GSK Exomes page will look like
- [ ] Plan table schema
- [ ] Plan GraphQL schema
- [ ] Map traits to EFO
- [ ] Write description of methods

**Comment by d0choa** [comment]
The 450k+ individuals are currently available through GWAS catalog. We will soon be scoping the required work. Particularly, to handle rare variants.
