### ISSUE TITLE
Mendelian randomisation (MR)

### ISSUE THREAD

**Issue by edm1** [opentargets/issues#2090]
We have not planned exactly how this will be done.

One option is to take results straight from the Bristol IEU's MR Everything-vs-Everything (MR-EvE). Their methods preprint is [here](https://www.biorxiv.org/content/early/2017/08/23/173682).

We can access the neo4j database from: http://eve-neo4j.mrbase.org/browser/ (Ed has username/password).

To think about:
- [ ] How do diseases/phenotypes map to EFO
- [ ] Can we map targets to genes (e.g. the metabolites)
- [ ] What parameters are available. How can these be used to assess (1) strength of evidence, (2) risk of bias
- [ ] What comparisons are available
- [ ] How would we represent these data in the portal?
- [ ] Taking into accounts the caveats, the main thing to ask is whether an association detected through this process could be used as 'evidence' in our system, bearing in mind that we can score lower to reflect caveats. What would this look like e.g. is the protein measurement a causal biomarker for the trait?
