### ISSUE TITLE
Filter biobliography results by publication date

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#2578]
As a platform user I want to be able to filter bibliography widget entries by date.

## Background

The bibliography widget is populated through the GraphQL API. A query fetching the bibliography data looks something like:

```
query target {
  target(ensemblId: "ENSG00000169083") {
    id
    approvedName
    approvedSymbol
      literatureOcurrences {
        count
        rows {
          pmid
          publicationDate
        }
      }
    }
  }
```
It would be necessary to extend the API to take a date parameter which filters these results. This would then need to be exposed in the FE. 

It was suggested on the [community forum](https://community.opentargets.org/t/on-the-platform-is-it-possible-to-sort-or-filter-bibliography-results-by-year-of-publication/551) to add this feature. 

## Tasks

- [x] Update API to accept date parameter on literature occurrences.
- [x] Update FE to expose the new API

## Acceptance tests

1. It is possible to return all publications before a specific date.
2. It is possible to return all publications after a specific date.
3. When no date is specified, all publications are returned.

**Comment by buniello** [comment]
Discussed with @remo87, there are a couple of issues with the functionality:
1) Number of entries reported by sliders never goes below the "pagination" number. e.g. I chose to display 5 entries per page and filter to the last 1 paper - slider is still reporting 5 papers. 
![Screenshot 2022-11-21 at 12.43.37 (2).png](https://images.zenhubusercontent.com/5ef1da283f096f8317c9ca44/9aade706-28c3-44e7-8da7-a4349d427eca)
2) Slider can change its status to the 'initial' status sometimes w/o human intervention
3) Dates overlap at the final point -- we discuss showing first date below the 'circle' and second date above the 'circle' so that they can never overlap.
![Screenshot 2022-11-21 at 12.47.38 (2).png](https://images.zenhubusercontent.com/5ef1da283f096f8317c9ca44/6669ef02-e1bc-4a7d-8236-4fa416d33e2b)

**Comment by buniello** [comment]
Tested the [latest version of the functionality](https://deploy-preview-90--ot-platform.netlify.app/disease/EFO_0000756) and I have a few comments for @remo87 :
1 - the `Tag category` filters situated on the left of the slider (Target, Disease, Drug) do not work (e.g. total counts never changes when unticking **one** or **all** the filters. This bug is also observed [in production](https://platform.opentargets.org/disease/EFO_0000565).  

2- There is a small typo in the loading message (occurrences)

3- The loading time when changing the date is quite slow, and I had the page stuck on loading a couple of times yesterday

4- When sliding all the way to 2023-1 (tested with several profile pages) , we still get a count despite return of zero entries. See screenshot.
![Screenshot 2023-02-08 at 17.33.18.png](https://images.zenhubusercontent.com/5ef1da283f096f8317c9ca44/50f14216-e7dc-4905-bba9-d3de473364fe)

**Comment by remo87** [comment]
Hi @buniello I just pushed changes that should solve the point 1 from the first comment and the points 2 and 4 from the second comment

**Comment by buniello** [comment]
Thank you @remo87! I have another point - how is the "starting date" for the slider being set? I would think it is the date of the first reported publication, but in the case of melanoma (for example) starting date is 1900-1, which is not date of first publication and it is too far back in time.

<img width="1332" alt="Screenshot 2023-02-10 at 12 06 08" src="https://user-images.githubusercontent.com/30833755/218088575-a3ddfa37-ada2-445a-aa42-1f3367b0d79c.png">

**Comment by prashantuniyal02** [comment]
Also the left sidebar of the filter goes back to the original date even after it is applied (the counts seem to change)
<img width="1323" alt="Screenshot 2023-02-10 at 12 09 20" src="https://user-images.githubusercontent.com/122870584/218089542-6f2b55e4-d6d6-49e9-be11-1d45da0d8c38.png">

**Comment by prashantuniyal02** [comment]
I think the logic should be: The left side filter date should be the date of the earliest publication (yyyy-mm) and the right side filter date should be the date of the latest publication (yyyy-mm). And when the filter is applied, it stays at the applied date along that length of the side bar.
It might affect the loading time of the table/filter & will be different for all tables

**Comment by buniello** [comment]
@remo87 -- it looks like points 1 and 2 from my comment on 21 Nov 2022 haven't been addressed yet. See Prashant's comment on slider going back to original date and also see schenshoot below: 
- when sliding all the way down to 2023-1, the slider count shows pagination number (5) instead of 3 -- which is the actual number of publications published in 2023:

<img width="1218" alt="Screenshot 2023-02-10 at 12 15 40" src="https://user-images.githubusercontent.com/30833755/218091732-7ad3c25b-f749-4b92-832b-e0a7085dd27a.png">

**Comment by prashantuniyal02** [comment]
Hi Ricardo, as discussed:

- [ ] Keeping both the year & month in the filter as the year & month of the first publication

**Comment by mbdebian** [comment]
@remo87 , can we flag this as completed or, does it make sense for this to be completed for the September release?
Thanks!

**Comment by remo87** [comment]
@mbdebian it would make sense to check again with the latest updates to the literature pipeline to see if it can be included. I'll take a look.

**Comment by mbdebian** [comment]
> @mbdebian it would make sense to check again with the latest updates to the literature pipeline to see if it can be included. I'll take a look.

Thanks!

**Comment by mbdebian** [comment]
@remo87 , would you mind checking whether this has been completed after your recent work on the literature pipeline?
Thanks!

**Comment by remo87** [comment]
Will do!

**Comment by remo87** [comment]
I've found 39770 Full text records with a pubDate earlier than 1900-01-01 are those valid publications?

these are some of them 

+--------+----------+----------+                                                
|    pmid|     pmcid|   pubDate|
+--------+----------+----------+
|30756561|PMC6103056|1878-09-01|
|30756601|PMC6103111|1878-08-01|
|30756600|PMC6103110|1878-08-01|
|30756603|PMC6103113|1878-08-01|
|30756635|PMC6103159|1879-02-01|
|33698456|PMC6919148|1865-05-01|
|33698436|PMC6919126|1865-05-01|
|30756596|PMC6103105|1878-11-01|
|30756606|PMC6103116|1878-08-01|
|30756675|PMC6106251|1874-02-01|
|30756633|PMC6103156|1879-02-01|
|30756667|PMC6106238|1873-09-01|
|30756643|PMC6103184|1879-04-01|
|30756649|PMC6106209|1873-08-01|
|33646652|PMC7852929|1856-01-01|
|33646693|PMC7853062|1858-04-01|
|33646708|PMC7853115|1859-02-01|
|30757286|PMC6114567|1894-03-01|
|30757727|PMC6118790|1896-01-01|
|30757846|PMC6119035|1885-01-01|
+--------+----------+----------+

the complete list is stored in `gs://open-targets-pre-data-releases/ricardo/lit/olderThan1900/` in parquet format

**Comment by remo87** [comment]
In the case of abstracts I found 2897 which pubDate was earlier than 1900-01-01. Here is a sample of the data

+--------+----------+----------+                                                
|    pmid|     pmcid|   pubDate|
+--------+----------+----------+
|    null|PMC2308718|1885-10-24|
|29418918|      null|1865-01-01|
|29257421|      null|1819-01-01|
|29257432|      null|1816-04-01|
|29257439|      null|1816-02-01|
|    null|PMC2508206|1895-08-10|
|    null|PMC2326196|1864-09-10|
|    null|PMC2408174|1897-12-04|
|    null|PMC2407876|1897-11-06|
|    null|PMC2412166|1899-09-02|
|    null|PMC2402404|1893-01-14|
|    null|PMC2422007|1893-07-29|
|    null|PMC2420993|1892-09-24|
|    null|PMC2419208|1853-10-07|
|    null|PMC2421028|1892-09-10|
|    null|PMC2407809|1897-10-09|
|    null|PMC2408523|1897-10-16|
|    null|PMC1288447|1884-01-01|
|    null|PMC1309879|1879-01-01|
|    null|PMC1288605|1886-04-01|
+--------+----------+----------+
only showing top 20 rows

the complete list is in `gs://open-targets-pre-data-releases/ricardo/lit/abstracts/olderThan1900`

**Comment by prashantuniyal02** [comment]
Hi @DSuveges and @tsantosh7 , are these publication date correct? Can you please look into this whenever you have some time?

**Comment by DSuveges** [comment]
By looking at a few examples, we are reproducing EuroPMC/Pubmed data:

- [PMC2422007](https://europepmc.org/search?query=PMC2422007): publication date:  29 Jul 1893
- [29418918](https://pubmed.ncbi.nlm.nih.gov/29418918/): publication date: 1865

I think the data is fine, there are old publications, but even if they are not that old, the data is coming from upstream and we don't have any means to fix them.

**Comment by remo87** [comment]
I found a data issue in the where some literature entries have year=0 month=0 and day=0. There's just a few of these I'm currently looking for the original record to try and find what's causing the issue. But given that there's just a few of them I think we could just ignore them in the query the gets the min date.

```

**Comment by remo87** [comment]
Indeed that seems to be issue. The pubDate is null for these records. 

```
+---------+----------+--------+-----+-------+--------------------+-------------------+
|organisms|     pmcid|    pmid|pprid|pubDate|           sentences|          timestamp|
+---------+----------+--------+-----+-------+--------------------+-------------------+
|     null|PMC5522542|29584195| null|   null|[{null, [{15, Cro...|2023-04-23 04:01:56|
|     null|PMC5522568|29584380| null|   null|[{null, [{50, Inf...|2023-04-23 00:02:58|
|     null|PMC5522571|29584219| null|   null|[{null, [{30, Sal...|2023-04-23 08:47:20|
|     null|PMC5540119|29419169| null|   null|[{null, [{82, Inf...|2023-04-23 11:39:59|
|     null|PMC5522558|29584209| null|   null|[{null, [{49, Dis...|2023-04-23 12:33:32|
|     null|PMC5269977|29838853| null|   null|[{null, [{57, Dis...|2023-04-23 02:50:47|
|     null|PMC5269851|29838746| null|   null|[{null, [{13, Can...|2023-04-23 05:55:40|
|     null|PMC5540115|29419167| null|   null|[{null, [{69, Inf...|2023-04-23 00:48:43|
|     null|PMC6067266|30750183| null|   null|[{null, [{19, Car...|2023-04-23 03:24:06|
|     null|PMC5269213|29838510| null|   null|[{null, [{29, App...|2023-04-23 06:54:17|
|     null|PMC5269850|29838745| null|   null|[{null, [{9, Infl...|2023-04-23 06:15:59|
|     null|PMC5269196|29838495| null|   null|[{null, [{52, Can...|2023-04-23 10:30:14|
+---------+----------+--------+-----+-------+--------------------+-------------------+

```

**Comment by remo87** [comment]
There's another option that @mbdebian proposed and I think it's a good one we are currently setting the date in the publication to the epoch (5th column) and we could use the same approach for the remaining columns year, month, day. @DSuveges @buniello @d0choa @prashantuniyal02 what do you think?

**Comment by DSuveges** [comment]
I don't know what does that mean exactly. Anyway the publication data for these publication exists at least on EuroPMC. For example [PMID: 29584219 PMCID: PMC5522571](https://europepmc.org/article/MED/29584219) -> 1900 Jan 1. 

I can take a look if that data was propagated from EuroPMC to us or not.

**Comment by remo87** [comment]
The epoch it's the 1970-01-01 it's the date where timestamps (in milliseconds) starts counting from. That date is being set to one of the columns in the literature index but not for the year, month, day. I checked the information from EPMC in the full text and that's where I found that for a few records with a null pubDate. And these records are the ones causing the odd behavior in the ui that we can see in pneumonia

**Comment by DSuveges** [comment]
Given these publication have pubdate at EuroPMC, however the raw json files we are getting do not, it would worth asking @tsantosh7 what options we might have here.

**Example:** pmid: 29838510, pmcid: PMC5269213. The [EuroPMC website](https://europepmc.org/search?query=PMC5269213) has publication date: 01 Jan 1900. However the json we are getting looks like this:

 - full text:
```
-RECORD 0---------------------------------------------------------------------------------------------
 organisms | null                                                                                     
 pmcid     | PMC5269213                                                                               
 pmid      | 29838510                                                                                 
 pprid     | null                                                                                     
 pubDate   | null                                                                                     
 sentences | [{null, [{29, Appendicitis, 17, DS}], title, null, null, The Treatment of Appendicitis}] 
 timestamp | 2023-04-23 06:54:17     
```

@tsantosh7 is there a way to add the publication date for these papers?

**Comment by tsantosh7** [comment]
@DSuveges please could you please let me know the source files where this is originating from? please

**Comment by prashantuniyal02** [comment]
Hey @remo87 ,

Some of the feedback points based on the current dev version:

- [ ] The total count is not updated after the filter is applied.
![image](https://github.com/opentargets/issues/assets/122870584/43003a8e-dd18-4b41-8019-d539cc0075ab)

- [ ] If the API sends a new request after you change past 25 entries, the filter shows as applied but there are results outside the filter being displayed. 
![image](https://github.com/opentargets/issues/assets/122870584/6583e258-a708-4dc4-bc55-8cd13743d044)

- [ ] Ideally we should display the results that match the filter and also the results that have date as null. However these should have a small tag indicating a missing date.

**Comment by prashantuniyal02** [comment]
Hi Ricardo,

Here are the feedback points:

- [ ] The Bibliography widget in the profile page is disabled even when there is [data](https://deploy-preview-327--ot-platform.netlify.app/disease/EFO_0000756).
<img width="1380" alt="image" src="https://github.com/opentargets/issues/assets/122870584/c96a1a7c-8ffb-4485-84fa-b47a59519365">

- [ ] Once you filter the list and select the chips, and keep moving to next pages (say page 6) and then change the rows per page, the page does not work as expected.

**Comment by remo87** [comment]
For the no data this seems to be caused by the page size change because if we are at 5 records per page and we are at page 9 if we change to 25 records per page and we're still at page 9 we would need to have more than 275 records to be able to show something. One way to fix this would be any time change page size we go back to page 1. Would that be ok?

**Comment by buniello** [comment]
I have tested the latest implementation in dev and observed a similar behaviour to the one displayed in Prashant's videos above: 1) number of records does not change when filtering out (stays on total number -unfiltered) 2) observed an inconsistent FE behaviour when filtering (e.g. slider suddenly goes back to initial state) @prashantuniyal02 could you please follow up with @remo87

**Comment by remo87** [comment]
> I have tested the latest implementation in dev and observed a similar behaviour to the one displayed in Prashant's videos above: 1) number of records does not change when filtering out (stays on total number -unfiltered) 2) observed an inconsistent FE behaviour when filtering (e.g. slider suddenly goes back to initial state) @prashantuniyal02 could you please follow up with @remo87

I just talked to @prashantuniyal02 and it seems that was related to another PR. Dev should be fixed with the next release.

**Comment by buniello** [comment]
sorry @remo87 , i was testing an old link!
