### ISSUE TITLE
Review parameter handling for PPP evidence generation

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2582]
Currently configuration files are used to store study level metadata for generating evidence for the partner preview. The current arrangement needs to be changed and should be made consistent across data sources. The config files should not be publicly available, so storing them in github is not an option. Files should live in a google bucket not accessible by public.

**Tasks for `ot_crispr`**:

- [x] Remove study spreadsheet: convert to json, copy to a Google bucket.
- [x] Add `version` and `releaseDate` fields for all the studies (infer data and version).
- [ ] Update code to read and process config.

**Tasks for `ot_validation_crispr`**:

- [x] Remove config file from google bucket: convert to json, copy to a Google bucket.
- [ ] Add `version` and `releaseDate` fields for all the studies (infer data and version).
- [ ] Add flag to indicate studies to be skipped.
- [ ] Add disclaimer message

**Tasks for `encore`**:

- [x] Remove config file from google bucket: convert to json, copy to a Google bucket.
- [ ] Add `version` and `releaseDate` fields for all the studies (infer data and version).
- [ ] Add flag to indicate studies to be skipped.
- [ ] Add disclaimer message

**Comment by DSuveges** [comment]
To establish full tracking of the changes of these files, I decided to open a private repository to hosting the configurations: https://github.com/opentargets/PPP-evidencie-configuration
