### ISSUE TITLE
Rewrite V2G interval data generation process

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2584]
As a **developer** of the genetics portal pipelines I want **a reasonable v2g interval data**, the structure of the current implementation is quite inefficient as @JarrodBaker  has pointed out.

## Tasks

- [ ] Review the existing codebase ([genetics-v2g-data](https://github.com/opentargets/genetics-v2g-data))
- [ ] Test run existing implementation
- [ ] Change output so the output files won't contain study level metadata required downstream.

**Comment by DSuveges** [comment]
**TODOS:**
1. Review The list of comments under the PR -> Apply modification on the etl repo if necessary.
2. Close PR on V2G. 
3. Adding documentation to etl repo for the interval parser.
