### ISSUE TITLE
Add canonical transcript to Target object in ETL

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#2591]
As a developer I want the canonical transcript on a target to be identified because this is required to integrate the genetics portal and platform ETLs.

## Background

The genetics portal creates a mini target index using a select statement against database. This is a manual script which must be run before the genetics pipeline. We want to integrate the genetics pipeline into the platform, and reuse the target index to ensure that the two align. All fields required are already on the target index, _except for an annotation for the canonical transcript_. 

Daniel has identified how the ETL can be updated in a comment from 16 May on [ticket](https://app.zenhub.com/workspaces/open-targets-issue-tracker-58a421fd8c85e652659a1486/issues/opentargets/issues/1947)

## Tasks

- [ ] Update PIS to get the required input file from `gencode`
- [x] Update the ETL to annotate the target index with the canonical transcript ID. 
- [x] Update the target documentation in the ETL readme with notes on the source of the file. 

## Acceptance tests

1. When I view the target object, I see a field `canonical_transcript_id` which lists a canonical transcript where one exists in the gencode annotation file
2. Where a target has a `canonicalTranscriptId`, that same value is present in the array `transcriptIds`

**Comment by DSuveges** [comment]
At least the interval data generation of the Genetics Portal release pipelines uses canonical transcripts to calculate distance between the interval midpoint and the transcription start site of the transcript. We can store the sufficient information in the target index like this:

```
 |-- canonicalTranscript: struct (nullable = false)
 |    |-- id: string (nullable = true)
 |    |-- chromosome: string (nullable = true)
 |    |-- start: long (nullable = true)
 |    |-- end: long (nullable = true)
 |    |-- strand: string (nullable = true)
``` 
Content:
```json
  "canonicalTranscript": {
    "id": "ENST000000000",
    "chromosome": "1",
    "start": 8127634,
    "end": 8129745,
    "strand": "+"
  }
```
This proposal would cut dependencies of the Genetics Portal release process from Ensembl by directly sourcing gene data from OT Platform.

**Comment by JarrodBaker** [comment]
@d0choa, @buniello : This new field will be available on Target in the Platform data from the upcoming release onwards. The field was added to aid in integrating the genetics and platform datasets. If you want to display this information in the front-end let me know and I'll have the API updated accordingly.

**Comment by d0choa** [comment]
Thanks @JarrodBaker. I can't think of any clear use case to expose it in the Platform or Genetics
