### ISSUE TITLE
Plug EPMC evidence generation to the ETL.

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2629]
## Aim

The EPMC evidence needs to be moved to the ETL from the [evidence datasoruce parsers](https://github.com/opentargets/evidence_datasource_parsers/blob/master/modules/EPMC.py).

## Background

The EPMC evidence generation relies on the grounded cooccurrences, which means the completed ETL run is expected for generating the evidence. Then the generated evidence is picked up by the ETL. This is a circular dependence and needs to be resolved.

## Tasks

- [ ] Change the parser EPMC parser in a way to make sure it can be run as a dataproc job.
- [ ] Create an ETL step for this task.
- [ ] The validation should also be somehow be integrated.
 
## Acceptance tests

1. The literature pipeline is expected to generate the epmc evidence.

**Comment by ireneisdoomed** [comment]
Regarding the validation process, Great Expectations is a relevant Python library to run data quality checks. I've been thinking of testing this validation suite as an alternative to our current approach, and this could be a nice usecase since it integrates nicely with Pyspark.

Here's some sample code on how it could be integrated: https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/968100988546031/3944681434720936/8836542754149149/latest.html

However, I've never tried it on big datasets so I am not aware of its limitations.
