### ISSUE TITLE
Capturing primary vs. conditional signals in reported results (OTG)

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2631]
Following up from the feedback on OTG functionalities provided by BMS on 8-6-22.

As a user, I need to be able to gather info on whether a reported SNP/trait association is coming from a primary or conditional analysis - these tags are important for downstream analyses/customised pipelines.

This info should be visualised on the study and gene prioritisation pages.

## Tasks
**STUDY PAGE**

- [ ] Adding a new column in the associations' table, populated with different shapes to report primary and secondary signals (see one option below). In the example below, two lead variants mapping very close to each other are shown in curly bracket - which one is the primary? Which one is the secondary signal? 

Screenshot from [GCST002221](https://genetics.opentargets.org/study/GCST002221)

![Screenshot 2022-07-06 at 12.41.18.png]
(https://images.zenhubusercontent.com/5ef1da283f096f8317c9ca44/71a98f0d-0099-4464-b106-94c25944c6f7

**GENE PRIORITISATION PAGE**:

- [ ] Adding variant signal info to the Association Summary (at a variant level) see option below:

![Screenshot 2022-07-06 at 12.41.18.png](https://images.zenhubusercontent.com/5ef1da283f096f8317c9ca44/0e691381-0f26-4857-b829-cc56d0b656cb)

- [ ] Additional Action Item for @bruno-ariano: to investigate where to extract this info in investigate where to extract this info  in GCTA-cojo and to look at the locus-zoom like regional plot / FinnGen regional plot for benchmarking.

![Screenshot 2022-06-13 at 14 15 50](https://user-images.githubusercontent.com/30833755/173363375-01b440f0-dbe5-4e5d-b4b7-9719ac44acc1.png)

## Acceptance tests

How do we know the task is complete? 

1. When data and visualisations are successfully deployed for the users.

**Comment by bruno-ariano** [comment]
Hi I have found a nice example describing a secondary signal:

This involve the study GCST002221.  In this study there is a leading variant 19_44919689_A_G which is close to another leading variant named 19_44912678_G_T. 

If we click on the variant summary page of the first variant (https://genetics.opentargets.org/variant/19_44919689_A_G) we see the second one(19_44912678_G_T) is tagging the primary one for the GCST002221 study. This is an example of secondary signal

Given that we must have the credible set information stored of the leading and tagging variants (respectively 19_44919689_A_G and 19_44912678_G_T ) for the study GCST002221. 

The credible set file store also the conditional p-value information for 19_44912678_G_T given the leading variant (19_44919689_A_G) which we should add to the page

**Comment by buniello** [comment]
@JarrodBaker could you please take a look at Bruno's example and let us know if it is indeed a good use-case to progress with this task?

**Comment by JarrodBaker** [comment]
I'll get to it as soon as I can.

**Comment by d0choa** [comment]
To add to the feature request document

**Comment by buniello** [comment]
feature added to partners feedback doc

**Comment by buniello** [comment]
feature added to partners feedback doc
