### ISSUE TITLE
The PheWAS table contains redundant data

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2683]
**Bug description**

The PheWAS table contains redundant data. Seemingly one association is repeated multiple times.

**Expected behaviour**

The table should be unique: from one study, there should be only one association in the table.

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to the variant page of [rs3124797](https://genetics.opentargets.org/variant/1_7689747_A_G)
2. Find the PheWAS table. 
3. Filter table for the trait: `Amyotrophic lateral sclerosis`
4. The table return 5 rows, 4 of which seems identical.

The duplication can be also found in the downloadable GWAS parquet file.

**Additional context**

The issue was reported as a community post [here](https://community.opentargets.org/t/repeated-records-in-opentargets-genetics-phewas-table-report/717).

**Comment by DSuveges** [comment]
The parquet file of the summary stats of the implicated study ([GCST005647](https://genetics.opentargets.org/study/GCST005647)) seems to be quadrupled: the size of the dataset is 39_630_630, while the number of unique association is just 9_465_602. (based on: `gs://genetics-portal-dev-sumstats/unfiltered/gwas/GCST005647.parquet`)

**Comment by DSuveges** [comment]
When re-running the sumstat ingestion[1] for the dataset, the resulting dataset contained 9_465_602 entries, which was consistent with the expected number of unique entires. The log of the run showed no unexpected event[2]. The run was OK, and the generated data looks OK.

This leaves us with two reasonable possibilities:
1. The bug, that caused the duplication was in the code, but now it is fixed. 
2. The bug was introduced with the wrong data, but the source got updated on the GWAS Catalog.

- The data was generated on 2021-10-04 [3]
- Logs shows no significant changes in the code of the master branch since this timepoint [4].
- The harmonized summary stats on the GWAS Catalog FTP was generated on `2021-06-16` [5].

**Conclusion:** Based on the above tests, I couldn't locate the source of the issue.

[1] Command:
```bash
python process.py \
    --in_sumstats gs://genetics-portal-raw/gwas_catalog/harmonised_test/29566793-GCST005647-EFO_0000253.h.tsv.gz \
    --in_af gs://genetics-portal-data/variant-annotation/190129/variant-annotation.parquet \
    --out_parquet gs://genetics-portal-dev-analysis/dsuveges/GCST005647.sumstats.parquet \
    --study_id GCST005647 \
    --n_total  80610 \
    --log log.test
```
[2] Log:
```
Namespace(in_af='gs://genetics-portal-data/variant-annotation/190129/variant-annotation.parquet', in_sumstats='gs://genetics-portal-raw/gwas_catalog/harmonised_test/29566793-GCST005647-EFO_0000253.h.tsv.gz', log='log.test', min_mac=10, min_rows=10000, n_cases=None, n_total=80610, out_parquet='gs://genetics-portal-dev-analysis/dsuveges/GCST005647.sumstats.parquet', study_id='GCST005647')
Warning: Ignoring non-Spark config property: parquet.summary.metadata.level
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
22/08/01 21:30:04 INFO org.apache.spark.SparkEnv: Registering MapOutputTracker
22/08/01 21:30:04 INFO org.apache.spark.SparkEnv: Registering BlockManagerMaster
22/08/01 21:30:04 INFO org.apache.spark.SparkEnv: Registering BlockManagerMasterHeartbeat
22/08/01 21:30:04 INFO org.apache.spark.SparkEnv: Registering OutputCommitCoordinator
Spark version:  3.1.3
2022-08-01 21:30:14,018 __main__     INFO     Started ingest pipeline for gs://genetics-portal-raw/gwas_catalog/harmonised_test/29566793-GCST005647-EFO_0000253.h.tsv.gz
2022-08-01 21:33:36,380 __main__     INFO     9481886 rows in dataset, 9 partitions
2022-08-01 21:38:21,133 __main__     INFO     Removed NAs (16284 removed)
2022-08-01 21:38:25,364 __main__     INFO     9465602 rows with allele frequency info (0 removed)
2022-08-01 21:38:29,561 __main__     INFO     9465602 rows after filtering on MAC (0 removed)
2022-08-01 21:38:51,603 __main__     INFO     9465602 rows after processing (16284 removed, 0.17%)
2022-08-01 21:38:51,603 __main__     INFO     Time taken: 0:08:37.585180
```
[3] `gsutil ls -lah gs://genetics-portal-dev-sumstats/unfiltered/gwas/GCST005647.parquet | head`
[4] `git log -p -- scripts/process.py`
[5] ftp://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST005001-GCST006000/GCST005647/harmonised/29566793-GCST005647-EFO_0000253.h.tsv.gz

**Comment by DSuveges** [comment]
Further exploring the issue revealed two separate issues:
1. Complete duplication of rows
2. Seemingly duplicated entries, however having different allele frequencies

### Complete duplication of rows

This problem was reported in reported for GCST005647 [1]:
```
+----+----------+------------+-----------+-------+-----+-------+---+---+------+------+--------+-------+-------+-------------------+-----------------+---------+----+-----+
|type|study_id  |phenotype_id|bio_feature|gene_id|chrom|pos    |ref|alt|beta  |se    |pval    |n_total|n_cases|eaf                |mac              |mac_cases|info|is_cc|
+----+----------+------------+-----------+-------+-----+-------+---+---+------+------+--------+-------+-------+-------------------+-----------------+---------+----+-----+
|gwas|GCST005647|null        |null       |null   |1    |7689747|A  |G  |0.0435|0.0137|0.001565|80610  |20806  |0.48650000000000004|78433.53000000001|20244.238|null|true |
|gwas|GCST005647|null        |null       |null   |1    |7689747|A  |G  |0.0435|0.0137|0.001565|80610  |20806  |0.48650000000000004|78433.53000000001|20244.238|null|true |
|gwas|GCST005647|null        |null       |null   |1    |7689747|A  |G  |0.0435|0.0137|0.001565|80610  |20806  |0.48650000000000004|78433.53000000001|20244.238|null|true |
|gwas|GCST005647|null        |null       |null   |1    |7689747|A  |G  |0.0435|0.0137|0.001565|80610  |20806  |0.48650000000000004|78433.53000000001|20244.238|null|true |
|gwas|GCST005647|null        |null       |null   |1    |7689747|A  |G  |0.0435|0.0137|0.001565|80610  |20806  |0.48650000000000004|78433.53000000001|20244.238|null|true |
+----+----------+------------+-----------+-------+-----+-------+---+---+------+------+--------+-------+-------+-------------------+-----------------+---------+----+-----+
```
This issue is quite enigmatic. As saying above, when re-run on a given study we see no remaining duplications.

### Seemingly duplicated entries, however having different allele frequencies:

```
+----+------------+------------+-----------+-------+-----+--------+---+---+------+-----+------+-------+-------+-------------------+------------------+---------+----+-----+
|type|study_id    |phenotype_id|bio_feature|gene_id|chrom|pos     |ref|alt|beta  |se   |pval  |n_total|n_cases|eaf                |mac               |mac_cases|info|is_cc|
+----+------------+------------+-----------+-------+-----+--------+---+---+------+-----+------+-------+-------+-------------------+------------------+---------+----+-----+
|gwas|GCST90002227|null        |null       |null   |10   |50134652|A  |G  |0.0403|0.348|0.7642|63396  |null   |0.0754836663495084 |9570.725023786868 |null     |null|false|
|gwas|GCST90002227|null        |null       |null   |10   |50134652|A  |G  |0.0403|0.348|0.7642|63396  |null   |0.09613615455381785|12189.295308187673|null     |null|false|
|gwas|GCST90002227|null        |null       |null   |10   |50134652|A  |G  |0.0403|0.348|0.7642|63396  |null   |0.24146683003675828|30616.062314020655|null     |null|false|
+----+------------+------------+-----------+-------+-----+--------+---+---+------+-----+------+-------+-------+-------------------+------------------+---------+----+-----+
```
This example is explainable by a very strange problem with the variant index: there are seeming duplications in the variant index with identical genomic locations and alleles but with different allele frequencies [3]:

```
+-----+--------+---+---+-------------------+
|chrom|pos     |ref|alt|gnomad_nfe         |
+-----+--------+---+---+-------------------+
|10   |50134652|A  |G  |0.09613615455381785|
|10   |50134652|A  |G  |0.24146683003675828|
|10   |50134652|A  |G  |0.0754836663495084 |
+-----+--------+---+---+-------------------+
```
This duplications explodes all the the rows in the summary stats when joined with the variant index. This problem most likely will go away once we are moving from GnomAD 3.


[1] Get complete duplicates of rows:
```Python
(
    spark.read.parquet('gs://genetics-portal-dev-sumstats/unfiltered/gwas/GCST005647.parquet')
    .filter((F.col('chrom') == '1') & (F.col('pos') == 7689747) & (F.col('alt') == 'G'))
    .show(10, truncate=False)
)
```

[2] Get same variants with different AFs:
```Python
(
    spark.read.parquet('gs://genetics-portal-dev-sumstats/unfiltered/gwas/GCST90002227.parquet')
    .filter(( F.col('chrom') ==  '10') & (F.col('pos') == 50134652))
    .show(truncate=False)
)
```
[3] Retrieve problematic variant from variant index:
```Python
(
    spark.read.parquet('gs://genetics-portal-data/variant-annotation/190129/variant-annotation.parquet')
    .select(
        F.col('chrom_b38').alias('chrom'), F.col('pos_b38').alias('pos'), 'ref', 'alt', 'af.gnomad_nfe'
    )
    .filter(
       ( F.col('chrom') ==  '10') & (F.col('pos') == 50134652)
    )
    .show(10, truncate=False)
)
```

**Comment by DSuveges** [comment]
The second case can be explained by liftover artefacts: we are using GnomAD2.1, so we have to lift over the variant coordinates to the new build. The problem is that multiple GRCh37 coordinates can point to the same location in the new build:

```
+---------+---------+---------+---------+---+---+--------------------+
|chrom_b37|chrom_b38|  pos_b37|  pos_b38|ref|alt|          gnomad_nfe|
+---------+---------+---------+---------+---+---+--------------------+
|        1|        1|144465704|120968509|  G|  T|1.271294177472667E-4|
|        1|        1|144285466|120968509|  G|  T| 0.07902511078286559|
+---------+---------+---------+---------+---+---+--------------------+
```

**Comment by DSuveges** [comment]
Investigating the issue systematically revealed that the duplication affects ~50 million associations from 510 studies, however the wast majority of the duplication affects only 4 studies:

```
+------------+--------+------------+--------+------------------+
|study_id    |count   |unique_count|diff    |proportion        |
+------------+--------+------------+--------+------------------+
|GCST005647  |39630630|9465602     |30165028|4.186805023071961 |
|GCST004421  |18173964|9085622     |9088342 |2.000299374109995 |
|GCST90000513|16535161|8381764     |8153397 |1.9727543032707673|
|GCST003368  |4880078 |2440039     |2440039 |2.0               |
|GCST004770  |2272477 |2154596     |117881  |1.0547114168967175|
|GCST004772  |2272477 |2154596     |117881  |1.0547114168967175|
|GCST90013658|7237327 |7220574     |16753   |1.0023201756536253|
|GCST003395  |9481847 |9469100     |12747   |1.0013461680624347|
|GCST007557  |14039324|14028871    |10453   |1.0007451062883108|
|GCST003394  |9481847 |9471718     |10129   |1.001069394169041 |
|GCST003392  |9481847 |9471739     |10108   |1.0010671746761604|
|GCST006679  |6916644 |6908100     |8544    |1.0012368089633907|
|GCST004488  |6916672 |6908130     |8542    |1.0012365140783397|
|GCST90026610|815751  |811230      |4521    |1.0055730187493066|
|GCST90026611|815701  |811198      |4503    |1.0055510491889772|
|GCST90026609|821049  |817975      |3074    |1.003758061065436 |
|GCST004422  |9388671 |9387300     |1371    |1.0001460483845195|
|GCST004439  |9411761 |9410390     |1371    |1.00014569002985  |
|GCST004432  |9411796 |9410426     |1370    |1.0001455832073916|
|GCST004433  |9414459 |9413090     |1369    |1.0001454357708255|
+------------+--------+------------+--------+------------------+
```

## Todos:

To resolve all this issue listed above, the following actions needs to be taken:
- [ ] Rewrite the the data ingestion [script](https://github.com/opentargets/genetics-sumstat-data/blob/master/ingest/gwas_catalog/scripts/process.py)
- [ ] Use variant annotation based on GnomAD3 (This dataset is already prepared)
- [ ] Re-run the data ingestion pipeline

**Comment by DSuveges** [comment]
Some of the duplications can be explained by issues in the GWAS Catalog, about which I have reported the team:

```
Hi Guys,
 
 
I have been investigating a user report about duplication in our datasets. When digging into the data, I have identified a range of issues in our pipelines, however I also noticed that some of the duplications are coming from the GWAS Catalog (potentially hundreds of summary stats are affected, on our side its number is more than 500). Please let me provide some details in the example of study GCST003395 [1].
 
The raw data: contains 9_583_642 rows, but only 9_558_711 unique, meaning there are 24_931 rows with identical values in all fields [2]. When calculating the number of unique variants (CHR, POS_b37, A1, A2) I got 9_558_444, meaning there are 267 duplicated variants with different statistical parameters [3]. Based on the study page on the GWAS Catalog website, I think this level of duplication cannot be explained by potential conditional analysis (also, the p-values aren’t justify a conditional test). Based on my experience such events can happen when coordinates from an older build is mapped to a newer one. Eg. Multiple coordinates on b36 could be mapped to a single b37 coordinate (but this is just an assumption).
In the harmonized dataset these duplications propagated: 9_536_338 total, 9_523_572 unique and 9_468_100 unique variants.
 
I’m wondering if you are already aware of such duplications? As I mentioned earlier this might be quite prevalent issue. Tacking the pure duplications is trivial: just select distinct rows before saving the data, however not sure what the best way of handling the second group, when seemingly the same variant has two or more association statistics. Any insight would be highly welcomed.
 
Best,
Daniel
```

**Comment by d0choa** [comment]
@DSuveges do you want to close this?

**Comment by DSuveges** [comment]
I would say so. We explored the issue, it seems the duplication is coming from the source (GWAS Catalog Summary Statistics), we will have to remember when we are touching the PheWAS table to make sure we are applying at least a `.distinct()` on the each summary statistics. That would solve most of the problem.
