### ISSUE TITLE
Standardise column names in genetics backend

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#2684]
As a developer I want a data model with clear and easy to use names.

## Background

The genetics project uses Clickhouse as it's primary data source for back-end services. The database is made of 16 tables which have inconsistencies in the way they name the same object.

In the case of variants, at least 12 of the tables have some form of reference to variants, using 5 different schemas. These are typically some form of breaking down the variant into four separate columns; one each for chromosome, position, reference allele and alternative allele. There does not appear to be any computational benefit in representing the data in this way. 

This makes it difficult to reuse queries across tables and validate the inclusion of a variant on in a table.

Since all of the data ingested into the database is provided through either the ETL or directly from the genetics team, this issue should be tackled at the point of data generation. 

## Tasks

- [ ] Update data generation to include references to variants using a common field `variant_id` in the form `CHR_POS_REF_ALT`
- [ ] Harmonise `v2d_coloc` and `studies_overlap` to use either `A/B` or `left/right` to denote variant comparison pairs.
- [ ] Update data loading scripts as necessary to follow new schema
- [ ] Update API to use new variant IDs where necessary

## Acceptance tests

Database tests:
1. When I run the query:

- [ ] `select variant_id from [ l2g_by_gsl | l2g_by_slg | manhattan | v2d_sa_molecular_trait | v2d_sa_gwas | manhattan]` I am returned a list of variant IDs. 
- [ ] `select left_variant_id, right_variant_id from v2d_coloc` I am returned a list of variant IDs. 
- [ ] `select lead_variant_id, tag_variant_id from [ d2v2g_scored | v2d_by_chrpos | v2d_by_stchr | v2d_credset]` I am returned a list of variant IDs. 
- [ ] `select left_variant_id, right_variant_id from [ v2d_coloc | studies_overlap ]` I am returned a list of variant IDs.
