### ISSUE TITLE
QC EPMC data coming from the new pipeline

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2685]
As a **data analyst** I want **to ensure the quality of the newly generated EPMC data** because **the EPMC pipeline has reached a mature stage whereby data is generated incrementally, rather than re-running the analysis for each release**.

### 1. New stream of data
EPMC has started uploading their analyses incrementally since July 13th. Under the otar025-epmc bucket we have the data in 2 directories: `Abstracts` and `Full-text`. Inside we have a directory per each date, which collects the analyses of the articles uploaded on the day before.

So the plan for the EPMC data from 22.09 on is that we will use these newly generated files. At the moment this is what you can find in both directories:
- Analysis of publications from July 13th and 14th
- Analysis of publications from July 27th until yesterday (3th August)

@saha-shyamasree said on the last monthly meeting that:
- She was going to rerun the pipeline and process the articles between July 14th and 27th.
- She was going to upload the already processed articles prior to July 13th so we end up with the whole EPMC dataset. This should be uploaded in about a week.
    - Bulk data will follow the pattern: NMP_patch-total-{number}.jsonl
    - Daily data will follow the pattern: NMP_patch-{date}.jsonl. The date is when the analysis was done, the foldername is one day later.

### 2. New association classifier
On top of the new data, we will also have a new field in the schema `association`. This classifier assesses whether a cooccurrence between a **gene/disease**:
	- Is reporting an association 
	- Is not reporting an association
	- has an ambiguous relationship

### 3. Pre-prints: a new type of publication ID
Additional article identifier for publications that have yet not been peer-reviewed. This comes in `pprid`, I'll probably create another ticket to collect how we want to integrate it into the Platform.

## Tasks
When all the previous articles are uploaded we want to:

- [ ] Check that we are not missing publications compared with the data in production.
- [ ] Check that we have publications for dates between January and July 2022.
- [ ] Check that we have publications for dates between July 14th and 27th.
- [ ] Compare the schemas so that EPMC's data doesn't compromise our literature ETL.
- [ ] Extract some basic statistics based on the association assessment. Perhaps we decide we only want evidence tagged as `association`, or we want to use this field as a criterion for scoring.
- [ ] Create ticket to scope the integration of preprints

**Comment by ireneisdoomed** [comment]
The status of the received data as of today is:
- Full text articles:
	- Available until 24/03
	- [ ] @saha-shyamasree to reprocess articles between 25/03-31/07
	- Available from 01/08 onwards
- Abstracts:
	- Available until 27/05
	- [ ] @saha-shyamasree to reprocess articles between 28/05-31/07
	- Available from 01/08 onwards


---
@saha-shyamasree I wanted to do some straightforward manual checks on the directories that are supposed to have everything we have in production and I am not sure they are complete. When I read the abstracts and FT contents and filter for those articles dated before Feb 2022 the number of unique PMIDs is extremely low (~3000). Am I doing something wrong?

```python
full_text = spark.read.json('gs://otar025-epmc/Full-text/23_03_2022')
abstract = spark.read.json('gs://otar025-epmc/Abstracts/27_05_2022')

abstract.unionByName(full_text, allowMissingColumns=True).filter(F.col('pubDate') <= ('2022-01-31')).select('pmid').distinct().count()
>> 3150
```

**Comment by saha-shyamasree** [comment]
@ireneisdoomed : are you missing about 3k PMIDs compared to the January data?

**Comment by ireneisdoomed** [comment]
@saha-shyamasree No, I see only 3000 unique PMIDs after chaining the results from the abstracts+FT. The same code outputs  > 6M PMIDs if I use the current data in production as input.

**Comment by ireneisdoomed** [comment]
The previous metric was not correct, there are more PMIDs in the data than the ones reported above.
```
~ gsutil cat gs://otar025-epmc/Full-text/23_03_2022/NMP_patch-total-9.jsonl | jq .pmid | uniq | wc -l
     625
```

This is due to a **parsing problem** when reading the data, @saha-shyamasree could you please take a look at this? I am able to parse the older files with Pandas, but it is failing now.

<details>
<summary>Full traceback</summary>
```
In [3]: example = 'gs://otar025-epmc/Full-text/23_03_2022/NMP_patch-total-9.jsonl'

In [4]: pd.read_json(example, lines=True)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-30e5916b6b37> in <module>
----> 1 pd.read_json(example, lines=True)

~/miniconda3/envs/pyspark/lib/python3.7/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    205                 else:
    206                     kwargs[new_arg_name] = new_arg_value
--> 207             return func(*args, **kwargs)
    208
    209         return cast(F, wrapper)

~/miniconda3/envs/pyspark/lib/python3.7/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    309                     stacklevel=stacklevel,
    310                 )
--> 311             return func(*args, **kwargs)
    312
    313         return wrapper

~/miniconda3/envs/pyspark/lib/python3.7/site-packages/pandas/io/json/_json.py in read_json(path_or_buf, orient, typ, dtype, convert_axes, convert_dates, keep_default_dates, numpy, precise_float, date_unit, encoding, encoding_errors, lines, chunksize, compression, nrows, storage_options)
    612
    613     with json_reader:
--> 614         return json_reader.read()
    615
    616

~/miniconda3/envs/pyspark/lib/python3.7/site-packages/pandas/io/json/_json.py in read(self)
    744                 data = ensure_str(self.data)
    745                 data_lines = data.split("\n")
--> 746                 obj = self._get_object_parser(self._combine_lines(data_lines))
    747         else:
    748             obj = self._get_object_parser(self.data)

~/miniconda3/envs/pyspark/lib/python3.7/site-packages/pandas/io/json/_json.py in _get_object_parser(self, json)
    768         obj = None
    769         if typ == "frame":
--> 770             obj = FrameParser(json, **kwargs).parse()
    771
    772         if typ == "series" or obj is None:

~/miniconda3/envs/pyspark/lib/python3.7/site-packages/pandas/io/json/_json.py in parse(self)
    883
    884         else:
--> 885             self._parse_no_numpy()
    886
    887         if self.obj is None:

~/miniconda3/envs/pyspark/lib/python3.7/site-packages/pandas/io/json/_json.py in _parse_no_numpy(self)
   1138         if orient == "columns":
   1139             self.obj = DataFrame(
-> 1140                 loads(json, precise_float=self.precise_float), dtype=None
   1141             )
   1142         elif orient == "split":

ValueError: Unexpected character found when decoding array value (2)
```
</details>

Spark does not raise an error, but only is able to parse one line (and therefore the reduced number of PMIDs reported). Our pipelines most likely will experience the same problem.

**Comment by DSuveges** [comment]
Hi @saha-shyamasree ,

When looking at the output of the incremental release process it seems the data is not in the right format. We are expecting `jsonl` format which is a newline-delimited JSON, however in the files what we are getting now, all JSON objects are concatenated without newlines. 

The presence of newlines is a [requirement in spark](https://spark.apache.org/docs/latest/sql-data-sources-json.html) to read the files: 
> Note that the file that is offered as a json file is not a typical JSON file. Each line must contain a separate, self-contained valid JSON object. For more information, please see [JSON Lines text format, also called newline-delimited JSON](http://jsonlines.org/).

That was the reason the earlier version of the pipeline produced jsonl files in the first place. Could you please prioritise this issue to allow us ingest the EPMC output?

**Comment by d0choa** [comment]
@saha-shyamasree can we get json lines as before?

**Comment by ireneisdoomed** [comment]
The parsing issue has been fixed (thanks @saha-shyamasree!), so here is a simple comparison between the data available as of today and what we have in production:

**Data in Production**
- Count of PMIDs: 6 442 978
- Count of PMCIDs: 2 241 619
- Count of PMIDs not present in the new data: 795 509

To extract the metrics in production I've used the cooccurrences datasets available at `gs://open-targets-pre-data-releases/development/output/literature-etl/parquet

**New data**
- Count of PMIDs: 25 055 565
- Count  of PMCIDs: 857 876
- Count of PPRIDs: 1

To extract the metrics in the new datasets I've used the contents of the full-text and abstract buckets that have all the processed articles that we should have in production (date up to Jan '22). This is:
	- For full text: `gs://otar025-epmc/Full-text/23_03_2022`
	- For abstracts: `gs://otar025-epmc/Abstracts/27_05_2022`

**The increase in PMIDs is really big.** Additionally, I wanted to see for how many of them the association "status" was positive. For that, I fetched all the PMIDs for which the association classifier outputted at least one association. This resulted in 3 065 034 of PMIDs (~12% of all occurrences).

---
**Code to reproduce**
```python
# To calculate the production PMIDs
cooc = spark.read.parquet('gs://open-targets-pre-data-releases/development/output/literature-etl/parquet/cooccurrences/')
failed_cooc = spark.read.parquet('gs://open-targets-pre-data-releases/development/output/literature-etl/parquet/failedCooccurrences/')
cooc.unionByName(failed_cooc, allowMissingColumns=True).select('pmid').distinct().count()
>> 6442978

# To calculate the new PMIDs
full_text = spark.read.json('gs://otar025-epmc/Full-text/23_03_2022')
abstract = spark.read.json('gs://otar025-epmc/Abstracts/27_05_2022')

abstract.unionByName(full_text, allowMissingColumns=True).filter(F.col('pubDate') <= ('2022-01-31')).select('pmid').distinct().count()
>> 25055565

# To calculate the missing PMIDs
prod_pmid = cooc.unionByName(failed_cooc, allowMissingColumns=True).select('pmid').distinct()
new_pmid = abstract.unionByName(full_text, allowMissingColumns=True).filter(F.col('pubDate') <= ('2022-01-31')).select('pmid').distinct()
prod_pmid.join(new_pmid, on='pmid', how='left_anti').distinct().count()
>> 795509

# To calculate the PMIDs with a positive association
(
    abstract.unionByName(full_text, allowMissingColumns=True).filter(F.col('pubDate') <= ('2022-01-31'))
    .withColumn('cooc', F.explode('sentences.co-occurrence'))
    .select(F.explode('cooc.association').alias('assoc_analysis'), 'pmid')
    .groupBy('pmid').agg(F.collect_set('assoc_analysis').alias('assoc_analysis'))
    .filter(F.array_contains(F.col('assoc_analysis'), 'YGD')).count()
)
>> 3065034
```

**Comment by saha-shyamasree** [comment]
@ireneisdoomed : can you kindly check the abstract folder. This submission contains pre-print abstracts, the pmid count has gone up.

**Comment by ireneisdoomed** [comment]
@saha-shyamasree The counts obtained above are a result of the attached code. The counts are not only taking into account the abstracts, but abstracts and full text references with a date prior to Feb '22.

As I was saying, if the input data folder is correct, something seems to be off. Even just by looking at the abstracts, the count of pre prints is 1. 
```
abstract.select('pprid').distinct().count()
1
```

**Comment by saha-shyamasree** [comment]
@ireneisdoomed I just check, and it seems all the Pre-prints ide went under the pmid. I will look into it and apply some fix and update the code accordingly. I am on leave today and tomorrow, so it will be Thursday.

**Comment by ireneisdoomed** [comment]
As discussed in today's lead meeting, since the new pipeline is incremental we need to account for modifications or retractions in a literature reference by keeping only the latest record for an ID.
@JarrodBaker has pointed out that this approach could lead to an overhead as such modifications start to accumulate over time, so we might explore the option of filtering this data incrementally as well. For that, we want to have an estimated idea of how many of these modifications there are in the entire dataset.

**Comment by ireneisdoomed** [comment]
A comment from @JarrodBaker on 16/11:

> The literature step in the pipeline is a series of 4 tasks: processing, embedding, vectors, evidence. The Pipeline is breaking at the 'processing' (first step).
The errors seen in the driver logs just point to a write task failing and the executor being killed.
I have been able to run the step on a small subset of the data ~5GB and the process runs without breaking (`literature-4c6lxoprwh5hs`). For contrast, the complete incremental dataset is 176GB. (Note, this is _smaller_ than the 22.01 dataset which is 184.66GB!). A larger subset (~150GB) of data failed (`literature-sz4ijma73dhmw`)
I've tried various cluster configurations to no effect. The problem seems to be a single executor fails a write task. Ricardo is helping me try and get the logging output of the executors so that we can diagnose without shooting in the dark.
Some notes on the data:
There are a number of files in both the full-text and abstracts folders with bad records (eg `/Abstracts/22_08_2022/NMP_patch-21-08-2022-0.jsonl`). When you read this file into Spark you'll get a `_corrupt_record` column. Similarly examining it with `jq` will show that it isn't valid JSON. I made a copy of the data and removed all the bad files (throwing away lots of good data I suppose). The pipeline still breaks.
Notes on preprints:
EPMC have added an additional field to contain preprint IDs so we're going to have up the literature pipeline to include that. The code is quite dense, so it might not be a trivial change. Currently there is only a single pre-print included in the data.

**Comment by ireneisdoomed** [comment]
I can confirm that a fraction of the IDs present in the `pmid` field are actually preprints. We went from 6M to 25M references, but only 500k of them are guilty of being pre prints. So PPRIDs are not the reason of the increment in coverage, as I was expecting, however we should take them into account in case we want to filter them out initially.

**Comment by ireneisdoomed** [comment]
Another finding is that there are +7M literature IDs where the sentences array is empty. This basically means that no significant matches were found for that article.

**Comment by saha-shyamasree** [comment]
Hi Irene, one of the issue I identified before leaving was in the condition that Zunaira used to create day wise / incremental data retrieval. I wrote scripts so that EPMC team can run the OT pipeline for any given day (underneath it uses Zunaira 's code) and for any range to deal with cluster related issues where the pipeline doesn't finish. Please contact them if and when u have empty folder, i.e no publication on a day or way too many (this bug needs to be fixed by Zunaira). Please refer to the OpenTargetOrchestrator code from EPMC gitlab, it's under my name but open.

**Comment by saha-shyamasree** [comment]
Zunaira was supposed to look at her code, but she has been quite busy as far as I am aware.

**Comment by ireneisdoomed** [comment]
In sum, when the raw data is filtered to include those records where 2 terms co-occur, the reported explosion in the number of PMIDs goes away.

Now that we are going to ingest the new EPMC data, @JarrodBaker has flagged that the number of publications from 2010 onwards has decreased compared to what we have in production. This is being investigated in #2852. I am closing this ticket as no pending actions are required.
