### ISSUE TITLE
Update sQTL `phenotypeId` field in V2D credset 

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#2688]
In the v2d_credset dataset there is a field called `phenotype_id`. The API expects this to be a ENSG ID, and is used to map between datasets. This is incorrect and it results in us dropping ~25m of ~60m records. sQTLs only account for a portion of this data-loss, with the remainder caused by a more general issue (ticket pending). In the sQTL data this field includes additional metadata regarding the splice; for example `phenotypeId`: ‘chr9:13110740:13112024:clu_56974:ENSG00000107186’. 

When the API tries to resolve this it cannot find a gene with that ID and does not return the expected data.

This problem relates to opentargets/issues#2682 regarding data loss, and impacts the FE development work (see opentargets/issues#2623). 

The proposed solutions for both of these tickets work around the issue, rather than addressing the problem. The `phenotype_id` field should not be relied upon to contain an ENSG ID. An additional column needs to be added to the `credset` data called `gene_id`. 

A new field needs to be added by the genetics team in preparation of the credset dataset `geneId` which includes the ENSG ID extracted from the `sqtl` entries, eg.

```json
{
"phenotype_id":  "chr9:13110740:13112024:clu_56974:ENSG00000107186"
"gene_id": "ENSG00000107186"  
}
```
We would expect the field `gene_id` never to be null for `qtl` studies, and always null for `gwas` studies.

The FE can then choose how this information is displayed, whether all the sQTLs or just the most significant are displayed. 

## Tasks

- [x] Update data generation steps to include the new field `gene_id` and update the `phenotype_id` field so that only the field `gene_id` is present. (Jack)
- [x] Update the SQL loading scripts to include new fields (somewhere [here](https://github.com/opentargets/genetics-backend/tree/master/loaders/clickhouse)) (Jarrod)
- [x] Update the API to include a new field to expose a field `geneId` of type `Option[String]` (Ricardo)
- [x] Update the API to change parameter `phenotypeId` to `geneId` on qtl endpoints, eg. qtlRegional
- [x] Update the API to query qtl data using the field `geneId`. (see `components/Backend.scala` method `qtlCredibleSet`)
- [ ] _[Optional]_ Update the API to log errors when there is a database error. It currently silently falls back to an empty list with no notification. 
- [ ] Any relevant FE work to use the new field to display sQTL metadata. (Ricardo)

There should be no update necessary to the ETL, as this data is passed through directly from the data team to the database. This might fall under some ETL QA though where we want to confirm all the mappings are valid.  

## Background

To unblock the API work I have executed the following query against the development database to create the necessary new field for the API to query:

```sql
ALTER TABLE v2d_credset
ADD COLUMN IF NOT EXISTS gene_id Nullable(String)
ALTER TABLE v2d_credset
UPDATE gene_id = phenotype_id
WHERE startsWith(phenotype_id, 'ENSG')
```
## Notes

- We're using lower camel case in the API, and snake case in the data / DB. This it to ensure consistency with current field contexts. 

### Data validation
- [x] The query `select gene_id from v2d_credset where gene_id is not null` returns valid results.
- [x] `select count(gene_id) from v2d_credset where data_type = 'gwas' and gene_id is not null` returns 0
- [x] The query `select count(gene_id) from v2d_credset where startsWith(gene_id, 'chr')` returns 0
- [x] `select count(gene_id) from v2d_credset where startsWith(gene_id, 'ENSG)` returns the same value as `select count() from v2d_credset where data_type != 'gwas'`

###  API validation
- [ ] The following query returns a valid entry:
```
query sqtl_query {
  qtlCredibleSet(studyId: "GTEx-sQTL", 
    variantId: "19_218383_G_T", 
    geneId: "ENSG00000105556", 
    bioFeature: "Heart_Atrial_Appendage"){
		spliceId
  }
}
```

**Comment by ireneisdoomed** [comment]
For the time being the credible set (pre ETL) has been patched in the same way as reported in #2670 for coloc.

New output: `gs://genetics-portal-dev-staging/finemapping/220224_merged/credset`
Old output: `gs://genetics-portal-dev-staging/finemapping/220224_merged/credset_obsolete`


The snippet:
```python
credset_path = 'gs://genetics-portal-dev-staging/finemapping/220224_merged/credset_obsolete'
phenotype_gene_path = 'gs://ot-team/dochoa/phenotype_id_gene_luts/'

credset = spark.read.json(credset_path)
phenotype_gene_lut = spark.read.csv(phenotype_gene_path, sep='\t', header=True).select(F.col('phenotype_id').alias('right_phenotype_id'), F.col('gene_id').alias('right_gene_id'))

credset_fix = (
    credset.join(
        phenotype_gene_lut,
        credset['phenotype_id'].eqNullSafe(phenotype_gene_lut['right_phenotype_id']),
        how='left',
    )
    .drop('right_phenotype_id')
    .withColumn(
        'gene_id',
        F.when(F.col('right_gene_id').isNull(), F.regexp_extract('phenotype_id', r'(ENSG\d+)', 1)).otherwise(
            F.col('right_gene_id')
        ),
    )
    .drop('right_gene_id', 'phenotype_id')
    .distinct()
)

credset_fix.repartition(200).write.option('compression', 'gzip').json('gs://genetics-portal-dev-staging/finemapping/220224_merged/credset')
```

Some checks:
```python
credset.count()
>> 60090436

credset_fix.count() # Again, slight increase due to the 1:M phenotype/gene relationship
>> 60095556

credset_fix.filter(F.col('type') != 'gwas').filter(F.col('gene_id').isNull()).count()
>> 0

credset_fix.filter(F.col('type') == 'gwas').filter(F.col('gene_id').isNull()).count()
>> 5077645

credset_fix.schema == credset.schema
>> False
```

In this case the fix results in a different schema because we are dropping `phenotype_id` in favour of `gene_id`.
```python
credset_fix.printSchema()
>> root
 |-- bio_feature: string (nullable = true)
 |-- is95_credset: boolean (nullable = true)
 |-- is99_credset: boolean (nullable = true)
 |-- lead_alt: string (nullable = true)
 |-- lead_chrom: string (nullable = true)
 |-- lead_pos: long (nullable = true)
 |-- lead_ref: string (nullable = true)
 |-- lead_variant_id: string (nullable = true)
 |-- logABF: double (nullable = true)
 |-- multisignal_method: string (nullable = true)
 |-- postprob: double (nullable = true)
 |-- postprob_cumsum: double (nullable = true)
 |-- study_id: string (nullable = true)
 |-- tag_alt: string (nullable = true)
 |-- tag_beta: double (nullable = true)
 |-- tag_beta_cond: double (nullable = true)
 |-- tag_chrom: string (nullable = true)
 |-- tag_pos: long (nullable = true)
 |-- tag_pval: double (nullable = true)
 |-- tag_pval_cond: double (nullable = true)
 |-- tag_ref: string (nullable = true)
 |-- tag_se: double (nullable = true)
 |-- tag_se_cond: double (nullable = true)
 |-- tag_variant_id: string (nullable = true)
 |-- type: string (nullable = true)
 |-- gene_id: string (nullable = true)
```
