### ISSUE TITLE
Update blog: Ghost and theme

### ISSUE THREAD

**Issue by LucaFumis** [opentargets/issues#2693]
As a **developer** I want **to run the latest version of the blog platform** in order **to avoid compatibility issues**.
@HelenaCornu please update/add/change as you see fit.

## Background

The blog is now hosted by Ghost and is due to be updated to the latest version(v5). The theme is a customised version of the `liebling` theme.

## Tasks

- [x] Identify any potential issues (e.g. what to upgrade first, theme or ghost version)
- [x] Update theme as per issue https://github.com/opentargets/issues/issues/2698
- [x] Update Ghost: link at the top of the admin page

## Acceptance tests

The blog displays without issues

How do we know the task is complete? 

1. From profile > what's new we can check the Ghost version

**Comment by LucaFumis** [comment]
The blog is now running on Ghost 5 (v5.10.1) with the new version of the Liebling theme; seems to be working OK to me:
  - multiple authors 
  - post's comments

I'm not sure which posts have comments/discussions going on - @HelenaCornu could you please double check just to make sure the comments feature is supported correctly.

There are some JS errors which do not appear to affect functionality - these were present also before, so are not related to the update: I had a look, but will need to investigate further. I will open a separate ticket for it.

**Comment by HelenaCornu** [comment]
Thanks @LucaFumis!

- The comments look good — this post has a comment and it appears as expected: https://blog.opentargets.org/open-targets-platform-21-06-release/

- The multiple author feature is working as before — this post has three authors (https://blog.opentargets.org/q-n-a-reactome-visualisations/). It's not the prettiest view, but it works.
