### ISSUE TITLE
Update Ghost (blog) theme

### ISSUE THREAD

**Issue by LucaFumis** [opentargets/issues#2698]
As a **developer** I want to **run Ghost locally** because **I need to update and test a theme**

## Background

The Open Targets blog uses a modified version of the `Liebling` Ghost theme. Unfortunately not all the changes are available in Github.
The newest version of the theme offers support for Ghost v5 so we need to update our fork of the theme with the latest changes available.
For testing/dev purposes we'll also probably want to run Ghost locally...

## Tasks

- [x] Merge new changes in original theme, fixing conflicts
- [x] Run Ghost locally
- [x] Since we're at it, we could also rename default branch to `main`

## Acceptance tests

How do we know the task is complete? 

1. We can run the updated theme locally and/or
2. Check the theme with the Ghost theme app: https://gscan.ghost.org/

**Comment by LucaFumis** [comment]
Hi @HelenaCornu adding you in for reference and in case of comments or ideas
