### ISSUE TITLE
New Clinical Significance terms from EVA

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2705]
As reported on Aug 24 from EVA, the ClinVar evidence now contains a broader set of clinical significance terms. The new terms:

- low penetrance
- uncertain risk allele
- established risk allele

Details on the update: [pdf](https://clinicalgenome.org/site/assets/files/4531/clingenrisk_terminology_recomendations-final-02_18_20.pdf)

## TODOs

- [x] Adding these values to the JSON schema
- [x] Release JSON schema for the September OpenTargets Platform release that contains this modification.
- [x] Update ETL configuration to handle and assign score to evidence with these clinical significance values.
- [x] Add the new classes to documentation

**Comment by DSuveges** [comment]
- PR on JSON schema merged. [PR#160](https://github.com/opentargets/json_schema/pull/160)
- JSON schema release is out: [v2.2.8](https://github.com/opentargets/json_schema/releases/tag/2.2.8)

**Comment by DSuveges** [comment]
How the scoring is sorted out for these new categories:
```
'low penetrance': 0.3,
'uncertain risk allele', 0.3,
'established risk allele', 0.5,
```
Update staged: [PR#259](https://github.com/opentargets/platform-etl-backend/pull/259)

**Comment by DSuveges** [comment]
Gitbook updated and merged.
