### ISSUE TITLE
Remove size from evidence widgets queries

### ISSUE THREAD

**Issue by LucaFumis** [opentargets/issues#2731]
As a **developer** I want to **load evidence widget without specifying the size** (from summary widget) because **new associations table will not have summary widgets**.

## Background

The new associations table will load evidence widgets on the fly, however these will not load the Summary widget which currently provides the size for the query. If no size is provided, the API returns all matching records. For ClinVar, however, the query is different (server side pagination for big queries) and it needs to be handled accordingly.

## Tasks

- [ ] Remove the size from evidence widgets (body and query)
- [ ] Address size for the ClinVar widget (query uses cursor)

## Acceptance tests

- [ ] Check all widgets (tables) work as expected

**Comment by LucaFumis** [comment]
This is now obsolete and can be closed.
We discussed and tried a couple of approaches as part of AOTF. 
Ultimately decided for a different solution, passing the query size from the associations table.
That is now (perhaps incorrectly) referred to in issue https://github.com/opentargets/issues/issues/2750
