### ISSUE TITLE
Closing down helpdesk@opentargets.org

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2749]
The helpdesk email will no longer be monitored, pushing users to the Open Targets Community instead. A separate email will be advertised to partners to provide confidential support. 

## Background

- Queries sent to helpdesk@opentargets.org are either reposted to the Community, or users are encouraged to post their question there. This creates additional work for the helpdesk team.
- The team does not have capacity to assist all users individually, especially since many of the questions sent to the helpdesk have already been answered on the Community.
- We aim to provide fast-track support to members of the Open Targets consortium. It can be difficult to spot their questions among all the queries that come in. 

Therefore, from the next release, the helpdesk will no longer be monitored. Instead, an automatic response will be set up, pointing users to the Community. We will remove references to the helpdesk email addresses on the Platform, Genetics, and corporate website. 

We will continue to provide confidential email support to our partners, using a newly-created email address.

## Tasks

Remove the helpdesk email address from **footers**:

- [x] the Platform footer
- [x] the Genetics footer
- [x] the PPP footer (replace with new email: ask Helena or Annalisa for the address)

**Documentation** — @HelenaCornu 
- [x] the Platform documentation
- [x] the Genetics documentation

**Contact us**
- [x] the Platform "Contact us" button (remove entirely?)
- [x] the Genetics "Contact us" button (remove entirely?) 
- [x] the Community "Contact us" button (remove entirely?) -- @HelenaCornu suggested this style for the Community header links:  `Platform    Genetics     Blog     opentargets.org` (removing the contact us link)
- [x] the PPP "Contact us" button (replace with new partner-only email)

**Templates** — @HelenaCornu 
- [x] the training, presentation, and poster templates

Other: — @HelenaCornu 
- [x] Add a [code of conduct](https://docs.google.com/document/d/1-zWl9SigT-poPvl91CtOGW7OrQDRhuMly9S0OFLJ9zc/edit#heading=h.z4p7k96jtgr3) to the Community
- [x] Add a [readme](https://docs.google.com/document/d/1-zWl9SigT-poPvl91CtOGW7OrQDRhuMly9S0OFLJ9zc/edit#heading=h.gsr1taonewn) to the Community
- [x] Set up the new email address
- [ ] Set up automatic response on the helpdesk@ email address

## Questions

Is the helpdesk@ email address featured anywhere else?
Is it possible to have a new email address in the PPP footer but not the Platform footer?

**Comment by JarrodBaker** [comment]
Good idea! There are some references to the helpdesk in some of the 'code of conduct' files on Github.

@carcruz : can you confirm whether the helpdesk email is configurable per platform/partner release?

**Comment by HelenaCornu** [comment]
Helpdesk email address also mentioned in the Google cloud public dataset pages for Platform and Genetics. 

- [ ] Write to the Google BQ team and ask them if this can be amended.

**Comment by HelenaCornu** [comment]
Additional updates to the frontend to go out simultaneously.

For @chinmehta: 

Add new partner to:
- [ ] the Platform footer
- [ ] the PPP footer
- [ ] the Genetics footer

This should go between EMBL-EBI and GSK. 

For @HelenaCornu:

- [ ] Update corporate website footer
- [ ] Add new logo to home page
- [ ] Add text and logo to partner page

Other:
- [ ] Add new partner to the Community footer

Please note, we are currently aiming to release this on **14 November**.

**Comment by buniello** [comment]
**Intranet pages**

- [ ] Adding Genentech in list of Partners on Homepage

- [ ] Adding Genentech logo on ABOUT page and update text below the logos

- [ ] Updating the PEOPLE section

I believe @HelenaCornu usually updates the Intranet pages, however I would be very happy to learn how to do that if provided with pages source code.

**Comment by HelenaCornu** [comment]
> 

I have updated the homepage and about page. To update the **people** section, we need a list of people to add with, for each person:

- An image
- An email address
- A short bio
- A project affiliation*

*not essential but ideally

**Comment by buniello** [comment]
I have updated community header/footer

**Comment by HelenaCornu** [comment]
Thank you all for your help with this!
