### ISSUE TITLE
Add no-op step to ETL to move files from input to output directory

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#2812]
As a developer I want a way to move files without manipulation because 
Platform Output Support should only deal with output files and be blind
to the input files. 

## Background

The PIS project gathers the inputs necessary for the Open Targets Platform. 
The vast bulk of these are manipulated using the ETL to generate the files
necessary for the Platform application. There is at least one exception to this
in the form of sequence ontology where PIS gets the raw file which is used 
directly as an output. 

To handle this the POS project needs to know about where the inputs and the 
outputs are in the release process. This adds unnecessary complexity to the 
release process and is difficult for external users to recreate. 

## Tasks

- [ ] Update ETL with new 'no-op' step which can be used to move files within GCP
- [ ] Update POS to remove mention of the inputs directory.
- [ ] Update workflows to include new step.

## Acceptance tests

1. When I run the full workflow _all_ the necessary files for POS land in the output directory.
2. When I look at the POS project I don't see a variable `config_direct_json`.

**Comment by d0choa** [comment]
@mbdebian I'm tagging you to evaluate how likely is that we work on this soon

**Comment by mbdebian** [comment]
My point of view is that we need to split this issue in two separate issues:
1. On one hand we want a new _passthrough_ step in the ETL where, through the config file, we tell it each dataset that needs to pass through, where to collect the data and where to put it.
2. On the other hand, we need to create a new issue on updating POS for, whatever it was working with from the _inputs_, to collect it from the _ETL outputs_ now.
These updates, if useful for the next release, could be part of it.
@d0choa , thoughts?

**Comment by javfg** [comment]
Once the ETL is run using airflow (#3396), this will no longer be a concern. We can handle the moving of data from input to output in the graph.
