### ISSUE TITLE
Output literature sentences in appropriate data type

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#2825]
As a developer I want to produce clean, validated, reliable literature sentences.

## Background

The current literature step in the ETL produces an output called `literature` which is used to populate the `literature` table in the Clickhouse database. 

This table has the schema: 

```

ot-genetics :) describe literature

DESCRIBE TABLE  literature

Query id: 6e96e78c-a208-4b7e-814a-d0da461f6046

┌─name──────┬─type─────────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ pmid      │ UInt64           │              │                    │         │                  │                │
│ pmcid     │ Nullable(String) │              │                    │         │                  │                │
│ date      │ Date             │              │                    │         │                  │                │
│ year      │ UInt16           │              │                    │         │                  │                │
│ month     │ UInt8            │              │                    │         │                  │                │
│ day       │ UInt8            │              │                    │         │                  │                │
│ sentences │ Nullable(String) │              │                    │         │                  │                │
└───────────┴──────────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘

7 rows in set. Elapsed: 0.001 sec. 
```
The `sentences` field is actually a very large JSON blob with all of the sentences used by that publication. 

An example of the JSON:

```
[
   {
      "section":"abstract",
      "matches":[
         {
            "label":"systemic amyloidosis",
            "keywordType":"DS",
            "keywordId":"EFO_1001875",
            "startInSentence":48,
            "endInSentence":68,
            "sectionStart":0,
            "sectionEnd":249
         },
         {
            "label":"amyloidosis",
            "keywordType":"DS",
            "keywordId":"EFO_1001875",
            "startInSentence":156,
            "endInSentence":167,
            "sectionStart":576,
            "sectionEnd":753
         },
         {
            "label":"apoAs",
            "keywordType":"GP",
            "keywordId":"ENSG00000118137",
            "startInSentence":30,
            "endInSentence":35,
            "sectionStart":968,
            "sectionEnd":1118
         },
         {
            "label":"apoAI",
            "keywordType":"GP",
            "keywordId":"ENSG00000118137",
            "startInSentence":189,
            "endInSentence":194,
            "sectionStart":0,
            "sectionEnd":249
         },
         {
            "label":"apoAI",
            "keywordType":"GP",
            "keywordId":"ENSG00000118137",
            "startInSentence":7,
            "endInSentence":12,
            "sectionStart":468,
            "sectionEnd":576
         },
         {
            "label":"apoAI",
            "keywordType":"GP",
            "keywordId":"ENSG00000118137",
            "startInSentence":40,
            "endInSentence":45,
            "sectionStart":576,
            "sectionEnd":753
         },
         {
            "label":"apoAI",
            "keywordType":"GP",
            "keywordId":"ENSG00000118137",
            "startInSentence":5,
            "endInSentence":10,
            "sectionStart":753,
            "sectionEnd":845
         },
         {
            "label":"apoAI",
            "keywordType":"GP",
            "keywordId":"ENSG00000118137",
            "startInSentence":5,
            "endInSentence":10,
            "sectionStart":845,
            "sectionEnd":968
         },
         {
            "label":"apoAII",
            "keywordType":"GP",
            "keywordId":"ENSG00000158874",
            "startInSentence":109,
            "endInSentence":115,
            "sectionStart":0,
            "sectionEnd":249
         },
         {
            "label":"apoAII",
            "keywordType":"GP",
            "keywordId":"ENSG00000158874",
            "startInSentence":200,
            "endInSentence":206,
            "sectionStart":0,
            "sectionEnd":249
         },
         {
            "label":"apoAII",
            "keywordType":"GP",
            "keywordId":"ENSG00000158874",
            "startInSentence":17,
            "endInSentence":23,
            "sectionStart":468,
            "sectionEnd":576
         },
         {
            "label":"apoAII",
            "keywordType":"GP",
            "keywordId":"ENSG00000158874",
            "startInSentence":22,
            "endInSentence":28,
            "sectionStart":576,
            "sectionEnd":753
         },
         {
            "label":"apoAII",
            "keywordType":"GP",
            "keywordId":"ENSG00000158874",
            "startInSentence":33,
            "endInSentence":39,
            "sectionStart":576,
            "sectionEnd":753
         },
         {
            "label":"apoAII",
            "keywordType":"GP",
            "keywordId":"ENSG00000158874",
            "startInSentence":15,
            "endInSentence":21,
            "sectionStart":753,
            "sectionEnd":845
         },
         {
            "label":"apoAII",
            "keywordType":"GP",
            "keywordId":"ENSG00000158874",
            "startInSentence":15,
            "endInSentence":21,
            "sectionStart":845,
            "sectionEnd":968
         },
         {
            "label":"reactive amyloidosis",
            "keywordType":"DS",
            "keywordId":"MONDO_0019439",
            "startInSentence":228,
            "endInSentence":248,
            "sectionStart":0,
            "sectionEnd":249
         }
      ]
   },
   {
      "section":"title",
      "matches":[
         {
            "label":"reactive amyloidosis",
            "keywordType":"DS",
            "keywordId":"MONDO_0019439",
            "startInSentence":69,
            "endInSentence":89
         }
      ]
   }
]
```
We want a new table with the schema:

```
pmid: Int64
pmcid: Nullable(String)
section: String
label: String
keywordType:  String
keywordId: String
startInSentence: Int
endInSentence: Int
sectionStart: Nullable(Int)
sectionEnd: Nullable(Int)
```
This will then be queried by the API to pull all the sentences for a publication. 

## Tasks

- [x] Update the ETL to change the output of `literatureIndex` so as not to include `sentences`
- [x] Update the ETL to add an output `publicationSentences` which will provide the inputs for loading in Clickhouse as specified above.
- [x] Update POS to load the new table into Clickhouse
- [x] Update API to resolve sentences from the new table.
