### ISSUE TITLE
Add CVD metabolic biomarkers from PMID: 32150548 to gene_burden

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2833]
Riveros-Mckay et al. report the results of gene-based analyses of rare variants and metabolic biomarkers relevant to cardiovascular disease. This work was initially scoped in #2604.

Some notes:
- 226 NMR metabolic biomarkers (serum lipoproteins, lipids and amino acids)
- 7k healthy participants from the INTERVAL cohort
- Gene-based analysis results using rare-variant (MAF <1%) aggregate tests:
    - confirmed associations at _APOB_, _APOC3_, _PAH_, _HAL_ and _PCSK_
    - novel associations _ACSL1_, _MYCN_, _FBXO36_ and _B4GALNT3_
- The main approach is to:
    - Run the tests on WES data from 3741 people - this will yield the discovery dataset
    - Run the tests on WGS data from 4301 people for those found significant (pval < 5e-3)
        - Here they also make use of related biomarkers that are treated as covariates to boost power.
    - Meta-analysis of both datasets with METASKAT after adjusting for multiple testing (pval < 2.5e-6)
- The main results are reported in Table 1 (aggregated on the gene, reporting only the most significant trait)
- All significant results are in the Supp Table 2 and 3.
    - Table 2 reports the analyses done on LOF variants
    - Table 3 reports the analyses done on LOF + deleterious missense variants 
- The single point associations are already reported in the GWAS Catalog: https://www.ebi.ac.uk/gwas/publications/32150548

## Tasks

- [x] Filter the results to extract the significant associations that we want to include eventually
- [x] Map the traits to an EFO term - most of them will need to be added to EFO
- [x] Add the data to the curation repo to generate evidence

**Comment by ireneisdoomed** [comment]
The most significant part of this issue is mapping the metabolites to EFO.

After taking a look at the data, I've filtered the results to include only the significant associations from the meta analysis between the discovery and validation cohort.

With this I filter down the results to ~130 evidence (8 distinct genes, 63 measurements). The results can be analysed in the working spreadsheet (`meta_significant_assocs`) https://docs.google.com/spreadsheets/d/1hbW2NmgLeHu6QiVZxwUZsfpWmhPFenfkbCRZTCKSGhE/edit#gid=1785912640

The code to filter the raw data:
```python
# burden with lof variants only
table_s2 = pd.read_excel("/Users/irenelopez/Downloads/pgen.1008605.s005.xlsx", sheet_name="Supp Table 2", header=1).iloc[:3177]
lofs_filtered = table_s2.query("`METASKAT P (discovery+validation, adjusted)` <=  2.5e-6")
lofs_filtered["qualifying_variants"] = "LOF"

# burden with lof and deleterious missense variants
table_s3 = = pd.read_excel("/Users/irenelopez/Downloads/pgen.1008605.s006.xlsx", sheet_name="Supp Table 3", header=1)
lofs_missense_filtered = table_s3.query("`METASKAT P (discovery+validation, adjusted)` <=  2.5e-6")
lofs_missense_filtered["qualifying_variants"] = "LOF+missense"

# merge
m = pd.concat([lofs_extended, lofs_missense_extended], axis=0, ignore_index=True)
```

**Note:** The meta analysis does not incldue all the novel findings reported in the Table 1. We have SCARB1 or LIPC missing because these genes were not meeting the meta analysis criteria. To report them, I'll have to curate the results on the discovery sample.

**Comment by ireneisdoomed** [comment]
Regarding the metabolites mappings, I've tried to find an existing mapping for the relevant traits mentioned above. However, the measurements are overall quite granular and correlated, so in most of the cases I couldn't find an appropriate mapping.

I've submitted a ticket to EFO with 47 terms that we would need to have included if we wanted to report this source with detail.
The mappings can be found in `meta_significant_traits` in the [spreadsheet](https://docs.google.com/spreadsheets/d/1hbW2NmgLeHu6QiVZxwUZsfpWmhPFenfkbCRZTCKSGhE/edit#gid=1785912640).

However, if EFO doesn't add them in their upcoming release, we could also map them with less granularity, as less fine-grained terms exist. For example, we have a lot of variations of lipoportein measuremtns such as "Total cholesterol in _small_ VLDL"/"Total cholesterol in _very small_ VLDL". Mapping this to a more general term will mean that most of the evidence would be highly duplicated.

**Comment by ireneisdoomed** [comment]
154 new pieces of evidence will be added from this publication:
- 16 targets
- 61 measurements
- 109 associations

The collapsing statistical method is SKAT-O, a different way of aggregating on the gene than the normal burden, therefore we don't have effect sizes for these associations.

For example, they report many associations involving PCSK9 with the test that aggregates LOF and missense variants. Practically all measurements are related to lipidic metabolites, and PCSK9 is a classic example of risk of CVD.
The most significant association they report in their Table 1 is with free cholesterol in IDL measurements:
<img width="725" alt="image" src="https://user-images.githubusercontent.com/45119610/214019818-ecc904a3-f416-473b-b0de-ac3a9c8ed715.png">

And the corresponding evidence:
```
 allelicRequirements              | [GCST90179195]
 ancestry                         | EUR
 ancestryId                       | HANCESTRO_0005
 beta                             | null
 betaConfidenceIntervalLower      | null
 betaConfidenceIntervalUpper      | null
 cohortId                         | INTERVAL
 datasourceId                     | gene_burden
 datatypeId                       | genetic_association
 diseaseFromSource                | Free cholesterol in IDL
 diseaseFromSourceId              | null
 diseaseFromSourceMappedId        | EFO_0022181
 literature                       | [32150548]
 oddsRatio                        | null
 oddsRatioConfidenceIntervalLower | null
 oddsRatioConfidenceIntervalUpper | null
 pValueExponent                   | -10
 pValueMantissa                   | 2.39
 projectId                        | null
 resourceScore                    | 2.39E-10
 sex                              | null
 statisticalMethod                | meta-analysis
 statisticalMethodOverview        | Meta-analysis of SKAT-O tests carried out with LOF and missense variants with a MAF smaller than 1%
 studyCases                       | null
 studyCasesWithQualifyingVariants | null
 studyId                          | 7142
 studySampleSize                  | null
 targetFromSourceId               | ENSG00000169174
```


For a few cases, we can link the evidence with a GCST - however this is very rare as the single point associations were lacking statistical power overall.
```
 allelicRequirements              | null
 ancestry                         | EUR
 ancestryId                       | HANCESTRO_0005
 beta                             | null
 betaConfidenceIntervalLower      | null
 betaConfidenceIntervalUpper      | null
 cohortId                         | INTERVAL
 datasourceId                     | gene_burden
 datatypeId                       | genetic_association
 diseaseFromSource                | Total lipids in medium VLDL
 diseaseFromSourceId              | null
 diseaseFromSourceMappedId        | EFO_0022153
 literature                       | [32150548]
 oddsRatio                        | null
 oddsRatioConfidenceIntervalLower | null
 oddsRatioConfidenceIntervalUpper | null
 pValueExponent                   | -7
 pValueMantissa                   | 6.2
 projectId                        | null
 resourceScore                    | 6.2E-7
 sex                              | null
 statisticalMethod                | meta-analysis
 statisticalMethodOverview        | Meta-analysis of SKAT-O tests carried out with LOF and missense variants with a MAF smaller than 1%
 studyCases                       | null
 studyCasesWithQualifyingVariants | null
 studyId                          | 7142
 studySampleSize                  | null
 targetFromSourceId               | ENSG00000134323
```

The new curation has been added to our [repo](https://github.com/opentargets/curation).
