### ISSUE TITLE
Data related tasks for 23.02 Platform release

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2834]
This is a collection of tasks of the data team for the upcoming 2023 February release. It is important to properly time and scope these task to impose the minimal load on the backend team.

## Tasks

- [x] Integrate new sources for gene burden (#2833). @ireneisdoomed 
- [x] Explore the possibility to ingest CRISPR screens (CRISPR Catalog, CRISPR Brain) (BE, FE depends) (#2821) @DSuveges 
- [x] Update molecular probes. @ireneisdoomed 
- [x] Apply stop reasons model to new ChEMBL evidence @ireneisdoomed 
- [x] Ingest AOPWiki (#2838) @ireneisdoomed 
- [x] Update ot_genetics with QTL based directionality information (BE, FE depends) @ireneisdoomed @DSuveges 
- [x] Update schema for the above update. (BE depends) @ireneisdoomed @DSuveges (#2840)
- [x] Update evidence parser configuration (new EFO, schema, sources etc), create release. @tskir 
- [x] Run evidence parsers. Review the run to make sure all evidence file generated properly. @tskir 
- [x] Run pre-etl metrics, do QC data to make sure there's no noticeable leakage. @tskir 
- [x] Upon ETL run, run post-ELT metrics. Do QC @tskir
- [x] Review flagged dependencies in the evidence parser repo (#2839) @tskir  

Please @buniello , take a look at the above list and add more tasks if I missed anything.

**Comment by tskir** [comment]
@ireneisdoomed @DSuveges All actions are done here, can we close it?
