### ISSUE TITLE
Updating Genetics Portal evidence with the overlapping QTL effect

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2840]
This is follow up ticket on #2831.

Genetics Portal sourced disease/target evidence is enriched with QTL data as follows:
- L2G table is joined with colocalized QTLs of the same gene.
- Out of the QTLs the one with the highest absolute beta is picked.
- The direction of the effect is mapped to SO terms.
- The SO term is stored in a column called: `variantFunctionalConsequenceFromQtlId` should follow the same schema as `variantFunctionalConsequenceId`.

**Direction to SO mapping:**

- Negative beta: `SO_0002316` ([decreased_gene_product_level](http://www.sequenceontology.org/browser/current_release/term/SO:0002316))
- Positive beta: `SO_0002315 ` ([increased_gene_product_level](http://www.sequenceontology.org/browser/current_release/term/SO:0002315))
- Beta not available: `SO_0002314` ([altered_gene_product_level](http://www.sequenceontology.org/browser/current_release/term/SO:0002314))

**Tasks scoped under this ticket:**

- [x] Update JSON schema
- [x] Create release on JSON schema.
- [x] Update evidence parser.

**Downstream tasks:**

- [x] Update API to make sure the SO Terms are resolved.
- [x] Adding columns to evidence table with the right header + tool tip
- [ ] Updating documentation.

**Comment by JarrodBaker** [comment]
Taken from Slack: 

...we are adding a new (nullable) field to the genetics portal evidence called variantFunctionalConsequenceFromQtlId that contains sequence ontology identifiers (more info under the ticket). I’m afraid a [new field](https://github.com/opentargets/platform-api/blob/6ba32781d3c2a83201695041f435f14d13161816/app/models/entities/Evidence.scala#L455) is need in the API code (this field is not involved in the score calculation). I assume this is required to resolve the SO terms.

**Comment by d0choa** [comment]
for reference... the logic to resolve the column can be borrowed from the existing "functionalConsequenceId"

**Comment by buniello** [comment]
we need to discuss the right column header for the visualisation in FE for @LucaFumis 
We discussed `EffectOnExpression` as a possible option. Any other thoughts?

**Comment by buniello** [comment]
![Screenshot 2023-01-24 at 09.38.12.png](https://images.zenhubusercontent.com/5ef1da283f096f8317c9ca44/9dc2a487-2566-47db-9073-31b96e322cd5)

**Comment by LucaFumis** [comment]
FE changes are ready - will test once data is available in the API (endpoint field is available in dev already)

**Comment by buniello** [comment]
Field is now in the API
```

{
  "data": {
    "disease": {
      "id": "EFO_0003767",
      "evidences": {
        "rows": [
          {
            "id": "3fdc38c24977abaea5baac62baef15acbea11802",
            "disease": {
              "id": "EFO_0003767",
              "name": "inflammatory bowel disease",
              "__typename": "Disease"
            },
            "diseaseFromSource": "Inflammatory bowel disease",
            "studyId": "GCST004131",
            "studySampleSize": 59957,
            "variantId": "16_50474075_A_G",
            "variantRsId": "rs72790317",
            "literature": [
              "28067908"
            ],
            "publicationYear": 2017,
            "publicationFirstAuthor": "de Lange KM",
            "pValueExponent": -32,
            "pValueMantissa": 1.77,
            "oddsRatio": 1.38126535090563,
            "oddsRatioConfidenceIntervalLower": 1.309555805576578,
            "oddsRatioConfidenceIntervalUpper": 1.4569016161723904,
            "beta": null,
            "betaConfidenceIntervalLower": null,
            "betaConfidenceIntervalUpper": null,
            "variantFunctionalConsequence": {
             "id": "SO:0001628"
              "label": "intergenic_variant",
              "__typename": "SequenceOntologyTerm"
            },
            "resourceScore": 0.8871004581451416,
            "projectId": "GCST",
            "__typename": "Evidence"
          }

```

**Comment by LucaFumis** [comment]
Front end work complete and merged in.
