### ISSUE TITLE
Include information about the variant consequences for all burden methods

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2856]
In the new burden evidence, 40 evidence are falling to invalid because of duplication.

## Background

The current fields that identify a burden evidence as unique are: the target, the disease, the ancestry, the project, and the actual burden collapsing model.
The model's name usually reflects the filters used to define the set of variants applicable to the method. However, in this case (and for other curated datasets), the method name is common independently of the filters. This is the reason why two evidence that find the same gene/disease association on different set of variants are marked as duplicated.

## Tasks

- [ ] Go back to the curation and annotate the variant functional consequences in the model name

## Acceptance tests

How do we know the task is complete? 

1. When I go to page [APOC3/total lipids in medium VLDL](https://platform.opentargets.org/evidence/ENSG00000110245/EFO_0022153) I see 2 evidence curated from 32150548: one referring to the results with LoF variants; the other one to the results with LoF and missense variants.

**Comment by prashantuniyal02** [comment]
@ireneisdoomed, is this issue still pending? 
It seems to be resolved in the latest release of the platform?

**Comment by prashantuniyal02** [comment]
Scoped for 24.06 release:

- [ ] variant consequence for burden

- [ ] Scoping [community post](https://community.opentargets.org/t/remove-all-category-based-analysis-of-genebass-from-opentargets-platform/1393) from Shicheng_Guo

- [ ] adding more gene burden

**Comment by prashantuniyal02** [comment]
Hi @ireneisdoomed ,
