### ISSUE TITLE
Table component reimplementation

### ISSUE THREAD

**Issue by carcruz** [opentargets/issues#2887]
As an Open Targets developer, I want a new table component that is not dependent on Material-UI because it makes us dependent on a component that does not provide all its features in the open-source version.

## Background

Currently, we are using the [Table](https://v4.mui.com/components/tables/) and [DataGrid](https://v4.mui.com/components/data-grid/) components from Material-UI V4. This forces us to be dependent on Material-UI versioning and also to have a lack of features because we are using the open-source version of their components.

## Tasks

- [ ] Research different alternatives of table components or primitives to build our own table component: [TanStack Table](https://tanstack.com/table/v8), [React-data-grid](https://adazzle.github.io/react-data-grid/#/common-features), [React component table](https://github.com/react-component/table), and explore any other option. 
- [ ] Build a POC of the component and display it on the platform

## Acceptance criteria
- The component must be built with Typescript

- Handle server-side pagination
- Handle rows and columns as parameters
- Have pagination controls
- Have rows per page controls
- Sorting (Default sort on load, Sort by col (optional))
- Export
	- TSV, JSON
	- Download raw data from API *(needs to be reviewed)
- Search box globally (optional to be disabled)
- Help text tooltips 
- Colm mixing
- Stick column 
- Be able to reuse the API playground component 
- Be able to display either content base on row data and child components based on the columns (as the current table component. e.g., Publication drawing)

**Could**
- Search box by fields
- Numeric styling (align right - font mono-space)
- Property to format on bool values "globally."
- Option of vertical headers
- Filter table by parameter

**Comment by carcruz** [comment]
Discussed on FE meeting
- [ ] Abstract downloads functionality and attached it to the new table implementation
- [ ] Merge mechanism to re-use current columns object in the new table (match at least 80% of widgets)
