### ISSUE TITLE
Update POS to include the target engine information

### ISSUE THREAD

**Issue by remo87** [opentargets/issues#2909]
As a developer I want POS to load target engine information into clickhouse because the API will use the new tables to make the information accesible

## Background

The AOTF requires the creation of new tables to store the information produced by the ETL.

## Tasks

- [ ] Create the sql scripts for the log table
- [ ] Create the sql scripts for the table
- [ ] Update the load logic to look for the target engine json files

## Acceptance tests

How do we know the task is complete? 

1. The new table is loaded the content of the json files
2. The log table is loaded with the correct information
3. The null values are correctly handled 
4. The log shows that the table was loaded with the total number of records in the json file
