### ISSUE TITLE
When pmid/pmcid or pprid is not available, the value should be null

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2931]
Conceptually it makes more sense to have nulls for missing values than empty strings, plus it is easier to filter for missingness or implement validation.

## Tasks

- [ ] Literature pipeline needs to be updated to enforce this rule.
- [ ] Validate output of full-text pipeline
- [ ] Validate output of abstract pipeline
- [ ] Ensure the etl on our end ready for this update

**Comment by tsantosh7** [comment]
Hi @DSuveges In the new release I have fixed this issue. Let me know if this is fixed in the new release

**Comment by DSuveges** [comment]
In the most recent release on 2023. Apr 24, the full text data dump contains `nulls` when `pprid` is not available. That's good. However, in the entire dataset, there's no pre-prints:

```python
# preprint identifiers
pubs_w_pprid = pubs.filter(f.col('pprid').isNotNull()).count()
print(f'Publications with pprid: {pubs_w_pprid:,}')
```
`Publications with pprid: 0`

**Comment by d0choa** [comment]
We could drop ppr Ids from the schema. They are not populated and we are not using the field.

Instead, we are using the pmids that contains Pprs. Since epmc consider them as internal ids I don't see a huge amount of value in adding more granularity to the schema.

**Comment by DSuveges** [comment]
I might misunderstand you comment, but I was referring the raw json files EPMC were submitting to us. I'm not implying any change in any schema.

**Comment by d0choa** [comment]
pprid has been empty in previous rans as well. the preprint pprids have been inside the other id columns (pmcid or pmid I can't remember)

If this is still the case, we can continue working like this.

Sorry if I'm making this more confusing

**Comment by DSuveges** [comment]
Yes it was quite confusing.

**Comment by tsantosh7** [comment]
@DSuveges yes the pprids are null for the fulltext, however they are populated for the abstracts data. To maintain the same schema for both abstracts and fulltext, pprids were introduced for fulltext jsons as well. If we were to remove we could remove for both abstracts and fulltexts. However, there is no harm in including right?

**Comment by DSuveges** [comment]
Based on the QC of the data released on 28.04, this ticket can be considered done.
