### ISSUE TITLE
Update `drugWarnings` annotation in the Platform

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2943]
As part of ChEMBL32, the team has revised the drug warnings annotation to extract -when possible-  the specific adverse outcome associated with the drug warning.

**Out of 854 drugs with some sort of safety warning, 219 have specific annotation about the reported adverse outcome and their mapping to EFO**. We need to update the Drug Warnings datasets and widget to display this data.

## Tasks
Process the drugWarnings dataset to include the new fields:
`efo_term`: label of the curated EFO term that represents the adverse outcome
`efo_id`: ID of the curated EFO term that represents the adverse outcome
`efo_id_for_warning_class`: ID of the curated EFO term that represents the high level warning class

- [x] Update PIS to pull the new fields
- [x] Update the [ETL](https://github.com/opentargets/platform-etl-backend/blob/0529d18f5d90e3a197e7f3587b385a01201aafab/src/main/scala/io/opentargets/etl/backend/drug/DrugWarning.scala#L6) to integrate the new fields
- [x] Add the new fields to ES/Clickhouse and GraphQL
- [x] Update the Drug Warnings widget

## Context
An example of the new annotation is Carisopropodol, where the high level class is just "misuse" ([OT page](https://platform.opentargets.org/drug/CHEMBL1233)):
![image](https://github.com/opentargets/issues/assets/45119610/ec90a2a4-593f-4397-9c57-47f1efff4219)

and now we have the specific AOs that led to this drug being withdrawn ([chembl page](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1233/)):
![image](https://github.com/opentargets/issues/assets/45119610/b76f4295-09e0-4136-9720-4f4123d8bf5f)

More documentation about this changes [here](https://chembl.blogspot.com/2023/03/drug-warning-update-withdrawn-drugs-and.html)

**Comment by d0choa** [comment]
@ireneisdoomed could you review and close if appropriate?

**Comment by ireneisdoomed** [comment]
Looks good to me, 2 small details that'd be nice to have before going live:
- I'd like the link to point to the latest OLS, since OLS3 is no longer updated: 
    - Instead of `https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=`, use `https://www.ebi.ac.uk/ols4/ontologies/efo/terms?short_form=`
- In the tooltip, remove the extra whitespace between in `Description : ...`
