### ISSUE TITLE
Change ClinicalTrials.gov reference URL for ChEMBL evidence

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2945]
As a **user** I want **to unequivocally see what is the study backing up a ChEMBL evidence**.

## Background

A ChEMBL evidence is often based on a clinical trial submitted to ClinicalTrials.gov. The evidence links out to ClinicalTrials's search endpoint, rather than providing a direct link, which would be much more user friendly.

As an example of the change, we will go from:
https://clinicaltrials.gov/search?id=%22NCT01356004%22
to:
https://clinicaltrials.gov/ct2/show/NCT01356004

## Tasks

- [x] Communicate with ChEMBL to apply this change to their pipeline - a new file will be submitted today
- [x] QC the new submission
- [x] Minor data dependency: Change the example in the JSON schema (validation won't break)
- [ ] Minor BE dependency: Update URL in the ETL tests [here](https://github.com/opentargets/platform-etl-backend/blob/0529d18f5d90e3a197e7f3587b385a01201aafab/src/test/resources/indication_test30.jsonl#L1) and [here](https://github.com/opentargets/platform-etl-backend/blob/0529d18f5d90e3a197e7f3587b385a01201aafab/src/test/resources/chembl31_evidence_200.jsonl#L1)

## Context

The use of the search endpoint is likely to be historical, as this field didn't used to be a list so we would use `search` to reference an aggregation of studies in a single URL.

This field will affect evidence and its artifacts:
- evidence: each piece of evidence represents a single study, so there shouldn't be any problems
- knownDrugsAggregated: urls are aggregated, however we display them in a box to check each study independently

**Comment by ireneisdoomed** [comment]
Working in the latest dev version.
Pinging @opentargets/be-team in case they want to update their test data.
