### ISSUE TITLE
Implement version aware code deployment in the genetics ETL pipeline

### ISSUE THREAD

**Issue by tskir** [opentargets/issues#2946]
As a **developer** I want **version aware code deployment** because **it is necessary for multiple people to work on developing the repository without interfering with each other.**

## Background
Currently, running `make build` will upload the code and overwrite the version submitted by anyone else previously. This creates the possibility for conflicts when two or more people are attempting to run their own respective version of the code.

Additionally, `workflow_template.py` has some hardcoded values which need to be edited manually by any developer running the code on Dataproc.

## Tasks
- [ ] Update `make build` to upload code to a version specific path
- [ ] Update `workflow_template.py` to run the code from that version specific path
- [ ] Replace hardcoded parameters in `workflow_template.py` with customisable ones
- [ ] Amend developer documentation to make it clear how versioning works

## Acceptance tests
1. When running `make build`, the code is uploaded to a version specific path
2. When running `workflow_template.py`, the code is run from that version specific path

**Comment by tskir** [comment]
CC'ing @d0choa @hlnicholls for information
