### ISSUE TITLE
Migrate to FinnGen R9

### ISSUE THREAD

**Issue by tskir** [opentargets/issues#2955]
As a **developer** I want to **migrate FinnGen ingestion to F9** because **this is the latest and likely final version, which we want to ingest and process**

## Background
FinnGen R9 was released in May 2023: https://www.finngen.fi/en/access_results 

## Tasks
* [x] Update input/output configuration paths
* [x] Update path construction patterns
* [x] Update test sample data
* [x] Make sure the tests pass
* [x] Test run the updated code
* [x] Manually examine the produced data

## Acceptance tests
FinnGen R9 is ingested instead of R8
