### ISSUE TITLE
Updating evidence parsers for intogen.

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2963]
There's a new [release for intogen on 31th May](https://twitter.com/bbglab/status/1663932069926281216?s=46&t=8P0XPZTEhJc59dWjxAjJDg). Given how infrequently Intogen releases, we could assume the update comes with a series of schema changes.

## Tasks:

- [x] Download new data
- [x] Sort out existing and new data in the input bucket (`gs://otar000-evidence_input/IntOgen/data_files`)
- [x] Update parser accounting for changes in the schema
- [x] Investigate generated evidence file to identify new cancer types that need to be mapped to EFO
- [x] Update disease mapping file
- [x] Update config file
- [x] Run snakemake rule with new config
- [x] Run validation
- [x] Upload new evidence file to output bucket (`gs://otar000-evidence_input/IntOgen/json/`).

**Updates**: the progression can be followed in this draft [PR](https://github.com/opentargets/evidence_datasource_parsers/pull/162)

**Comment by DSuveges** [comment]
Stats based on the new data:
- Old evidence count: 3333
- New evidence count: 4360
- Unmapped evidence count: 1968
- Unmapped disease count: 45

**Comment by DSuveges** [comment]
Questionable mappings:
- `Plasma Cell Myeloma` -> `multiple myeloma`.
- `uveal melanoma` mapped to `HP_0007716` and `EFO_1000616` they have the same labels.

Not mapped by ontoma, but mappings might be:
- `Gastrointestinal Neuroendocrine Tumors` -> Neuroendocrine Tumor / EFO_1001901
- `Salivary Carcinoma` -> salivary gland carcinoma/MONDO_0000521
- `Chronic Lymphocytic Leukemia/Small Lymphocytic Lymphoma` -> chronic lymphocytic leukemia/EFO_0000095
- `Small Bowel Cancer` -> small intestine cancer/MONDO_0000956
- `Low-Grade Glioma, NOS` -> MONDO_0021637/low grade glioma
- `High-Grade Glioma, NOS` -> MONDO_0100342/malignant glioma
- `Diffuse Large B-Cell Lymphoma, NOS` -> EFO_0000403/diffuse large b-cell lymphoma

Less confident mappings:
- `Vulva/Vagina` -> MONDO_0001402/vaginal cancer
- `Pancreas` -> EFO_1000359 /malignant pancreatic neoplasm

Mappings for the new cancer names:

| Cancer_type_acronym   | Cancer_type_name                                        | EFO_id        | EFO_name                          |
|:----------------------|:--------------------------------------------------------|:--------------|:----------------------------------|
| UM                    | Uveal Melanoma                                          | HP_0007716    | uveal melanoma                    |
| UM                    | Uveal Melanoma                                          | EFO_1000616   | uveal melanoma                    |
| RMS                   | Rhabdomyosarcoma                                        | EFO_0002918   | rhabdomyosarcoma                  |
| RCC                   | Renal Cell Carcinoma                                    | EFO_0000681   | renal cell carcinoma              |
| LMS                   | Leiomyosarcoma                                          | EFO_0000564   | leiomyosarcoma                    |
| CHOL                  | Cholangiocarcinoma                                      | EFO_0005221   | cholangiocarcinoma                |
| MEL                   | Melanoma                                                | EFO_0000756   | melanoma                          |
| BCC                   | Basal Cell Carcinoma                                    | EFO_0004193   | basal cell carcinoma              |
| PLMESO                | Pleural Mesothelioma                                    | EFO_1000485   | pleural mesothelioma              |
| PANET                 | Pancreatic Neuroendocrine Tumor                         | EFO_1000045   | pancreatic neuroendocrine tumor   |
| LNM                   | Lymphoid Neoplasm                                       | EFO_0001642   | lymphoid neoplasm                 |
| PAST                  | Pilocytic Astrocytoma                                   | MONDO_0016691 | pilocytic astrocytoma             |
| BL                    | Burkitt Lymphoma                                        | EFO_0000309   | burkitts lymphoma                 |
| ACYC                  | Adenoid Cystic Carcinoma                                | EFO_0000231   | adenoid cystic carcinoma          |
| WDTC                  | Well-Differentiated Thyroid Cancer                      | EFO_1002017   | differentiated thyroid carcinoma  |
| COAD                  | Colon Adenocarcinoma                                    | EFO_1001949   | colon adenocarcinoma              |
| EPM                   | Ependymoma                                              | EFO_1000028   | ependymoma                        |
| CSCC                  | Cutaneous Squamous Cell Carcinoma                       | EFO_1001927   | cutaneous squamous cell carcinoma |
| MLYM                  | Malignant Lymphoma                                      | EFO_0000574   | lymphoma                          |
| MDS                   | Myelodysplastic Syndromes                               | EFO_0000198   | myelodysplastic syndrome          |
| PGNG                  | Paraganglioma                                           | EFO_1000453   | paraganglioma                     |
| CCRCC                 | Renal Clear Cell Carcinoma                              | EFO_0000349   | clear cell renal carcinoma        |
| HCC                   | Hepatocellular Carcinoma                                | EFO_0000182   | hepatocellular carcinoma          |
| OVT                   | Ovarian Epithelial Tumor                                | MONDO_0002229 | ovarian epithelial tumor          |
| PRCC                  | Papillary Renal Cell Carcinoma                          | EFO_0000640   | papillary renal cell carcinoma    |
| COADREAD              | Colorectal Adenocarcinoma                               | EFO_0000365   | colorectal adenocarcinoma         |
| RBL                   | Retinoblastoma                                          | MONDO_0008380 | retinoblastoma                    |
| CHRCC                 | Chromophobe Renal Cell Carcinoma                        | EFO_0000335   | chromophobe renal cell carcinoma  |
| NBL                   | Neuroblastoma                                           | EFO_0000621   | neuroblastoma                     |
| NPC                   | Nasopharyngeal Carcinoma                                | EFO_0004252   | nasopharyngeal neoplasm           |
| PCM                   | Plasma Cell Myeloma                                     | EFO_0001378   | multiple myeloma                  |
| PSCC                  | Penile Squamous Cell Carcinoma                          | MONDO_0018352 | squamous cell carcinoma of penis  |
| NHL                   | Non-Hodgkin Lymphoma                                    | EFO_0005952   | non-hodgkins lymphoma             |
| ES                    | Ewing Sarcoma                                           | EFO_0000174   | ewing sarcoma                     |
| ANSC                  | Anal Squamous Cell Carcinoma                            | EFO_1000081   | anal squamous cell carcinoma      |
| LIHB                  | Hepatoblastoma                                          | EFO_1000292   | hepatoblastoma                    |
| GINET                 | Gastrointestinal Neuroendocrine Tumors                  | nan           | nan                               |
| SACA                  | Salivary Carcinoma                                      | nan           | nan                               |
| CLLSLL                | Chronic Lymphocytic Leukemia[/Small](https://file+.vscode-resource.vscode-cdn.net/Small) Lymphocytic Lymphoma | nan           | nan                               |
| SBC                   | Small Bowel Cancer                                      | nan           | nan                               |
| VULVA                 | Vulva[/Vagina](https://file+.vscode-resource.vscode-cdn.net/Vagina)                                            | nan           | nan                               |
| LGGNOS                | Low-Grade Glioma, NOS                                   | nan           | nan                               |
| HGGNOS                | High-Grade Glioma, NOS                                  | nan           | nan                               |
| PANCREAS              | Pancreas                                                | nan           | nan                               |
| DLBCLNOS              | Diffuse Large B-Cell Lymphoma, NOS                      | nan           | nan                               |
| SOFT_TISSUE           | Soft Tissue                                             | nan           | nan                               |

**Comment by ireneisdoomed** [comment]
Thank you Daniel!

All suggestion from Ontoma make sense.
It also makes sense for me that we assume cancers for the less confident ones.
As for the non mapped ones, only one suggestion:
- For Gastrointestinal Neuroendocrine Tumors, I'd rather suggest [Digestive System Neuroendocrine Tumor](https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C95404)

**Comment by DSuveges** [comment]
Good. Thank you!

**Comment by DSuveges** [comment]
Some more stats highlighting improvements:

|             |   old |   new |
|:------------------|------:|------:|
| evidence_count    |  3333 |  4360 |
| association_count |  2080 |  2630 |
| target_count      |   568 |   619 |
| disease_count     |    66 |    71 |
| cohort_count      |   214 |   254 |

Interesting the new dataset has lost 660 associations, while gaining 1210. It might worth checking why we are missing associations. The 660 lost association belongs to 54 distinct diseases, 17 of them were not found in the new dataset altogether while 37 have new associations.

**Comment by DSuveges** [comment]
- The data is prepared, ready to be picked by ETL (`gs://otar000-evidence_input/IntOgen/json/intogen-2023-06-02.json.gz`). 
- Code in the evidence datasource parser repo is reviewed and merged.

**Comment by DSuveges** [comment]
New significantDriverMethods:

```
+-----------------------+
|significantDriverMethod|
+-----------------------+
|oncodriveclustl        |
|combination            |
|smregions              |
|mutpanning             |
|cbase                  |
|hotmaps                |
|dndscv                 |
|oncodrivefml           |
+-----------------------+
```

All terms were already found in the old intogen dataset, so no need to update front-end mappings.
