### ISSUE TITLE
'Do not show again' button in the switch to PPP popup

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#2967]
As a user I do not want to see the move to PPP popup every-time I access the platform if I am part of the Open Targets consortium

## Background

As a future improvement to the current implementation, we need a 'Do not show again' check box on the PPP popup and figure out when should the choices be refreshed for every user.

## Tasks

- [x] Scoping the logic for the Do not show again button
- [x] Incorporate in the current implementation
- [ ] Testing the implementation

**Comment by d0choa** [comment]
@buniello can you confirm you are happy with this to happen (at some point)? I asked Prashant to open a ticket before we forget but we need the green light from you.

**Comment by buniello** [comment]
Yes, I think we should aim for a "refresh choice/new pop-up" every week/couple of weeks.

**Comment by d0choa** [comment]
Working in dev
