### ISSUE TITLE
API endpoint to flush GraphQL cache

### ISSUE THREAD

**Issue by mbdebian** [opentargets/issues#2977]
As an Open Targets operator and/or developer, I would like to have an API endpoint to trigger a flush of the GraphQL cache

## Background
When working towards a release, we iterate intensively on the underlying data backend the API uses for serving the release data through its GraphQL interface.

The current API uses an internal caching mechanism for the GraphQL queries and their corresponding responses.

We would like to have an API endpoint that, when called, triggers a flush of this internal cache, this way, when debugging issues in the underlying data, we make sure that we can reproduce those scenarios where we have issues.

This API endpoint should be disabled by default, with an additional mechanism based on environment variables to enable it.

## Tasks

- [ ] Implement an API endpoint to flush the GraphQL cache
- [ ] An environment variable mechanism to enable/disable this endpoint

## Acceptance tests
- [ ]  When the API is deployed without setting the environment variable for this endpoint, the endpoint is disabled.
- [ ]  When the API is deployed with the environment variable for this endpoint set, the endpoint is enabled and it flushes the GraphQL cache.
- [ ] Calls to this endpoint and their effect need to be logged

**Comment by d0choa** [comment]
This might be relevant:
https://github.com/opentargets/platform-api/pull/127

**Comment by d0choa** [comment]
https://github.com/opentargets/platform-api/blob/9b7259f8d89bc5b6d8ce96e20163d44f36804427/README.md?plain=1#L23

**Comment by buniello** [comment]
can we close this?

**Comment by mbdebian** [comment]
@remo87 , please, take into account this one, when addressing opentargets/issues#2934 and opentargets/issues#2975
