### ISSUE TITLE
Remove mapping between drug warning and MedDRA

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3003]
Remove look up table between adverse effect and MedDRA code in the ETL step that processes drug warnings (and other downstream tasks).

## Background
Now that we have most of the drug warnings mapped to an EFO code, the MedDRA codes we have linked to the toxicity classes are of less value.
I suggest removing this specific piece of code from the ETL as it has lost its usefulness over time. The associated dependency is costly to maintain while providing little return.
For example, the data has changed in the latest ChEMBL release (toxicity classes are now lower cased), therefore the MedDRA codes are always null (https://github.com/opentargets/issues/issues/3002)

## Tasks

- [x] Update https://github.com/opentargets/platform-etl-backend/blob/5be39b55584d48472b3ffb10b2cfb7feb739b1f4/src/main/scala/io/opentargets/etl/backend/drug/DrugWarning.scala#L21 to remove the LUT
- [x] Remove `meddraSocCode` from the `drug.drugWarnings` API endpoint
- [X] Remove the `MedDRA SOC Code` table from the UI

## Acceptance tests

How do we know the task is complete? 

1. The schema of the `drugWarnings` dataset does not have a field called `meddraSocCode``
2. The API endpoint `drug.drugWarnings.meddraSocCode` no longer exists
3. [CHEMBL8](https://platform.dev.opentargets.xyz/drug/CHEMBL8) does not show any reference to MedDRA in the drug warnings component

**Comment by mbdebian** [comment]
@jdhayhurst , @ireneisdoomed is going to be around for the next two weeks, would you mind checking with her whether this is issue is still relevant?

**Comment by ireneisdoomed** [comment]
@jdhayhurst Thank you for the changes in https://github.com/opentargets/platform-etl-backend/pull/323
It looks good to me, however it's easier to QC the data next time this is run to make sure we are not missing anything.
The API field to be removed is indeed `drugWarning.meddraSocCode`, not the pharmacovigilance one. Thanks again!

**Comment by ireneisdoomed** [comment]
These changes have implications in the FE that we have to action to close the issue.
Looking at the acceptance tests:
1. `drugWarnings` has been removed from the data ✅
2. `drug.drugWarnings.meddraSocCode` is no longer a field in the API ✅
    - **We need to update the example query in the API page https://platform.dev.opentargets.xyz/api**. It might not be related, but the `chemblId` env variable is incorrectly defined for the drug endpoint
 
![image](https://github.com/opentargets/issues/assets/45119610/38561f9c-13f2-4dcd-ba8c-c959131817b8)

3. We are missing the drug warnings widget for [ciprofloxacine](https://platform.dev.opentargets.xyz/drug/CHEMBL8) because the FE hasn't been updated yet ❌

Thank you!

cc @prashantuniyal02 @carcruz
