### ISSUE TITLE
Precompute LD sets for all possible variants

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3020]
As a **developer of the Genetics ETL pipeline** I want to **generate a dataset with the LD set for every variant included in the LD matrix** to streamline the LD annotation in every possible step downstream.

## Background

We use LD matrices from gnomad 2 to annotate the signals identified in GWAS with their variants in high LD.
Because of the complexity of the task and the size of the data, so far the approach has been to access the LD matrix and make queries only for our subset of variants of interest. Overall the process is like:
1. Generation of the LD indices: a look up table between a variantId (build 38) and its coordinate in the LD Matrix.
2. Accession of the LD Matrix and look up of the variants in high LD: by providing the indices obtained in Step 1.

Because of its complexity, so far we have aimed at minimising the number of variants of interest. However, accessing the LD information is likely to play a bigger role in our downstream pipelines, for example, when clumping summary statistics signals to find independent associations.

Since optimising the accession to the LD information seems capital, we want to change the scope by essentially precomputing a dump of the LD matrix, in a format that we can later easily integrate with other components of the pipeline.

## Tasks

- [x] Approach the task by looking at the compute time of dumping the whole LD matrix of non Finnish europeans.
    - We generated a dataset of all variant to variant combinations when the r2 was higher than 0.5 in 18 minutes (we didn't transpose the matrix in this case).

Create a new module in the project that:
- [x]  Transposes the block matrix to get a dataframe that contains r's for variantA with variantB, and for variantB with variantA. We'd need to deduplicate the diagonal of the matrix.
- [x] Resolves the variantIds for each entry of the matrix. By default, entries() returns `i` and `j`.
- [x] Dumps LD Matrices for all populations
- [x] Generates an unique and aggregated dataset that substitutes the current `LDIndex` and that is optimised for operability further down the pipelines.

**Comment by ireneisdoomed** [comment]
I have a working script that ticks all the boxes above.

## New data model
This is the schema that we have agreed on for the new LD index:
```
root
 |-- variantId: string (nullable = false)
 |-- ldSet: array (nullable = false)
 |    |-- element: struct (containsNull = false)
 |    |    |-- tagVariantId: string (nullable = false)
 |    |    |-- rValues: array (nullable = false)
 |    |    |    |-- element: struct (containsNull = false)
 |    |    |    |    |-- population: string (nullable = false)
 |    |    |    |    |-- r: double (nullable = false)
```

## Data

### Partial dataset (European LD matrix)
I have prepared a version of the dataset where only one ancestry matrix is processed (**europeans**). This is useful for inspection to see if we are happy with the new structure and to identify bugs.

Some stats:
- 14,192,022 unique variants
- Mean LD set size: 64
- 2,372,125 variants without any tag SNP

I've compared my LD set for `1_154434943_A_C` with the same one in [production](https://genetics.opentargets.org/variant/1_154434943_A_C) to make sure the variant mapping was correct and I think it makes sense. The examples I checked with very high r2 are in production, while other variants with a more modest relationship can be missing from production.
```
-------------------+------------------+                                       
|        tagVariantId|   POWER(r.r, 2.0)|
+--------------------+------------------+
|     1_154445353_C_T| 0.977017592243222|
|     1_154446273_C_T|0.8663914034274087|
|     1_154454494_A_C|0.8950914147371707|
|    1_154435509_C_CA|0.6213165467389992|
|     1_154447416_G_A|0.5152602632652837|
|     1_154452980_G_A|0.9049521521924578|
|     1_154447611_G_A|0.8715257882573817|
|     1_154441820_C_T|0.9766432525733204|
|     1_154443301_A_G|0.9352004846163459|
|   1_154447547_T_TAC|0.6240262336020064|
|1_154447555_C_CAT...|0.6582401513977938|
|    1_154437418_A_AT|0.8612230457987975|
|    1_154442789_CT_C|0.7513507856044945|
|     1_154444493_C_T|0.9800400749733147|
|     1_154437254_G_A| 0.981858170286397|
|     1_154446403_C_T|0.8633949865274938|
|    1_154437881_AT_A|0.7737998772902371|
|     1_154438943_A_C| 0.986084978947803|
|     1_154455807_A_G|0.8780691500250938|
|     1_154449054_T_C|0.6800625247976498|
+--------------------+------------------+
```

Link to the dataset: `gs://genetics_etl_python_playground/output/python_etl/parquet/XX.XX/ld_index_eur_aggregated`
Computation time: 43' ([job](https://console.cloud.google.com/dataproc/jobs/my_ld_index-6luhuzs4h6qsg/monitoring?region=europe-west1&project=open-targets-genetics-dev))

### Full dataset
The full dataset with the LD sets across all ancestries has been processed for ~5h.
The location will be: `gs://genetics_etl_python_playground/output/python_etl/parquet/XX.XX/ld_index`
Computation time: TBC ([job](https://console.cloud.google.com/dataproc/jobs/my_ld_index-pp6yewps2yrss/monitoring?region=europe-west1&project=open-targets-genetics-dev))

**Comment by ireneisdoomed** [comment]
Update: I've added `chromosome` as a field, to write the dataset partitioning on this column to perform more optimal joins when annotating variants.

**Comment by ireneisdoomed** [comment]
Success!! @d0choa suggested to throw more disk to the job and it ran in 5h ([job](https://console.cloud.google.com/dataproc/jobs/my_ld_index-tvs42edrdg2k6?region=europe-west1&project=open-targets-genetics-dev)) with a 5TB hard drive.

@mbdebian Could you still have a look at the changes I've made to make sure nothing is blatantly stinky? Changes are summarised [in the PR ](https://github.com/opentargets/genetics_etl_python/pull/110)and in the comment above.
