### ISSUE TITLE
Change in value structure in EFO file: efo_otar_slim.owl

### ISSUE THREAD

**Issue by ehsanb29** [opentargets/issues#3029]
As a developer I want to run [PIS](https://github.com/opentargets/platform-input-support) on the data in [latest version of the EFO](https://github.com/EBISPOT/efo/releases/tag/v3.56.0). 
But it seems that value structure for a field ("@type") in the [efo_otar_slim.owl](https://github.com/EBISPOT/efo/releases/download/v3.56.0/efo_otar_slim.owl) is changed.
The values in this field have been like this: `"Class"` or `"Axiom" `or `"Restriction"` untill EFO v3.52.0
From EFO v3.53.0 onwards, there is a literal (`"owl:"`) added to the "@type" fields and the values have changed to: `"owl:Class"`  or `"owl:Axiom"` or `"owl:Restriction"` 

## Tasks

- [ ] Update a relevant condition in [this JQ filter](https://github.com/opentargets/platform-input-support/blob/f0462f93b489dbed9aee375bbc05830e5b7c9886/config.yaml#L19).  
- [ ] Update the condition in EFO helper file [here](https://github.com/opentargets/platform-input-support/blob/f0462f93b489dbed9aee375bbc05830e5b7c9886/plugins/helpers/EFO.py#L392) 
- [ ] Check if anything else needs to be changed. 

## Acceptance tests

How do we know the task is complete? 

1. When the data team confirm the output.

**Comment by ireneisdoomed** [comment]
This is on BE's hands at the moment to make sure the code in the ETL is not affected by these changes.

**Comment by mbdebian** [comment]
@ehsanb29 is checking the ETL and API for this changes

**Comment by ehsanb29** [comment]
> @ehsanb29 is checking the ETL and API for this changes

As I checked the ETL and API, there won't be any side effect by this changes.

**Comment by mbdebian** [comment]
@ehsanb29 , Did any of these changes showed anything off in the QC process when navigating the platform?
