### ISSUE TITLE
Explore the use of Opensearch

### ISSUE THREAD

**Issue by remo87** [opentargets/issues#3031]
As a developer I want explore the use of opensearch because we want to avoid licensing issues and use modern features

## Background

Provide any necessary background information to provide context on the issue. 

## Tasks

- [ ] Update POS to generate data volumes using OpenSearch instead of Elasticsearch
- [ ] Review best configuration for server and indexes
- [x] Update Terraform to deploy Opensearch instead of Elasticsearch
- [x] Review API compatibility on the sksamuel library
- [x] Compare Elasticsearch and OpenSearch

**Comment by mbdebian** [comment]
We can stretch this one across the last two releases of the year and, if viable, the replacement could be scheduled to go live on the first 2024 release.
Thanks @remo87 !
