### ISSUE TITLE
New Molecular Interaction Data Model from IntAct

### ISSUE THREAD

**Issue by mbdebian** [opentargets/issues#3032]
As a backend developer, I want to process IntAct interactions dataset as part of the release process.

## Background
IntAct is one of our data providers for _molecular interactions_ data.

Our data collection pipeline (PIS), pulls their submitted data from
> https://ftp.ebi.ac.uk/pub/databases/intact/various/ot_graphdb/current/interactor_pair_interactions.json

They plan on updating the data model in this file with additional information (attributes) and, in order to give us time to adapt our pipelines, they have attached to their data submission the file *interactor_pair_interactions_new_format.json*, which contains the same information as *interactor_pair_interactions.json* but, using the new data model.

This is just for this release data submission, so we can have the old and new data models side by side and adapt our pipelines accordingly. Future data submissions will contain just the file we usually collect from them, but its content will be expressed in the new data model.

## Tasks

- [ ] Review and adapt, if needed, PIS
- [ ] Review and adapt, if needed, the ETL
- [ ] Confirm that no ripple effect reaches neither POS nor the API or frontend

## Acceptance tests
Being able to collect and ingest IntAct data through their updated data model.

**Comment by prashantuniyal02** [comment]
For this release it cannot cause any problem, because the file picked up by PIS follows the old schema. However the schema change is quite minimal:

**the schema of the new field:**

```json
{
  "full_name": "Breast cancer tissue",
  "short_name": "breast_cancer",
  "xrefs": ["UBERON:0000310"]
}
```
It's rarely populated (0.5%). At this point, I assume, we can just ignore it, I assume, if we are not explicitly ask for this field, it will be excluded from the output and would not be exposed. But someone from the backend team could confirm. Also, again, it is an issue from the next release.

_Originally posted by @DSuveges in https://github.com/opentargets/issues/issues/3038#issuecomment-1682059033_

**Comment by mbdebian** [comment]
@ehsanb29 , have you had a chance to look at this?

**Comment by prashantuniyal02** [comment]
Email received on 23 October 2023 at 11:06:51 BST

```
Hi All,

We have released data today, which is available at following path
https://ftp.ebi.ac.uk/pub/databases/intact/various/ot_graphdb/current

Thanks & Regards,
IntAct Developers
```

**Comment by remo87** [comment]
I checked the ETL, POS and API code and there's no specific reference to the field so no direct impact on the code execution.

**Comment by buniello** [comment]
I see from one of the comment that the new field is currently rarely populated (0.5%)- I suggest we postpone any scoping work on this to a calmer time

**Comment by mbdebian** [comment]
@jdhayhurst , I think we have used the new data model from IntAct in 23.12 release, would you mind checking whether we can close this issue?
Thanks!
