### ISSUE TITLE
Direction of effect assessment implementation at evidence level in BE

### ISSUE THREAD

**Issue by Juanmaria-rr** [opentargets/issues#3041]
## Background
The direction of effect refers to how genetic variation in a target is associated with a risk or protection for a trait/disease. As it is an assessment based on genetic information. 

The aim is to have the result of the direction of effect (doe) assessment at evidence level. Currently, the assessment is performed when the evidence has two key informations: 

1) Variation type. Type of variant (LoF, PTVs, GoF) or eQTL/pQTL expression data (increased expression = GoF / decreased expression = LoF)  for the next OT datasources.

2) Association with trait. Odds ratio / beta values OR risk / protective annotations.

We propose to create two columns in the evidence file, corresponding to each of the two key information, with the following names and possible values:

1)variantEffect column (values= LoF/LoF/Null) 
2)directionOnTrait column (values=Risk/Protective/Null) 

Shared repository to work on the code responsible for the doe assessment (https://github.com/Juanmaria-rr/directionOfEffect/blob/main/src/runDirectionOfEffect.py)

## Tasks

- [x] Translate PySpark code to Scala
- [ ] Implement into BE 
- [x] Having regular meetings to follow up the progress.

**Comment by Juanmaria-rr** [comment]
I need to check the @remo87 's results using Scala code to have a first pass of the data.

**Comment by Juanmaria-rr** [comment]
After some iterations we got 100% of agreement at evidence level.

**Comment by remo87** [comment]
There was an issue with the data. We were missing evidences in the run I did in December. Yesterday I found and fix the issue I'm currently generating the data images to deploy again.

The evidences we were missing were the ones we didn't process in DoE. Now those are joined back and should be visible once the new data images are deployed.

**Comment by remo87** [comment]
The new data images have been deployed to dev

**Comment by prashantuniyal02** [comment]
Hi @remo87, Juan and I checked the API response for the following datasources:
```
"ot_genetics_portal",
"gene_burden",
"eva",
"eva_somatic",
"gene2phenotype",
"orphanet",
"cancer_gene_census",
"intogen",
"impc",
"chembl"
```
The API response seems to be correct.

**Comment by buniello** [comment]
@Juanmaria-rr could you please add here the final list of 7 data sources/widgets we will need to add doE to?

**Comment by Juanmaria-rr** [comment]
The list of **8** data sources/widgets are the following: 
```
"ot_genetics_portal",
"gene_burden",
"eva",
"eva_somatic",
"gene2phenotype",
"orphanet",
"impc",
"chembl"
```
