### ISSUE TITLE
Migrating links from the old/current ClinicalTrials.gov website to the new version

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3048]
The [ClinicalTrials.gov](http://clinicaltrials.gov/) are deprecating the old links that we use and forwarding them to a classic view. It might be good to start migrating to the URLs

## Background

To reproduce:
1. Go to a [drug profile page](https://platform.opentargets.org/drug/CHEMBL112)
2. Scroll to the Clinical Precedence section.
3. Click on the `ClinicalTrials.gov` entry in the "Source" column
4. You will be redirected to the [classic ClinicalTrials.gov website](https://clinicaltrials.gov/ct2/show/NCT02967965) with a warning banner informing about the migration.
![image](https://github.com/opentargets/issues/assets/122870584/d2a0659f-9861-4b9b-97b0-e92984290474)

**[Old]** https://clinicaltrials.gov/ct2/show/NCT02967965
**[New]** https://www.clinicaltrials.gov/study/NCT02967965

## Tasks

- [ ] Ensure the links are redirecting to the new ClinicalTrials.gov website in all the relevant sections (see comment below)
- [ ] If we are using [identifiers.org](http://identifiers.org/) for this, the task is to update [identifiers.org](http://identifiers.org/) registry instead of our website: https://identifiers.org/resolve?query=clinicaltrials:NCT02967965
- [ ] Secondary task - Can we make better use of the [ClinincalTrials.gov](http://clinincaltrials.gov/) data from the new site/API?

**Comment by buniello** [comment]
ClinicalTrials links are visualised in the following sections (please add if I am missing any):

- [ ] ChEMBL **evidence** widgets - from the API `ChemblQuery`

- [ ] Known Drugs **target/disease** profile widget - from the API `KnownDrugsQuery`

- [ ] Clinical Precedence **drug** widget - from the API `KnownDrugsQuery`

- [ ] Indications **drug** widgets - hardcoded in FE

[Old] https://clinicaltrials.gov/ct2/show/NCT02967965
[New] https://www.clinicaltrials.gov/study/NCT02967965

It does not seem like we use the identifiers.org registry but will double check again.

**Comment by buniello** [comment]
Discussed in the FE meeting on 4/10/23: Luca will work on this ticket with me when he's back from his holidays

**Comment by LucaFumis** [comment]
Will discuss this in the devs meeting on Monday; it seems all queries would need updating at data/API level.
Will check the query for the Indications drug widget with backend team - should it not be possible to have that updated at API level, we can just fix the hardcoded link.
From the Indications query:
```
indications {
      rows {
        references {
          ids
          source
        }
      }
    }
```
returns something like:
```
"references": [
              {
                "ids": [
                  "NCT01037660"
                ],
                "source": "ClinicalTrials"
              }
            ]
```

**Comment by LucaFumis** [comment]
It seems that the indications `references` is intended in a different way than the `urls` field in the other queries, and probably for this reason was not returning a url for ClinicalTrials? 
I guess it might stay in this format, so for now I've simply updated the url for clinicaltrials in the platform config files.
It might also be no longer fully relevant as ClinicalTrials.gov are now redirecting correctly to the new URL without any warning message.

**Comment by LucaFumis** [comment]
PR ready for review for changes to the **Indications widget (**updated hardcoded url): if the info will then come from the API, then these changes will need to be updated. 
Front-end wise that is the only change, as for all other widgets the required changes are API only.

**Comment by prashantuniyal02** [comment]
Since now `clinicaltrials.gov` is now automatically redirecting the old links to the new page, it has solved this issue.
However this leads to the links being displayed in our platform being different that where you land up on the clinicaltrials.gov page which will be fixed after changes in the backend.
FYI @buniello
