### ISSUE TITLE
Expand the drug index definition to include all probes as reported by P&Ds

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3051]
As a **developer** I want **expand the definition of a drug to include all probes as reported by P&Ds** because **chemical probes are useful from a target's doability perspective**. 

## Background

Probes are chemicals that bind very selectively to a target. As opposed to drugs, they don't need to have a safety profile, because they're useful from a target's doability perspective. 

We annotate which probes bind to a target by processing the data available from Probes&Drugs.com (P&Ds).

Since probes are chemicals, they can also be referenced with a ChEMBL ID. Up until now, we were manually building the probe to ChEMBL cross references by using our drug index as a dependency to the probes dataset generation. This is something that is inherently wrong, because probes are generated before an ETL run.

From 23.09 on, probes to ChEMBL references are built with a table provided directly by P&Ds. This has led to the fact that this coverage has increased a lot, leaving most of the ChEMBL IDs outside of our definition of a drug (more [here](https://github.com/opentargets/issues/issues/3047#issuecomment-1697016236)).

To give the user a more comprehensive view of the information of a target, we want to add all ChEMBL IDs that describe a chemical probe to our molecules dataset. **This means that the `chemicalprobes.json.gz` dataset that the data team prepares from P&Ds will become a dependency of the drug step in the ETL.**

## Tasks

- [x] Add the probes dataset as a dependency to the [Drug step](https://github.com/opentargets/platform-etl-backend/blob/master/src/main/scala/io/opentargets/etl/backend/drug/Drug.scala#L79) in the ETL. The probes dataset is picked up by PIS and deposited in the bucket following the pattern: `gs://open-targets-pre-data-releases/XX.XX/input/target-inputs/chemicalprobes`
- [x] Join the raw molecule dataset with the probes dataset. From the probes, we only need the unique `drugId` values that are not null.
- [x] Update the [isDrugMolecule](https://github.com/opentargets/platform-etl-backend/blob/f7b6e164f027ae3372c07951cd81075905863bdc/src/main/scala/io/opentargets/etl/backend/drug/Drug.scala#L79) variable to accept drugs present in the probes dataset
- [x] QC data
- [ ] Update documentation
- [ ] Mention in comms

## Acceptance tests

- [x] Data QC: The new molecule dataset will have 4,057 new molecules, totalling to 17096
- [x] Data QC: CHEMBL4297778 is there. The name is LONCASTUXIMAB TESIRINE and has a maximum clinical phase of 4.
- [ ] FE QC: There is a drug page for CHEMBL4297778 with 8 indications.

**Comment by ireneisdoomed** [comment]
Some data analysis I've done on the incoming data:

```python
from pyspark.sql import SparkSession
import pyspark.sql.functions as f

spark = SparkSession.builder.getOrCreate()

# Data
probes = spark.read.json("gs://open-targets-pre-data-releases/23.09/input/target-inputs/chemicalprobes/chemicalprobes.json.gz")
raw_molecule = spark.read.json("gs://open-targets-pre-data-releases/23.09/input/chembl-inputs/chembl_33_molecule.jsonl").repartition(200)
ot_molecule = spark.read.parquet("gs://open-targets-pre-data-releases/23.09/output/etl/parquet/molecule")

# Basic stats
print(probes.filter(f.col("drugId").isNotNull()).select("drugId").distinct().count())  # 4_370
print(raw_molecule.select("molecule_chembl_id").distinct().count())  # 3_399_743
print(ot_molecule.select("id").distinct().count())  # 13_039

# Probes outside the drug index - 92%
print(probes.filter(f.col("drugId").isNotNull()).select("drugId").join(ot_molecule.selectExpr("id as drugId"), on="drugId", how="left_anti").distinct().count())  # 4_058

# Probes outside ChEMBL's raw data - 0%
print(probes.filter(f.col("drugId").isNotNull()).select("drugId").join(raw_molecule.selectExpr("molecule_chembl_id as drugId"), on="drugId", how="left_anti").distinct().count())  # 0

# Probes characteristics in ChEMBL's raw data - are we introducing any problematic data?
probes_in_raw_molecule = raw_molecule.join(probes.selectExpr("drugId as molecule_chembl_id").distinct(), on="molecule_chembl_id", how="inner")
probes_in_raw_molecule.describe().show()
"""
+-------+------------------+--------------------+------------------+------------------+-----------------+-------------+---------------+
|summary|molecule_chembl_id|   black_box_warning|      chebi_par_id|    first_approval|        max_phase|molecule_type|      pref_name|
+-------+------------------+--------------------+------------------+------------------+-----------------+-------------+---------------+
|  count|              4370|                4370|               156|                93|              278|         4370|            457|
|   mean|              null|0.006407322654462242|49009.179487179485|1999.6344086021506|2.487410071942446|         null|           null|
| stddev|              null| 0.07979803265999336|29682.919517848324|18.437193591403265|1.428444832640795|         null|           null|
|    min|      CHEMBL100231|                   0|              3077|              1950|             -1.0|      Protein|         (R)-9s|
|    max|       CHEMBL99203|                   1|            147675|              2022|              4.0|      Unknown|ZOLEDRONIC ACID|
+-------+------------------+--------------------+------------------+------------------+-----------------+-------------+---------------+
"""
```

- We are bringing **4370 new drugs**. 90% of them without an explicit name other than the ID
- 95% of them are small molecules.
- 94% of them are preclinical, we'll however bring 100 approved molecules.
