### ISSUE TITLE
platform-api base image reverted to use an outdated OS for now due to Travis issues

### ISSUE THREAD

**Issue by fedde-s** [opentargets/issues#3056]
As a **custom instance maintainer** I want **to use an up-to-date base image** because **the current one contains known security vulnerabilities that may or may not be accessible**.

## Background

After I updated the Dockerfile, it unfortunately caused a problem in the one part that is difficult for me, as an external contributor, to test locally: `deploy_quay.sh`. Hence it was [reverted](https://github.com/opentargets/platform-api/pull/148) to unblock the 23.09 release.

In the discussion there, I did come close to a fix that may be worth trying after the more urgent tasks are unblocked:

> [This](https://stackoverflow.com/questions/76491765/docker-buildx-failing-with-problem-executing-scripts-aptupdatepost-invoke#answer-76514507) Stack Overflow answer seems to have been able to reproduce the same error by using an old Docker release (20.10.6). Perhaps that's what was going wrong in the Travis context but not in my local tests: Travis reported using Docker CE release 20.10.7. Perhaps the proper fix is [inserting these instructions to tell Travis to update Docker](https://docs.travis-ci.com/user/docker/#installing-a-newer-docker-version)?

_Originally posted by @fedde-s in https://github.com/opentargets/platform-api/pull/148#issuecomment-1705447586_

## Tasks

- [ ] Try the instructions to tell Travis to use a recent Docker release, linked above
- [ ] Revert the revert or otherwise re-apply the  base image update
- [ ] Test whether it no longer breaks image pushing, either by releasing a tag or fixing the logic to test it on pull requests as I described [here](https://github.com/opentargets/platform-api/pull/148#issuecomment-1705348356), if that functionality is still desired

## Acceptance tests

How do we know the task is complete? 

1. When I look up a recent Quay tag on <https://quay.io/repository/opentargets/platform-api?tab=tags> and click the hexadecimal hash to view the image history, its build layers match the ones for `eclipse-temurin` instead of for the unmaintained `openjdk` images. For instance, including `ENV JAVA_HOME=/opt/java/openjdk` instead of `ENV JAVA_HOME=/usr/local/openjdk-11`
2.  When I look up a recent Quay tag on <https://quay.io/repository/opentargets/platform-api?tab=tags> and look at the **Security scan** column, it says something nicer than **55 Critical**.

**Comment by fedde-s** [comment]
I think this might actually have been resolved by the base image update in 25.03!

**Comment by fedde-s** [comment]
Yes:I just went over the acceptance tests, and this has been fixed. Thanks!
