### ISSUE TITLE
Harmonise data model for overlapping StudyLocus

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3058]
As a **user/developer** I want **to have the same data model for the StudyLocus overlaps independently of the method they have been produced** because:
- **a user would benefit from having a single representation**
- **+ a developer would benefit from having a single logic to produce that representation**

## Background

The way we have been referring to overlaps between associations in the Genetics Portal so far is by comparing studies and looking at common variants _in their respective credible sets_. We actually have a widget in the UI to display this information; at the same time, this dataset is useful in the colocalisation analysis.

Recent discussions around the integration of the pattern based colocalisation (PBC) have raised that we need a very similar dataset that essentially looks for common variants _in the respective locus_ instead, since this is computed before fine mapping.
This dataset of overlaps will be based on distance. The requirements of the PBC pipeline are:
- Clusters of associations can be identified when the leading variants are **within 50kb of each other.**
- To define the overlap, we look at variants that are common between pairs of StudyLocus. The **variant has to be within 250kb distance from the lead.**
- Statistics for each variant in the locus that need to be carried over are: p value, and beta

## Tasks
- [ ] Proposal for a common data model for these sets of overlaps that works for both methods
- [ ] New logic to find the overlaps based on a given distance
- [ ] Adapt the existing logic that finds overlapping peaks based on credible sets
- [ ] Adapt the colocalisation step to use the new data model

**Comment by ireneisdoomed** [comment]
The development of this feature is drafted in this [PR](https://github.com/opentargets/genetics_etl_python/pull/125). I first implemented a version where the dataset of overlaps was exploded so that each row represented the pairs of associations where we see an overlap + which is the overlapping variant. You can see the proposed data model [here](https://github.com/opentargets/genetics_etl_python/blob/8cf46d4e399982afe9d9563df875bc2f082b6e9c/src/otg/assets/schemas/study_locus_overlap.json).

Based on the discussions today with @xyg123 and @d0choa, where we looked at how the overlaps are used to calculate the thetas, we don't need to produce an exploded version of this dataset. The calculation of theta works by calculating aggregated statistics for all common variants in the left and right loci, so an aggregated version of the overlaps is actually more convenient, since each row represents a unique pair of studyLocus that somehow overlap.
This is the latest data model we have come up so far:
```
root
 |-- left_studyLocusId: long (nullable = true)
 |-- left_locus: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- variantId: string (nullable = true)
 |    |    |-- pValueMantissa: float (nullable = true)
 |    |    |-- pValueExponent: integer (nullable = true)
 |    |    |-- beta: double (nullable = true)
 |-- right_studyLocusId: long (nullable = true)
 |-- chromosome: string (nullable = true)
 |-- right_locus: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- variantId: string (nullable = true)
 |    |    |-- pValueMantissa: float (nullable = true)
 |    |    |-- pValueExponent: integer (nullable = true)
 |    |    |-- beta: double (nullable = true)
```
left_locus is just a filtered version of the locus of the left association, filtered to only contain only the common variants. The same goes for right_locus.

**This implementation introduces breaking changes with our former overlaps definition** (the one that looked at credible sets), because the former data model was exploded.
I need to go back to that code and adapt it given the new specification.

**Comment by d0choa** [comment]
Just so we don't forget, 2 more specs that could eventually be turned into tests:
- It would make our life easier if the 2 loci in the same overlap were in the same order.
- `coloc` requires the union of the 2 loci instead of the intersection. It is not a priority at the moment, but this will be necessary if we want to generalise the usage of the overlaps. The union could be used for pattern-based colocalisation, so it's the more general of the solutions.

**Comment by ireneisdoomed** [comment]
With the new approach where we work with aggregated data, and where all the metadata we need around the locus is carried over, there is a lot of logic around how the overlaps between credible sets were extracted that can be streamlined.

This logic lives in `StudyLocus.find_overlaps_in_credible_set` and mostly involves these steps:
1. We parse the StudyLocus dataframe to extract the credible sets where we want to search for overlaps
2. We identify the overlapping signals (`_overlapping_peaks`)
3. We bring metadata about the left and right locus to be processed later on (`_align_overlapping_tags`)

As I was saying, the third one with the newer data model is redundant. The idea is to align the logic for the 2 types of overlaps calculation, harmonising the whole process.

For the purpose of QCing in the future, I have run the current implementation on the GWASCatalog curated associations (`gs://genetics_etl_python_playground/output/python_etl/parquet/XX.XX/catalog_study_locus`). 
- I have 434,351 associations.
- I extract 2,121,633 pairs of unique overlapping signals
- All of them with an average of 1.1 overlapping variants (this is very low due to a bug in PICS, but it'll do the job), with the most extreme pair containing 322 common variants.

The dataset is here `gs://ot-team/irene/genetics_tmp/credset_overlaps_standard`, and with my proposed changes I expect to see the same metrics.

**Comment by ireneisdoomed** [comment]
## Proposed data model

### Context
In the StudyLocus dataset we annotate the region that that association is describing in the field `locus`. The locus "is born" after collecting the variant around the lead when summary stats are processed. We can start off with a definition like:
```
locus
--- variantId
--- beta
--- pvalue
```
As a StudyLocus dataset is processed downstream on the pipeline, `locus` is transformed.
For example, when we annotate each variant with its LD information, we'd have something like:
```
locus
--- variantId
--- beta
--- pvalue
--- r2Overall
```
In a similar way, after fine mapping the locus we will add additional information to it. Definition of the locus data model after fine mapping is not solidified yet, but after discussing it with @hlnicholls I think we can expect something like:
```
locus
--- variantId
--- beta
--- pvalue
--- r2Overall
--- credibleSetposteriorProbability
--- credibleModelposteriorProbability
```

### Proposal
So the overlaps structure should just mimic the structure we define for the locus. I think a sensible solution would be:
```
root
 |-- left_studyLocusId: long (nullable = true)
 |-- left_locus: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- variantId: string (nullable = true)
 |    |    |-- pValueMantissa: float (nullable = true)
 |    |    |-- pValueExponent: integer (nullable = true)
 |    |    |-- beta: double (nullable = true)
 |-- right_studyLocusId: long (nullable = true)
 |-- chromosome: string (nullable = true)
 |-- right_locus: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- variantId: string (nullable = true)
 |    |    |-- pValueMantissa: float (nullable = true)
 |    |    |-- pValueExponent: integer (nullable = true)
 |    |    |-- beta: double (nullable = true)
 |    |    |-- r2Overall: double (nullable = true)
 |    |    |-- credibleSetposteriorProbability: double (nullable = true)
 |    |    |-- credibleSetABF: double (nullable = true)
 |    |    |-- credibleSetNumber: integer (nullable = true)
 |    |    |-- credibleModelposteriorProbability: double (nullable = true)
```
Changes will pretty much depend on iterations we do on the data model after fine mapping with CARMA. I'll open a separate ticket about this.

**Comment by addramir** [comment]
To close?

**Comment by ireneisdoomed** [comment]
Yes, we concluded that the overlaps are used in their exploded format so the proposal is no longer relevant.
