### ISSUE TITLE
Define data model for fine mapping output

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3076]
As a **user/developer** I want **to have a set definition of the credible set** because **this data model has implications both up- and downstream our whole pipeline.**

## Background

(As extracted from https://github.com/opentargets/issues/issues/3058#issuecomment-1719463474)

In the StudyLocus dataset we annotate the region that that association is describing in the field `locus`. The locus "is born" after collecting the variant around the lead when summary stats are processed. We can start off with a definition like:
```
locus
--- variantId
--- beta
--- pvalue
```
As a StudyLocus dataset is processed downstream on the pipeline, `locus` is transformed.
For example, when we annotate each variant with its LD information, we'd have something like:
```
locus
--- variantId
--- beta
--- pvalue
--- r2Overall
```
In a similar way, after fine mapping the locus we will add additional information to it. Definition of the locus data model after fine mapping is not solidified yet, but after discussing it with @hlnicholls I think we can expect something like:
```
locus
--- variantId
--- beta
--- pvalue
--- r2Overall
--- credibleSetposteriorProbability
--- credibleModelposteriorProbability
```

## First proposal
To store the fine mapping results in our locus struct:
```
|-- locus: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- variantId: string (nullable = true)
 |    |    |-- is95CredibleSet: boolean (nullable = true)
 |    |    |-- is99CredibleSet: boolean (nullable = true)
 |    |    |-- pValueMantissa: float (nullable = true)
 |    |    |-- pValueExponent: integer (nullable = true)
 |    |    |-- beta: double (nullable = true)
 |    |    |-- r2Overall: double (nullable = true)
 |    |    |-- picsPosteriorProbability: double (nullable = true)
 |    |    |-- carmaposteriorProbability: double (nullable = true)
 |    |    |-- carmaABF: double (nullable = true)
 |    |    |-- carmaCredibleSetNumber: integer (nullable = true)
 |    |    |-- carmaCredibleModelposteriorProbability: double (nullable = true)
```

## Assumptions

- Unlike COJO, CARMA can output several credible sets. This is a result of CARMA looking for multiple sets of **independent** causal variants.
- The same variant can only belong to one credible set.
- We can only fine map those variants for which we have LD information.
- On top of the credible set, a variant can also belong to the credible model. This is the set of variants that **in combination** together explain the association best.

## Tasks

- [x] Proposal for a data model that is based on the fine mapping results outputted by CARMA, but also compatible with other fine mapping methods: PICS and SUSIE
- [x] Adapt current components of the pipeline that are affected by this definition
- [x] Decide what should exactly be the end product. What SNPs do we expect to see in locus? Only those in any of the credible sets?

**Comment by xyg123** [comment]
New StudyLocus schema has been incorporated to accomodate SuSIE + PICS.
