### ISSUE TITLE
On-demand skipping of ETL step computation on pre-existing results

### ISSUE THREAD

**Issue by mbdebian** [opentargets/issues#3090]
As a developer, when running our Platform ETL process, I would like for the pipeline to have an option where computation for pre-existing results is skipped.

## Background
_Platform ETL_ process is a Scala pipeline that uses _Spark_ for data processing.

When working on Open Targets Platform in the context of a release, or internal development, the pipeline is run in multiple iterations through the process, either completely or partially (specific steps).

The ETL configuration offers a mechanism to either _overwrite_ or _ignore_ pre-existing data, but this mechanism is wired at the Spark writer level, which means the computation always happens, and it’s only the stage where results are persisted, i.e. data output to some storage, the one that is skipped.

## Desired functionality
We need a higher level of abstraction flag to indicate that we want to skip computation for those steps that have pre-existing data.

This could be implemented as a _flag_ integrated in the concept of _Concept Manager_ that we can later on extend with additional features related to the running ETL session.

## Tasks

- [ ] Implement the concept of _ETL Session Context Manager_ which first option is going to be handling a flag where computation is required to re-run, e.g. *is_step_skip_preexisting*, **default** value is _false_.
- [ ] For every step, implement the logic needed for the step to evaluate whether pre-existing result data is present or not. This could be, at minimum, a combination of data present and not empty at the destination location, that validates the _post-flight contract_ and some additional checks that could increase the accuracy of the decision.
- [ ] When *is_step_skip_preexisting* is _false_, it means that the step needs to re-compute its processing, clearing up whatever is at the destination location to make sure no incoherent mixed results from several runs are mixed.
- [ ] When *is_step_skip_preexisting* is _true_, the step will evaluate whether or not pre-existing results are present, and skip the whole computation accordingly.

## Acceptance tests
- [ ] When *is_step_skip_preexisting* and pre-existing valid data is present, computation should be skipped
- [ ] In any other case, the step computation should be carried on.

**Comment by mbdebian** [comment]
@remo87 , We'll put this one on hold until we have your performance and cost results from autoscaling the Dataproc cluster
Thanks!
