### ISSUE TITLE
Conditional build for ETL Platform

### ISSUE THREAD

**Issue by mbdebian** [opentargets/issues#3091]
As a developer who works with Open Targets Platform ETL, I would like to have an improved assembly process for the _ETL jar_ file for multiple environments, e.g. _Dataproc_ and _local_.

## Background
Open Targets Platform ETL pipeline is written in Scala, and the assembly definition in _sbt_ produces a _jar_ file that we use in _Dataproc_.

Being useful for our internal processes and for the community (we’ve already had some requests about it), we would like the _build process_ to produce _jar_ files for multiple targeted environments on-demand, e.g. _Dataproc_ and _local_.

This could be achieved by passing flags through environment variables
```shell
sbt -DETL_FLAG_DATAPROC=true
```

And conditional dependency blocks
```scala

lazy val sparkDeps = if sys.env.get("ETL_FLAG_DATAPROC").getOrElse(true) {
   Seq(
    "com.github.fommil.netlib" % "all" % "1.1.2" pomOnly (),
    "com.databricks" %% "spark-xml" % "0.11.0",
    "org.apache.spark" %% "spark-core" % sparkVersion % "provided",
    "org.apache.spark" %% "spark-sql" % sparkVersion % "provided",
    "org.apache.spark" %% "spark-graphx" % sparkVersion % "provided",
    "org.apache.spark" %% "spark-mllib" % sparkVersion % "provided"
  )
} else {
   Seq(
    "com.github.fommil.netlib" % "all" % "1.1.2" pomOnly (),
    "com.databricks" %% "spark-xml" % "0.11.0",
    "org.apache.spark" %% "spark-core" % sparkVersion,
    "org.apache.spark" %% "spark-sql" % sparkVersion,
    "org.apache.spark" %% "spark-graphx" % sparkVersion,
    "org.apache.spark" %% "spark-mllib" % sparkVersion
  )
}
```

As an additional step, a _Makefile_ style wrapper could be provided for running these assemblies as a helper mechanism.

_Dataproc_ should be the target assembly environment by default.

## Tasks

- [x] Identify and refactor all the blocks that contain _Dataproc **provided**_ dependencies to support conditional build for, at least, _Dataproc_ and _local_ targets.
- [x] Implement an assembly wrapper to abstraction from the underlying assembly process to offer a uniform interface to the developer and future CI/CD pipelines.

## Acceptance tests
- [x] Assembly the pipeline for running on _Dataproc_ and verify it works
- [x] Assembly the pipeline for running locally and verify it works
