### ISSUE TITLE
Creating a Frontend UI for the Pharmacogenomics widget using the PharmGKB data

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3113]
We want to create a UI for the Pharmacogenomics widget where we can integrate PharmGKB data into the Platform.
This ticket is for the development of the UI which will be done by the FE team

## Dependencies

- [x] The JSON schema details compiled by the data team can be found here: #3110 
- [x] Mapping ChEBI identifiers to ChEMBL #3116 
- [x] The product and design related discussion can be found here: #3098 
- [x] Process PharmGKB data #3128 
- [x] Implement the required backend changes #3127 

## Tasks

- [x] To create a frontend for the Pharmacogenomics widget (diagram in the comments below)

## Acceptance tests

1. Netlify link and tested in the development deployment

**Comment by DSuveges** [comment]
I think there are a few bits that needs to be clarified (make the epic more granular): 
- Any implications on PIS
- Any implications on POS

**Comment by buniello** [comment]
Draft of Pharmacogenetics widgets below (discussed with Irene and reviewed by Ellie):
Built on this [Json Schema](https://github.com/opentargets/json_schema/blob/7c70a75db598b3770adbf14637df8f4767492e80/schemas/pharmacogenomics.json)

1) Widget on **target** ( "Targetfromsourceid”) profile page 
Will be placed between the ”Safety” and "Chemical probes” widgets
Datatypeid: "clinical_annotation”

<img width="1349" alt="Screenshot 2023-10-19 at 15 56 28" src="https://github.com/opentargets/issues/assets/30833755/4dffcab5-a183-4205-921a-5d5ca8829be6">


2) Widget on **drug** ("Drugid”) page  
Will be placed between the ”Drug warnings” and the “Pharmacovigilance” widgets
Datatypeid: "clinical_annotation”

<img width="1404" alt="Screenshot 2023-10-19 at 16 03 31" src="https://github.com/opentargets/issues/assets/30833755/caa139b1-2ca0-4c47-8225-23783de4ef83">


Please note comment from Ellie: we could choose to display just `1A` and `2A` values for the `evidenceLevel` field. This will probably enrich the data with drugs that have a Chebi/Chembl mapping as per [#3116](https://github.com/opentargets/issues/issues/3116)
Tagging @ireneisdoomed to this as well.

**Comment by carcruz** [comment]
Thanks @jdhayhurst everything looks great!

**Comment by LucaFumis** [comment]
Thanks @jdhayhurst. My understanding from looking at the schema you posted earlier in the comments is that some of those fields would expand to a full object? 
Looking at the mockups for the widgets, it seems some columns require for example tooltips.

Example for widget on **Target** page:
**GenotypeId**: needs full object for id (`genotypeId.title`?) and `description` for tooltip
**Variant consequence**: needs variant info for tooltip, not sure which field
**Drugs**: needs drug `name` and `id` for the link
**Adverse outcome**: `phenotypeText.title` + `phenotypeFromSourceId` for the link; tooltip: `genotypeAnnotationText.title`
**Adverse Outcome Category**: possibly `pgxCategory.title` ?
**Confidence**: is that `evidenceLevel.examples` ?

**Comment by ireneisdoomed** [comment]
Thank you @LucaFumis and @jdhayhurst for looking into it!

Some comments on top of @buniello 's specifications:
**Target and drug widgets**
- `variantFunctionalConsequence` is nullable. This is a SO term that needs to be resolved.
- `phenotypeText` is still not filtered to pick out actual adverse outcomes from drug responses. @LucaFumis, can you rename "Adverse Outcome" to "Drug Response" and "Adverse Outcome Category" to "Drug Response Category"? These are more general terms. 

**Target widget**
- Drug column: 
    - The text should be `drugFromSource`
    - Hyperlink to `drugId`. Not all drugs will have a drugId.
    - @jdhayhurst we are not using `drugFromSourceId` anywhere. So strictly speaking you could omit this field from the API if you wanted.

**Drug widget**
- Gene column:
    - The text should be the name of the resolved Ensembl ID in  `targetFromSourceId`
    - Hyperlink to `targetFromSourceId`
    - @LucaFumis, tooltip text is now built based on `isDirectTarget`
        - when `True`: "The variant is in the drug's primary target gene.." 
        - when `False`: "The variant is outside the drug's primary target gene." 

The rest of the fields are as pointed out in the widget prototype.
Please chip in @opentargets/data-team @d0choa if you have any comments

**Comment by LucaFumis** [comment]
Thank you @ireneisdoomed and @jdhayhurst for the feedback and input. I probably won't be working on it, but let me know in case anything needed...

**Comment by carcruz** [comment]
@chinmehta is working on the UI now. By now, we will be using sample data, and as soon as the data is in dev, we change it.

**Comment by chinmehta** [comment]
@prashantuniyal02 @jdhayhurst 
Missing fields from mockup/api

## Target and drug

- [ ]  genotypeId → tooltip see here for more details, "here" link is missing
- [ ]  source→ pharmgkb is missing
- [ ]  literature→ link to pmid, complete link details and multiple literature id shown details
         if more than one id-> open in a drawer / show in same column

**Comment by prashantuniyal02** [comment]
For point 3, can we adopt the same behaviour as is present in the `GEL PanelApp`, `UniProt literature` or `UniProt curated variants` widget which have a Literature column?

**Comment by buniello** [comment]
@chinmehta that is a good idea!

**Comment by buniello** [comment]
Already discussed and benchmarked with @chinmehta - (please let me know if anything is not clear)
We would like to harmonise the pharmacogenomics widget to the Clinvar one, by adding:

- [ ] Chip/link to[ ProtVar](https://www.ebi.ac.uk/ProtVar/query?chromosome=16&genomic_position=50712108&reference_allele=G&alternative_allele=T) for missense variants 
- [ ] [Hyperlinks to Ensembl](http://www.ensembl.org/Homo_sapiens/Variation/Explore?r=16:50711608-50712608;v=rs746055479;vdb=variation;vf=242937840) for rsids 
- [ ] VEP/ProtVar chips should look exactly same as in the Clinvar widget

![Screenshot 2023-11-09 at 10 23 11](https://github.com/opentargets/issues/assets/30833755/322e8346-9597-4441-9de2-3fca02b92a0c)

**Comment by buniello** [comment]
@chinmehta, as already discussed on slack, please see points below and let me know if everything is clear

- [ ] The current preview position of PGx widget in both target and drug pages are good.

- [ ] There is a typo in the widget header in drug page e.g.: https://deploy-preview-283--ot-platform.netlify.app/drug/CHEMBL2010601.

Header should spell: ` Genetic variants that are associated with the response to drugId. Source: [PharmGKB]`(https://www.pharmgkb.org/)`.
the `drugId` field should expose the drug name.

**Comment by buniello** [comment]
Latest version of drug and target profile PGx widgets are in the testing phase (external and internal test included).

**Comment by ireneisdoomed** [comment]
@chinmehta Some comments on the widget on drug and target pages:
- The box for the Level 2 evidence is white, so it looks like there is no data.
- The tooltip that has a granular description of the genotype is "floating" when the drug response phenotype is null. @buniello, not sure what is the best way to show this.

![image](https://github.com/opentargets/issues/assets/45119610/eeba37c8-01ec-47f5-a744-228c43c53d6c)

**Comment by buniello** [comment]
Good catch @ireneisdoomed! will discuss these with @chinmehta on wednesday

**Comment by prashantuniyal02** [comment]
A bug in the widget:

- [ ] The widget crashes when the search query is not found in the table (similar to #3084) - This will keep happening till we fix the root cause for this. @chinmehta 

--------------------------------------

2 points raised by David:

1. Should the default sorting be done in the confidence level (1A > 1B > 2A > 2B)?
2. Are the color pallets for 1B correct? (1A and 1B are green and 2A and 2B are blue in PharmGKB)

Case in point: `/target/ENSG00000167397`
<img width="1386" alt="image" src="https://github.com/opentargets/issues/assets/122870584/3794c07d-b1a3-4ee9-953b-e79c2510f498">

FYI @buniello
