### ISSUE TITLE
Process PharmGKB data based on latest discussions

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3128]
As the data team, we want to process the Pharmacogenomics data provided by EVA because it is in an iterative state.

## Background

EVA has been working and processing pharmacogenomics data from PharmGKB. We've had many discussions as to how we should account for more granular scenarios like:
- records where variant information is not present,
- records where the reported variant is multiallelic,
- ...

After reviewal of the data and widget specifications (https://github.com/opentargets/issues/issues/3113), we want to process the data provided by EVA so that **it is digested by the ETL in the expected shape and format**.

## Tasks

Based on conversations with @buniello, Ellie, EVA, and the data team, and as a one off solution, for the 23.12 release we want to :
- [x] Filter the dataset to only include records of high confidence (level "1A", "1B", "2A", "2B")
- [x] Flagging if the reported target is or isn't the drug target.
- [x] Rename `drugId` to `drugFromSourceId`. 
- [x] Include in `drugId` the result of mapping ChEBIs to a ChEMBL ID.

**Comment by ireneisdoomed** [comment]
New PharmGKB data has been added to the bucket:
`gs://otar012-eva/pharmacogenomics/cttv012-2023-10-23_pgkb.json.gz`

This is the code used to produce it https://gist.github.com/ireneisdoomed/acb02331fc4866eece41aaea2fd9f7d3
This logic is expected to be integrated in the ETL for 24.02 @prashantuniyal02

**Comment by ireneisdoomed** [comment]
Ellie reported a bug in the flag we add to the data saying whether target is indirect or not.
Looking at [ivacaftor/CFTR](https://platform.dev.opentargets.xyz/drug/CHEMBL2010601), the flag was incorrectly saying that CFTR was not the drug target.

![image](https://github.com/opentargets/issues/assets/45119610/8a714768-f161-4a47-961c-b3ba4eb4cbfe)

There was a bug [in my logic](https://gist.github.com/ireneisdoomed/acb02331fc4866eece41aaea2fd9f7d3#file-transform_pharmgkb-py-L31) (now fixed), where to build a look up table between each drug and their targets, I was filtering out those drugs with a single target as MoA. 
(`f.size("linkedTargets.rows") = 1` instead of `f.size("linkedTargets.rows") >= 1`)

> **This is now fixed and available in the new file: `gs://otar012-eva/pharmacogenomics/cttv012-2023-11-22_pgkb.json.gz`** 

## QC
Implications are important, however not massive in quantity. _Most of the variants curated by PharmGKB refer to a gene different than the drug target._
```
# Distribution before the bug
+--------------+-----+                                                          
|isDirectTarget|count|
+--------------+-----+
|         false| 1690|
|          true|    2|
+--------------+-----+

# Distribution after the bug
+--------------+-----+                                                          
|isDirectTarget|count|
+--------------+-----+
|         false| 1587|
|          true|  105|
+--------------+-----+
```

I've checked other examples, and they look alright:
- Variants in CYP interacting with nepiravine's drug response (not drug target) https://platform.dev.opentargets.xyz/drug/CHEMBL57
- Variants in RYR1 interacting with sevoflurane's drug response (not drug target) https://platform.dev.opentargets.xyz/drug/CHEMBL1200694
- Variants in ACE interacting with captopril's drug response (drug target)
https://platform.dev.opentargets.xyz/drug/CHEMBL1560

(The UI for the last example is incorrect as of today, but it'll show the target is direct once the data is updated.)

**Comment by DSuveges** [comment]
@ireneisdoomed , is the logic of the gist you shared, already in the evidence parsers? Or in other OT repos? Ideally we would incorporate it in the evidence parser pipeline.

**Comment by ireneisdoomed** [comment]
This is done. @prashantuniyal02, we have to remember to come back to this for the integration of the logic into the ETL.
