### ISSUE TITLE
"Productionizing" LD matrix extraction based on StudyLocus objects

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3131]
More sohpisticated fine-mapping algorithms require the square LD matrix of the locus for the calculations. This makes everything a huge pain, however we don't necessarily need to do the full process by iteration. As a first step for a more sustainable parallelizable solution, we need to came up with a method to extract the square matrix for a study-locus object and represent it as a spark dataset. The expectation is that these finemapping methods will never need to deal with studies of mixed ancestries.

**Steps**

- [x] Work out some data model that downstream stages can deal with.
- [x] Prototype and benchmark on some finngen studyLocus.

**Comment by DSuveges** [comment]
**After an extensive discussion we came to the following conclusion:**

- Make source specific implementation to interact with LD matrices.
- Make an intermediate layer between the application and the soruce specific code that knows which ancestry label should be picked up from which source.
- Make the source datasets default for the source specific classes so the intermediate layer doesn't have to know about where the data is read from.

**Progress**

- [x]  So far we defaulting only GnomAD [PR#233](https://github.com/opentargets/genetics_etl_python/pull/233).
- [x] GnomAD specific class has now method to extract an arbitrary slice of the ld matrix. [PR#](https://github.com/opentargets/genetics_etl_python/pull/236)

**What is missing**

- [ ] GnomAD specific method to return the melted square LD matrix with variant identifiers.
- [ ] This dataset could have its own data type given it would be extracted from different sources.
- [ ]  Having the intermediate layer that can call the previously mentioned method (source specific way).
