### ISSUE TITLE
Handing over disease/target evidence generation from Uniprot

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3181]
As the Uniprot team cannot support/run their evidence generation pipeline, we take over from them. 

- The code is here: [open-targets-core-db](https://github.com/ebi-uniprot/open-targets-core-db)

**Tasks**:

- [x] Run evidence generation
- [x] Uniprot team handing over ownership over the repo.
- [ ] Based on analytics on the evidence dataset make a decision on the future of the pipeline (options: keep java as it is, re-implement in Python, drop the entire dataset if not bringing enough value)

**Comment by DSuveges** [comment]
## Running evidence genration

Had to set the following things:

- One of the Java requirement's source was missing.
- maven needed to be installed
- The shell scripts needed to be updated so urls are pointing to ols4 APIs.
- Python has to point to Python3

Once all updates were in place, the evidence generation took `1h 57m 50s`, the resulting dataset contains 38,485 evidence string, which is a modest (109) increse compared to the most recent data update (`28-04-2023`) Once we own the repo, we can commit these updates to make the run smoother.

**Comment by DSuveges** [comment]
## Owning the code-base

The original codebase is forked to opentargets organization (`https://github.com/opentargets/uniprot-evidence-parser`). With some changes including:

- POM file contains dependency repository so now compiles.
- OLS API URLs are updated in the bash scripts.
- License (Apache v2.0) added to the repo.

**Comment by DSuveges** [comment]
- The handover has happened.
- New evidence set uploaded to: `gs://otar011-uniprot/cttv011-02-01-2024.json.gz`
- Evidence set validated.
- Number of evidence: 38,812 from 38,376. Modest increase with 436 evidence.
