### ISSUE TITLE
Updating DepMap data with the most recent release

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3190]
Currently Open Targets Platform contains data from the 2023Q2 depmap release. For the upcoming platform release there's a newer version released at the end of last year: 2023Q4. 

**Tasks**:

- [x] Identify relevant files in the download section of the [depmap website](https://depmap.org/portal/download/all/)
- [x] Download files and move to `gs://otar000-evidence_input/Essentiality/DepMap`
- [x] Test-run parser to make sure by the time of the production run there's no problem.
- [x] Validate resutil file against the essentiality schema.

**Comment by DSuveges** [comment]
Upadted dep-map files are here: `gs://otar000-evidence_input/Essentiality/DepMap/2023Q4`
The newly created evidence is here: `gs://otar000-evidence_input/Essentiality/json/essentiality-2024-01-26.json.gz`

The resulting dataset successfully validates against the schema.

**Comment by DSuveges** [comment]
It's done.
