### ISSUE TITLE
Automate running platform input support 

### ISSUE THREAD

**Issue by jdhayhurst** [opentargets/issues#3195]
As a developer I want to be able to automate runs of PIS because currently every run requires setting up all the infrastructure, doing the configuration and running manually, which takes time and is liable to introduce errors.

### Current process
1. Create a GCP VM with sufficient storage
2. Install dependencies
3. Setup user and dirs
4. Fetch GCP credentials
5. Run the specified PIS container with specified params and config
6. Check logs and tear down infrastructure

### Proposal
Utilise CLI `make` interface and Terraform to automate the above steps.

#### Terminology
- *profile* is a config where the following can be configured:
  - ensembl, chembl, efo versions etc. (small templatizable changes to PIS config.yaml)
  - PIS docker image/tag
  - GCS destination
- *session id* automatically generated id for identifying a specific PIS run

#### Operations/Makefile targets
- "credentials" -> copy credentials key from GCS to local. 
- "new profile" -> create a new profile from a template and set that profile.
- "set profile" -> set a particular profile as the _active profile_
- "instantiate config" -> create an instance of PIS _config.yaml_ file from a template using information in the active profile
- "launch PIS" (args: local/remote, PIS args)  -> create "session id" -> create session id subfolder under "sessions" -> write the PIS config (from "instantiate config") and the running context (a file?)
  - if *local* ->
    - prepare dirs
    - prepare log
    - docker run $args
    - upload logs, config, context to our GCS operations bucket
  - if *remote* ->
    - terraform init
    - new tf workspace with "session id"
    - provision resources
    - vm + storage 
    - startup script + dependencies, ops user env, creds, pis config, running context (a file?)
    - set ready flag
    - run PIS
    - upload the logs, config, context to our GCS operations bucket
    - shutdown VM

## Tasks

- [x] write the Makefile targets
- [x] write helper scripts
- [x] write the terraform infrastructure definition, provisioners and pipeline runner
- [x] write the pipeline runner for the local option

## Acceptance tests

How do we know the task is complete? 

1. I can run PIS locally using a simple CLI
2. I can run PIS remotely using a simple CLI
