### ISSUE TITLE
Scope more granular clinical significance for somatic variants in ClinVar

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3203]
As **the data team** we want **to investigate the new annotation about the clinical impact somatic variants in ClinVar** because **this information is key to interpret ClinVar t/d associations**.

## Background

@apriltuesday has summarised new changes in the ClinVar data download, that affect both the structure of the XML and its content. ClinVar will support the existing format until **March 2024**.

We want to scope how we want to accommodate the more granular somatic clinical impact terms:
```
Somatic clinical impact terms: AMP/ASCO/CAP Tiers (PMID 27993330)
- Tier I - Strong
- Tier II - Potential
- Tier III - Unknown
- Tier IV - Benign/Likely benign

Assertion types for clinical impact:

- For therapeutic:
    - sensitivity/response
    - resistance
    - reduced sensitivity

- For diagnostic:
    - supports diagnosis
    - excludes diagnosis

- For prognostic:
    - better outcome
    - poor outcome

Oncogenicity terms: ClinGen/CGC/VICC recommendation (PMID 36063163)
- Oncogenic
- Likely oncogenic
- Uncertain significance
- Likely benign
- Benign
```
(from https://github.com/EBIvariation/CMAT/issues/396).

This is a mock [from ClinVar](https://github.com/ncbi/clinvar/blob/master/sample_web_snapshots/vcv_08.png) of how significance could be reported after the changes, **with multiple possible assertions per variant/disease:**
<img width="928" alt="image" src="https://github.com/opentargets/issues/assets/45119610/488a0273-a78f-46ae-a20f-72b290b43084">

## Tasks
The clinical impact is how we score evidence from ClinVar. For the next meeting with EVA we need to determine
- [ ] new structure to report clinicalSignificances - should we nest all 3 assertions? 
- [ ] revisit scoring system - should we consider all assertion types?
- [ ] evaluate how we can use the role of the variant in cancer

It'd be good to gather ideas for the next meeting on **February 26**

**Comment by d0choa** [comment]
@ireneisdoomed, it appears there is little traction here. Unless you've seen this coming in the last 3-6 months, I advise closing the ticket and reopening it if/when appropriate.

I'll leave it to you.
