### ISSUE TITLE
Handle drug combinations in pharmacogenetics

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3205]
As the **data team**, I want **to handle pharmacogenetic evidence involving drug combinations where currently no drugId is mapped** because **this will ensure a more accurate representation of all pharmacogenetic evidence.**

## Background

Our current pharmacogenetics data model is structured to handle evidence involving a single variant/drug interaction.
We have encountered a limitation where evidence involving drug combinations is not mapped to any drug IDs. [CFTR w/ ivacaftor/lumacaftor is an example](https://platform.opentargets.org/target/ENSG00000001626).
<img width="1117" alt="image" src="https://github.com/opentargets/issues/assets/45119610/57be039d-4ec0-45b2-897f-939088fb89ff">

Important to note that this issue is really limited, I've only found 6 offending cases, all of them related with CFTR variation.
```
+--------------------------+----------------------+------+
|genotypeId                |drugFromSource        |drugId|
+--------------------------+----------------------+------+
|7_117559591_TCTT_TCTT,TCTT|ivacaftor / lumacaftor|null  |
|7_117559591_TCTT_T,T      |ivacaftor / tezacaftor|null  |
|7_117559591_TCTT_T,TCTT   |ivacaftor / tezacaftor|null  |
|7_117559591_TCTT_T,TCTT   |ivacaftor / lumacaftor|null  |
|7_117559591_TCTT_T,T      |ivacaftor / lumacaftor|null  |
|7_117559591_TCTT_TCTT,TCTT|ivacaftor / tezacaftor|null  |
+--------------------------+----------------------+------+
```

### Proposed Solutions

Two potential solutions are considered:

1. Expanding `drugFromSource` and `drugId` fields to allow lists. This would be more future-proof, accommodating drug combinations but requires significant alterations to the data model.
2. Exploding evidenceinto separate records for each drug. This approach kind of duplicates the data, but it maintains its structure.

Given the rarity of the drug combinations, I think that exploding is the most practical solution. The text that accompanies the genotype clearly specifies that the response is observed for the combination, so this field should be taken into consideration as context.

## Tasks
This is not meant to be done for 24.03. 
- [ ] If we all agree on this solution, we can talk to EVA in our next meeting for them to explode the evidence for 24.06.

## Acceptance tests

1. When I go to the [CFTR](https://platform.opentargets.org/target/ENSG00000001626) PGx widget, all evidence have a mapped drugId.

**Comment by DSuveges** [comment]
Even if the evidence is exploded to multiple `drugId`-s, I think it is possible to keep the `drugFromSource` as it is, so indicating the evidence is a combination in nature.

**Comment by ireneisdoomed** [comment]
We actually use the string `drugFromSource` in the drug mapping step to assign a `drugId`, I think it is more practical to explode.

**Comment by DSuveges** [comment]
Yes, we should explode, however it would be quite informative to know that these annotations are drug combination, there should be some provenance for that.

**Comment by ireneisdoomed** [comment]
@mbdebian After looking at the outputs after the changes in the drug mapping part of the ETL,  I think **they need a revision**. 

I observed **missing rows** between the PGx input (31,618) and the ETL output (24,573). This discrepancy is due to the way drug information is handled [here](https://github.com/opentargets/platform-etl-backend/blob/87568deca9cc3037f5e9f104628889c807e239dc/src/main/scala/io/opentargets/etl/backend/pharmacogenomics/Pharmacogenomics.scala#L42):
- Exploding Drug Arrays: The ETL process explodes arrays of drugs associated with each evidence record, creating separate rows for each drug. This explosion should be very small, given that the majority of evidence inform about a single drug.
- Grouping and Aggregation: The data is then grouped based on all columns except the drug information, and the drug values are aggregated back into a list.

This approach merges evidence that should be kept separate. Let me explain more graphically:
| evidenceId | response | drugs |
|------------|----------|-------|
| 1          | trait_a  | a     |
| 2          | trait_a  | b     |
| 3          | trait_a  | c, d  |

- 1, 2, 3 inform about the same effect given the same variant, the only thing that changes is the exposure (the drug) after which the response is observed
- 1, 2 inform about a response that is observed when you take drug a OR drug b
- 3 informa about the response that is observed when you take drug c AND drug d in combination

The current transformation loses this distinction, resulting in a single evidence record that lists all drugs associated with a given response, independently of whether they are individual or combinatorial:
| evidenceId | response | drugs      |
|------------|----------|------------|
| 1          | trait_a  | a, b, c, d |

For this reason, I'd suggest revising this step and keeping the drug array structure and use another strategy like `transform` to add the drug ID.
For QC, I suggest you check the sizes of the `drugs` array, that's how I identified the issue:
```
# Post ETL 
+-----------+-----+
|size(drugs)|count|
+-----------+-----+
|          1|20600|
|          6|   79|
|          3|  849|
|          4|  268|
|          8|    3|
|          5|  126|
|          2| 2453|
|          7|  165|
|         10|   27|
|         13|    3|
+-----------+-----+


# Pre ETL
+-----------+-----+
|size(drugs)|count|
+-----------+-----+
|          1|31516|
|          2|  100|
|          3|    2|
+-----------+-----+
```

**Comment by mbdebian** [comment]
I have changed the code to use an _operational row ID_, and after running the _pharmacogenomics_ step, I can confirm that the drug count stays the same:

Output
```spark
scala> outPharma.withColumn("drugsSize", size(col("drugs"))).groupBy("drugsSize").agg(count("*").as("count")).orderBy(col("count").desc).show
+---------+-----+
|drugsSize|count|
+---------+-----+
|        1|42358|
|        2|  164|
|        3|    2|
+---------+-----+
```

Original _pharmacogenomics_ input dataset
```spark
scala> original.withColumn("drugsSize", size(col("drugs"))).groupBy("drugsSize").agg(count("*").as("count")).orderBy(col("count").desc).show
+---------+-----+
|drugsSize|count|
+---------+-----+
|        1|42358|
|        2|  164|
|        3|    2|
+---------+-----+
```

The output for this run just for _pharmacognomics_ can be found at `gs://ot-team/mbernal/data/issue_3205/output`

**Comment by mbdebian** [comment]
I just corrected the bug in the grouping operation, results are in the same place
`gs://ot-team/mbernal/data/issue_3205/output`, the schema is now correct and the cardinality preserved.

And I have also run ETL just for _pharmacogenomics_, so the data at `gs://open-targets-pre-data-releases/24.06/output/etl/**/pharmacogenomics` is up to date.

**Comment by mbdebian** [comment]
ETL changes completed, now it needs to be addressed at the API

**Comment by ireneisdoomed** [comment]
Based on a conversation offline with @jdhayhurst we have set that:
- The reason the PGx endpoint has `drugId`, `drugFromSource` and `drug` is to account for the cases where we couldn't map the drug to any ID
- The front end is not using `drug` at all, it is just displaying `drugFromSource` and linking to the respective drug page with `drugId`
- We want to use the `drug` object every time we want to represent a drug

Given this, we propose a new type to represent drugs `DrugWithIdentifiers { drug: Drug, drugFromSource: String, drugId: String }`. This object is adaptable to both scenarios:
1. I have a drugFromSource that is mapped therefore `drug` can be resolved
2. I have a drugFromSource that is not mapped therefore i can just show `drugFromSource`

Actions:
- [ ] Change the representation of the drugs in the `Pharmacogenomics` endpoint to `drugs: Seq[DrugWithIdentifiers]`
- [ ] (Not directly related to this issue, but the situation is practically the same) Change the drug representation in the `ChemicalProbes` endpoint to `id: DrugWithIdentifiers` and delete `drugId`

**Comment by buniello** [comment]
I can see the FE change in [dev](https://platform.dev.opentargets.xyz/target/ENSG00000001626) and looking good

**Comment by ireneisdoomed** [comment]
Looking great! The genes with the maximum number of drugs in combination are [ENSG00000244122](https://platform.dev.opentargets.xyz/target/ENSG00000244122/associations) or [ENSG00000167165](https://platform.dev.opentargets.xyz/target/ENSG00000167165/associations), everything looks nice.

@gjmcn Take into account this will have an impact in the variant page work ([comment](https://github.com/opentargets/issues/issues/3318#issuecomment-2139756031))

**Comment by prashantuniyal02** [comment]
released in Platform 24.06


![Image](https://github.com/opentargets/issues/assets/122870584/3b593c03-29ca-4b5e-9b3b-ec1c84768695)
