### ISSUE TITLE
Target-Disease evidence from GEL PanelApp (panel name issue)

### ISSUE THREAD

**Issue by polrus** [opentargets/issues#3225]
As a **user of Open Targets platform** I want to see all relevant **Target-Disease evidence from GEL PanelApp** inferred from **Panel names** because some of **evidence are missing**

## Background

Target-disease evidence for GEL PanelApp currently relies on Phenotype assigned to each target. However, panel names can also indicate disease relevance, and overlooking this may result in missing evidence. For instance, the ["Infantile enterocolitis & monogenic inflammatory bowel disease" panel](https://panelapp.genomicsengland.co.uk/panels/176/), which explicitly mentions IBD, shows that many targets classified as green and amber lack associated [IBD evidence on the platform](https://partner-platform.opentargets.org/disease/EFO_0003767/associations?pinned=ENSG00000196839%2CENSG00000151694%2CENSG00000111732%2CENSG00000112182%2CENSG00000010671%2CENSG00000289746%2CENSG00000160654%2CENSG00000102245%2CENSG00000163599%2CENSG00000051523%2CENSG00000165168%2CENSG00000152457%2CENSG00000107099%2CENSG00000119888%2CENSG00000101311%2CENSG00000049768%2CENSG00000141349%2CENSG00000070019%2CENSG00000107521%2CENSG00000100099%2CENSG00000166189%2CENSG00000163600%2CENSG00000269335%2CENSG00000110324%2CENSG00000243646%2CENSG00000134460%2CENSG00000147168%2CENSG00000160255%2CENSG00000174405%2CENSG00000198589%2CENSG00000103313%2CENSG00000110921%2CENSG00000158517%2CENSG00000116701%2CENSG00000154124%2CENSG00000171603%2CENSG00000171608%2CENSG00000166349%2CENSG00000175097%2CENSG00000258366%2CENSG00000205413%2CENSG00000183918%2CENSG00000204351%2CENSG00000137700%2CENSG00000115415%2CENSG00000168610%2CENSG00000076944%2CENSG00000106799%2CENSG00000163513%2CENSG00000198677%2CENSG00000068724%2CENSG00000015285%2CENSG00000101966%2CENSG00000131620%2CENSG00000114270%2CENSG00000130826%2CENSG00000136634%2CENSG00000138684%2CENSG00000141458%2CENSG00000241973%2CENSG00000145675%2CENSG00000197943%2CENSG00000171862%2CENSG00000115085).

## Tasks

- [ ] Map panel names to EFO disease terms;
- [ ] Exclude nonsensical or overly broad disease names;
- [ ] Integrate new evidence into the platform.

## Acceptance tests

When I go to AOTF page I see new Target-disease evidence from GEL PanelApp.

**Comment by DSuveges** [comment]
That's very interesting. In other panels, the phenotypes usually provides a more detailed list of mappable diseases, which usually contains the disease from the panel name itself. See [autism](https://panelapp.genomicsengland.co.uk/panels/657/) for example. I remeber there was a discussion about how the panels, and the targets from a panel can be mapped to diseases and there was a justification for picking the phenotypes, however these discussions don't have github traces.

**Comment by d0choa** [comment]
@DSuveges, this makes sense, but we never act on it. Should we close the ticket and re-open it if necessary?

**Comment by DSuveges** [comment]
Let's close for now. There are so many other issues to work on for larger potential benefit.
