### ISSUE TITLE
Pharmacogenomics refactoring

### ISSUE THREAD

**Issue by remo87** [opentargets/issues#3228]
As a **developer** I want **implement the recommended changes in the PR** because **it improves the code base**

## Background

During the PR [329](https://github.com/opentargets/platform-etl-backend/pull/329) @ireneisdoomed suggested multiple refactoring opportunities for the pharmacogenomics step. We think these refactorings will make our code base better.

## Tasks

- [x] Have a single lookup table for names and CHEBI ids.
- [x] Rename the the cross reference fields to make the code more clear.
- [ ] Use the conditional join.

## Acceptance tests

How do we know the task is complete? 

1. The Pharmacogenomics step should run without any failure. 
2. The result of the step should not be affected. It should be the same as the previous version using the same input.

**Comment by prashantuniyal02** [comment]
@remo87 was this completed?

**Comment by javfg** [comment]
The parts of this that are still relevant are done. There could be more improvements when we decide to extract this step of the ETL to PySpark.
