### ISSUE TITLE
Allow replicates when ingesting genome-wide CRISPR screens

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3257]
So far, when ingesting CRISPR knock-out screens for PPP, we have one screen for each study. However OTAR2-061 introduces the concept of "replicates". These are different experimental runs of the same study. To increase confidence in the findings, we potentially need to read data from multiple replicates and only keep genes as hits that were identified as significant in all the replicates.

## Tasks

- [x] Update [PPP configuration](https://github.com/opentargets/PPP-evidence-configuration) and [config schema](https://github.com/opentargets/PPP-evidence-configuration/blob/master/tests/test_ot_crispr.py).
- [x] Update config files on `gs://otar013-ppp/PPP-evidence-configuration`
- [x] Upload input files to bucket: `gs://otar013-ppp/ot_crispr/input_data/OTAR2061`
- [x] Make [parser aware](https://github.com/opentargets/evidence_datasource_parsers/blob/master/partner_preview_scripts/ot_crispr.py) of replicate identifier.
- [x] Generate evidence
- [x] Validate

**Comment by DSuveges** [comment]
- [ ] Datafiles for all 16 studies from OTAR2061 were added to bucket.
- [ ] New PPP configuration was generated based on the updated table.
- [ ] PPP configuration was uploaded to google bucket.
- [ ] All evidence successfully validated against schema.
