### ISSUE TITLE
Implement facet id filter on AOTF endpoint

### ISSUE THREAD

**Issue by jdhayhurst** [opentargets/issues#3277]
As a user I want to be able to filter the AOTF results based on one or more facets.

Using facet ids from https://github.com/opentargets/issues/issues/3276 the user should be able to filter the AOTF results with these ids. 

The backend will resolve these facet ids to a set of target or disease ids and use that to filter the AOTF results. 

## Background

see https://github.com/opentargets/issues/issues/3239

## Tasks

- [x] add facet ID (Array) filter to AOTF endpoint
- [x] implement a resolver for facetIds -> target/diseaseIds
- [x] apply the target/diseaseIDs on AOTF

## Acceptance tests

How do we know the task is complete? 

1. when I use the AOTF API endpoint, I'm able to filter the results by one or more facetId(s)
