### ISSUE TITLE
Literature components refactor

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3292]
## Background

Frontend UI maintenance 

## Tasks

**Literature widget state refactor**
   - [x] Remove Recoil
   - [x] Migrate state to React Contex/Provider
  
**Literature components normalization** 
   - [ ] Publication item
      - [ ] Title
      - [ ] Authors
      - [ ] Extra publication details 
      - Actions (conditional)
         - [ ] Show summary
         - [ ] Show abstract
         - [ ] Show matches 
      - Indicators
         - [ ] Null || Full text free to use/read || Full text free to read

**Widgets columns**
   - [ ] Publication Drawer 
      - Input 1 or many pubs
      - API request to PubMed 
      - [ ] Reuse Table + PublicationItem

**Nice to have**
- [ ] Animation on transitions
- [ ] Split and/or label chips by entity
- [ ] Plot publications by date (attached to publications date filter *BE work required)
