### ISSUE TITLE
Preparation for the 24.06 data release

### ISSUE THREAD

**Issue by project-defiant** [opentargets/issues#3327]
As a **data release manager** I want **prepare gentropy for 24.05 data release** because **of planned changes in the data release schema**

## Background

Data release 24.06 should have following additions:

## Tasks
- [x] Update GWAS catalog clumping p-value significance from 5e-8 to 1e-8
- [x] Exclude PICS finngen credible set generation
- [x] Save feature matrix to persistent storage

## Acceptance tests

New data release produce feature matrix

How do we know the task is complete? 

1. When I go to page XX I see YY. 
2. When I click on 'foo' I see pop-up 'bar'
