### ISSUE TITLE
Determining list of paths and their location

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3344]
As requested by one of the Open Targets partners, to run certain gentropy pipeline steps, they would need to access the following files/directories in the Google Cloud Storage:

- [ ] gs://genetics_etl_python_playground/static_assets
- [ ] gs://genetics_etl_python_playground/input/Finngen_susie_finemapping_r10/Finngen_susie_credset_summary_r10.tsv
- [ ] gs://gwas_catalog_data/curated_inputs
- [ ] gs://gwas_catalog_data/manifests
- [ ] gs://genetics_etl_python_playground/input/preprocess
- [ ] gs://genetics_etl_python_playground/input/Finngen_susie_finemapping_r10/full (not for downloading all of the data, just for lookup to compare with the data published at gs://finngen-public-data-r10/finemap/full)

## Tasks

- [ ] Go through list of paths
- [ ] Decide which ones are inputs to include in the release
- [ ] Which ones are available in other FTP locations

**Comment by buniello** [comment]
closing as duplicate of [this](https://github.com/opentargets/issues/issues/3343)
