### ISSUE TITLE
Gentropy Airflow pipeline documentation

### ISSUE THREAD

**Issue by project-defiant** [opentargets/issues#3345]
As a **community user** I want **to be able to understand how the  Gentropy ariflow pipeline works ** because **I want to reproduce it with nextlfow.**

## Background

Background to this task is a result of a request send by community that stated:
* level of confusion around the four steps involved in ingestion of the GWAS catalog data 
  * `gwas_catalog_study_curation`
  * `gwas_catalog_study_inclusion` 
  * `gwas_catalog_ingestion`
  * `gwas_catalog_sumstat_preprocess` 
* Investigate usage of [nextflow](https://www.nextflow.io/) with gentropy and check the possibility of swapping airflow with nextflow.

## Tasks

- [x] Create screenshots from current airflow DAGs
- [x] Explain steps used to ingest the GWAS Catalog data

## Acceptance tests

How do we know the task is complete? 

1. Updated documentation around the GWAS Catalog ingestion process

**Comment by project-defiant** [comment]
The dags description:

## gnomAD preprocess
![gnomad_preprocess](https://github.com/opentargets/issues/assets/69353402/4e14fce3-3752-470f-97ed-e5a512b87a47)

## Finngen harmonisation
![finngen_harmonisation](https://github.com/opentargets/issues/assets/69353402/49e9fa0e-bf53-46bb-a301-5136ce77d1a3)

## eQTL preprocess
![eqtl_preprocess](https://github.com/opentargets/issues/assets/69353402/e31b6302-1da2-4809-92f7-2314f17bed2c)

## FInngen preprocess
![finngen_preprocess](https://github.com/opentargets/issues/assets/69353402/ae40585f-2471-4be0-a233-8be45dea32fc)

## GWAS Curation update
![gwas_curation_update](https://github.com/opentargets/issues/assets/69353402/18e1576e-da5d-4d09-a85c-3ab46eb1faf2)

## GWAS Catalog harmonisation
![gwas_catalog_harmonisation](https://github.com/opentargets/issues/assets/69353402/8c78e6ef-34d3-4101-b26c-025f33928c37)

## GWAS catalog preprocess
![gwas_catalog_preprocess](https://github.com/opentargets/issues/assets/69353402/31f7385a-f9a1-4194-bec6-98a7578e9e1d)

## Genetics ETL
![genetics_etl](https://github.com/opentargets/issues/assets/69353402/ea00c07d-7662-4f5f-8fc9-a6ac749a59c7)

**Comment by project-defiant** [comment]
Current documentation effords:
- [x] GWAS Catalog sumstat susie
- [x] GWAS Catalog sumstat pics 
- [x] GWAS Catalog top hits
- [x] UKB PPP EUR
- [x] FInngen r11
- [x] Credible_set_qc
- [ ] GWAS Catalog sumstat harmonisation
- [ ] Genetics ETL
