### ISSUE TITLE
Orchestration Layer

### ISSUE THREAD

**Issue by project-defiant** [opentargets/issues#3349]
As a **developer** I want **extract orchestration layer from gentropy pipeline** because **to be able to version it outside of gentropy development cycle**

## Background

The overall concept is to unify the orchestration around OpenTargets projects. The full description can be found in #3394.
This task is to extract the functionality of running dags that is prototyped in the [gentropy](https://github.com/opentargets/gentropy/tree/dev/src/airflow) to separate repository named [orchestration](https://github.com/opentargets/orchestration) and set the development and production flow.

The state of art to run the airflow pipeline consists of multiple best practices including:
- https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html
- https://www.astronomer.io/docs/learn/dag-best-practices
- [astronomer registry of operators](https://registry.astronomer.io/modules?types=operators)
- [module management](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/modules_management.html)

## Tasks

 * gentropy
    - [x] Remove airflow components from gentropy.
 * orchestration
    - [x] Move airflow components to the orchestration.
    - [x] Embed `ot_*` configs to the dag configurations.
    - [x] Define gentropy version to use inside the dag configurations.
    - [ ] ~~Submit gentropy package when by `install_dependencies` dataproc task.~~

## Acceptance tests

How do we know the task is complete? 
- [x] When gentropy does not reference the airflow depencencies, dags and config.
- [x] When clean setup of orchestration repository is successfully performed by following the docuemtnation
- [x] When dag is run successfully.

**Comment by javfg** [comment]
Adding Szymon here too, as he is the one working on this.

**Comment by project-defiant** [comment]
Marking this as close, there are two follow up issues:
- #3431
- #3345
