### ISSUE TITLE
Variant search - backend

### ISSUE THREAD

**Issue by jdhayhurst** [opentargets/issues#3365]
We need a enable the search of variants in the OpenTargets platform search. 

## Background

It should be possible to search on

- variant id (chr_pos_ref_alt)
    - search on exact ”chr_pos_” then suggest all the variants at that location
    - when searching for full id it has to be exact match
    - remember there are long allele strings - will this be an issue for the API?
    - 10^7 variants
    - also enable searching on synonyms
        - gnomad notations
        - rsid
        - etc.

Data should come from the variant output from gentropy: https://github.com/opentargets/issues/issues/3350

what happens when you search? 
- type and suggestions happens live suggesting the variant, fixing at the start and only recommending completed terms for exact of this starting string
- type + hit return - search results page (variant object should be in the results)

should we return top genes - yes this can be pre-computed and weighted from transcriptConsequences.distance and transcriptConsequences.targetId. 
- once connected to the target
- connect to the disease and drug in the same way as is done for other entities and return those as well.
 
## Tasks

- [x] ETL to generate the variant_search opensearch index
- [ ] ETL to add variants into the disease and target search indices
- [x] configure POS to build the backend including the variant_search index
- [x] Enable the search API to search this variant_search index

## Acceptance tests

How do we know the task is complete? 

1. When I run the ETL, the variant search index is generated
2. When I run POS, the variant search index is added to the opensearch backend
3. When I query the API for the search endpoint, I can search for variants.

**Comment by buniello** [comment]
@carcruz and FE team feel free to start exploring this dataset from your side (as discussed in the team leads meeting)

**Comment by DSuveges** [comment]
> disease and target labels should not be added to the variant search index. However, the variants should be added to the target search index.

So it means, when searching for a variant, we'll get targets and diseases suggested, but no variants are suggested if searched for a diseases or targets? I very much agree with this call.

**Comment by buniello** [comment]
As discussed this week, @gjmcn and @chinmehta will start building a FE feature on top of the current API & while james is on holidays. tagging @prashantuniyal02 for reference in the next two weeks.

**Comment by emcdonagh-OT** [comment]
May be out of scope for the MVP, but it would be great to have the ability to search by protein coordinates, as well as genomic, as part of the variant synonyms as for coding variants this is how people will recognise/remember them and want to look them up. This may already be covered but couldn't see reference above. 

Some examples: 
rs121913530: KRASG12C, NP_203524.1:p.Gly12Cys
rs186045772: CFTRF1074L, NP_000483.3:p.Phe1074Leu 


The ProtVar team (contact: James Stephenson) has different kinds of mappings for genome > protein which may be useful.

**Comment by d0choa** [comment]
As discussed in Aug 7th...

- some BE work is still required, as reported by @jdhayhurst
- @gjmcn and @chinmehta starting to think about FE requirements/ideas
- it would be good to identify any pending BE requirements early so we can move on with UI implementation
