### ISSUE TITLE
Add latest secondary pharmacology target-phenotype relationships to Safety Widget

### ISSUE THREAD

**Issue by inessmit** [opentargets/issues#3367]
As a user I want to view the most recently published secondary pharmacology targets because they provide a set of true positive target-phenotype relationships representing safety liabilities and are an industry standard.

## Background

The current Safety Widget contains target-phenotype relationships from publications such as Bowes, Lynch etc based on industry-derived panels of safety-related targets screened during drug development. Recently an updated compilation was published by former OT Safety Project member Richard Brennan and co-authors (https://www.nature.com/articles/s41573-024-00942-3). The updated data (Table 1 in the article) would enrich the platform and it fits the existing data model easily.

## Tasks

- [x] Extract the clinical data from the Table 1 (https://www.nature.com/articles/s41573-024-00942-3/tables/1) 
- [x] Map targets to Ensembl identifiers
- [x] Map phenotype terms to EFO
- [ ] Integrate into Platform

## Acceptance tests

How do we know the task is complete? 

1. When I go to the Safety Widget / download the target data, I can see the data from the paper standardised to EFO where possible.

**Comment by inessmit** [comment]
@ireneisdoomed When would you need the data to include this in the next release?

**Comment by ireneisdoomed** [comment]
@inessmit Our deadline to get the new data ready would be around August 9th

**Comment by inessmit** [comment]
[brennan_2ndary_pharm_for_ot.json](https://github.com/user-attachments/files/16364447/brennan_2ndary_pharm_for_ot.json)

I extracted the human data from Brennan et al. and manually mapped to EFO where possible. It contains data for 27 targets.
Tried to follow the existing data model. @ireneisdoomed Let me know if it passes the tests and is in the correct format or if any changes are needed.

Thank you!

**Comment by ireneisdoomed** [comment]
Thank you very much for all this work @inessmit! Let me share some notes I made when reviewing the data:

### General comments
- All risks curated from Table 1 are from clinical findings. The ones in brackets are derived from preclinical studies, and have been excluded. As discussed, I think they bring value. We just need a better definition in the schema to distinguish the source of the evidence.
- The system assignation is too unifying. An event was observed in all reported systems. See EGFR, hepatotoxicity is clearly only associated with the liver, skin rash with the skin... I understand how the data is presented relative to the AE and we want to make target level annotations. We want to make it more granular by assigning the right system for each event without compromising data accuracy from the source. By looking at them I think it's easy to make the distinction. As discussed, this is not the approach followed in other sources like Bowes, so we should ammend this in the short term.

### Suggestions
- For _MAOB_:
	- separate `neurological issues (dyskinesia/hallucinations)` into each phenotype, so that it is clearer that one evidence is for `dyskinesia` and another one for `hallucinations`
- For CCKBR:
	- map hypergastrinemia to `MONDO_0001770`;
	- map Increased gastric acid secretion volume to `MONDO_0001770`;
	- map Increased gastric acid secretion rate to `MONDO_0001770`;
	- map `increased gastric pH due to suppression of gastric acid secretion` to `MONDO_0001318`
- For _ESR1_:
	- map breast atrophy to EFO_0009483;
	- map vaginal atrophy to MONDO_0001433;
	- map increased risk of thrombosis with MONDO_0000831;
- For _ATM_:
	- map growth retardation to HP_0001510;
- For  *EGFR*:
	- Rename the `ALT` event to `ALT increase`;
	- map ocular keratitis to EFO_0009449;
	- map decreased appetite to EFO_0005203;
- For _GSK3B_:
	- map motor dysfunction to EFO_1001902
- For _KDR_:
	- map decreased appetite to EFO_0005203;
- For _MAP2K7_;
	- map sensorimotor disorder to EFO_0001058
- For  _NTRK1_:
	- separate epilepsy/seizures into each phenotype, so that it is clearer that one evidence is for `epilepsy` and another one for `seizures`
- For __PIK3CG__:
	- map decreased appetite to EFO_0005203;
- For __PTK2__:
	- combine `reduced platelet adhesion` and `aggregation`  into a single one: `reduced platelet adhesion and aggregation` 
	- rename `abnormal platelet production and function` and `liver and skin fibrosis` to `Tumour promotion: abnormal platelet production and function` and `Tumour promotion: liver and skin fibrosis

**Comment by inessmit** [comment]
Thanks a lot for the feedback and suggestions @ireneisdoomed !

**Preclinical findings**
I will extract the preclinical findings and as discussed we can use the "safetyLiabilities" > "studies" > "type" field to categorise the findings into 'preclinical' vs 'clinical'.
This field seems appropriate, it's used for the PharmGKB data to assign "patient-level" and for the Tox21 to assign e.g. "biochemical" or "cell-based".

**Organ system mappings**
I will try to map the organ systems to a more granular level

**Phenotype mappings**
Thanks for the additional phenotype mapping suggestions, that's great. Will consider and prepare an updated json file to upload here.

**Comment by inessmit** [comment]
New file attached.
[brennan_2ndary_pharm_for_ot_v2.json](https://github.com/user-attachments/files/16563437/brennan_2ndary_pharm_for_ot_v2.json)


- Adopted nearly all of your suggested EFO mappings
- Extracted all the preclinical findings (mapped to human target) using the "studies" > "type" field to distinguish "preclinical" from "clinical". Updated total number of targets is 33.
- Added more granular uberon mappings, as discussed there are some missing values and also inevitable inconsistencies, but the approach should be more informative than the previous target-based annotation

Thanks a lot for your help @ireneisdoomed, has made the extraction a lot more comprehensive.

Any issues let me know.

**Comment by ireneisdoomed** [comment]
This new source has brought information for 33 targets, 10 of which didn't have prior safety annotation.

This is what the widget looks like for [EGFR](https://platform.dev.opentargets.xyz/target/ENSG00000146648)
<img width="1110" alt="image" src="https://github.com/user-attachments/assets/59ec7f66-6309-4c0e-967f-ed612d51c207">

No pending actions on BE/FE. @inessmit, let us know if you have comments.

```
# Targets with liabilities from Brennan et al only
+---------------+                                                               
|             id|
+---------------+
|ENSG00000172175|
|ENSG00000117984|
|ENSG00000152256|
|ENSG00000179921|
|ENSG00000069535|
|ENSG00000076984|
|ENSG00000141867|
|ENSG00000110148|
|ENSG00000157103|
|ENSG00000183695|
+---------------+
```

**Comment by inessmit** [comment]
Fantastic, preview for EGFR looks good, thank you @ireneisdoomed
