### ISSUE TITLE
Changes in Validation Lab data

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3375]
Explanation on the tasks:

### Task 1: change in assessment field (string vs list)

The assessment column in the validation lab evidence table comes with text with new-line characters in them. In the current parser, these newline characters are [explicitly dropped](https://github.com/opentargets/evidence_datasource_parsers/blob/1b9170fbde88b037011bd673c814550b779cd757/partner_preview_scripts/ValidationLab.py#L330). However, for downstream considerations, instead of creating a single string, the field should be split by the newline characters. 

**Sub tasks**:

- [x] Make required changes in the parser.
- [x] Update the json schema accordingly (the singular name `assessment` should be changed to plural to imply an array).
- [x] Run snakemake on this dataset to ensure integration.
- [x] Let backend team know about the schema change.
- [ ] Let frontend team know about the schema change.

See snakemake configuration for input files.

### Task 2: ontology re-organisation

The assigned EFO for the colo dataset was not correct. Instead of Colorectal Adenocarcinoma (`EFO_0000365`), we should use colorectal carcinoma (`EFO_1001951`) as it represents the experiments better and is consistent with the ENCORE project.

**Sub tasks**:

- [x] Update validation lab configuration in [PPP config repo](https://github.com/opentargets/PPP-evidence-configuration)
- [x] Copy all updated config files to google cloud location: `gs://otar013-ppp/PPP-evidence-configuration`
- [x] Run evidence parsers and verify the updates are present.

## Background

Changes in Validation Lab data

- change in assessment field (string vs list)
- ontology re-organisation

## Tasks

- [ ] change in assessment field (string vs list)
- [ ] ontology re-organisation

**Comment by buniello** [comment]
Once the assessments are modified to a `list`, we could think about a different visualisation style for the `OTVL assessment` column fields.

**Comment by DSuveges** [comment]
Explanation on the tasks:

### Task 2: ontology re-organisation

The assigned EFO for the colo dataset was not correct. Instead of Colorectal Adenocarcinoma (`EFO_0000365`), we should use colorectal carcinoma (`EFO_1001951`) as it represents the experiments better and is consistent with the ENCORE project.

**Sub tasks**:

- [ ] Update validation lab configuration in [PPP config repo](https://github.com/opentargets/PPP-evidence-configuration)
- [ ] Copy all updated config files to google cloud location: `gs://otar013-ppp/PPP-evidence-configuration`
- [ ] Run evidence parsers and verify the updates are present.

**Comment by DSuveges** [comment]
@StuartHorswellOT provided new files we need to re-wire our configs to pick up:

```
gs://otar013-ppp/validation_lab/input_data/2024.06/OTVL-SCORE-PPP_Br_ScaledAssessmentScore_May2024_v2.txt
gs://otar013-ppp/validation_lab/input_data/2024.06/OTVL-SCORE-PPP_Br_ScaledAssessmentScore_May2024_v3.txt
```

**Comment by DSuveges** [comment]
@remo87 The schema change looks like this:

```json
{
    "assessment": "No evidence of dependency No evidence of toxicity",
}
```

new:

```json
{
  "assessments": [
    "Evidence of dependency",
    "No evidence of toxicity"
  ]
}
```

**Things to update:**

- Remove `assessment` from schema
- Add `assessments` to schema as a list of string.

Please let us know when things are ready, we need to keep the frontend team in the look as well.

**Comment by remo87** [comment]
Is the assesment field only used in the validation lab evidence? Also I checked the data from 24.03 and I didn't see the assesment field in the evidence  input (validation_lab.json.gz). Was this field not available at the time?

**Comment by javfg** [comment]
The changes in API are ready! (pending confirmation the field is not used anywhere else).

**Comment by DSuveges** [comment]
> @DSuveges @d0choa  Is the assesment field only used in the validation lab evidence? Also I checked the data from 24.03 and I didn't see the assesment field in the evidence  input (validation_lab.json.gz). Was this field not available at the time?

- yes, the assessment was introduced in the 24.06 PPP release.
- yes, it's just the validation lab that uses this field.

**Comment by mbdebian** [comment]
@javfg and @remo87 , would you mind giving the team a shout as soon this goes through the ETL and is deployed in _dev_?

**Comment by prashantuniyal02** [comment]
The widget still has a FE error in the latest PPP development.

**Comment by buniello** [comment]
Please note that the change `change in assessment field (string vs list)` allows more freedom in visualisation of assessments within the `OTVL assessment` column - e.g. strings could be shown as bullet points or even in a fancier way. This is something that FE could think about for this or future PPP releases @prashantuniyal02
