### ISSUE TITLE
Explore adding the associated entities to the facets index

### ISSUE THREAD

**Issue by jdhayhurst** [opentargets/issues#3380]
After discussion with @opentargets/fe-team, it may be useful to be able to search the disease facets by the associated target and vice versa. 

## Background

To enable some discoverability of the facets, it would be useful to be able to filter the facets by the associated entity. These facets could be forwarded to the user, to inform them of the available facets.

## Tasks

- [ ] Add the associated entities to the indices
- [ ] Add an argument for the associated entity
- [ ] Apply the associated entity id as a filter
- [ ] Respond as current, but also aggregated by category
