### ISSUE TITLE
Backend workflow

### ISSUE THREAD

**Issue by javfg** [opentargets/issues#3383]
# Backend Workflow
The backend team is looking to define a development workflow to unify the processes in all our repositories. Having a standard workflow serves as a guide on how to do things, avoids mistakes and it can be improved upon.

After discussions in the weekly team meeting, we decided we could also show this to the other teams (frontend, data), and maybe make it (or parts of it) go organization-wide.

## Key processes to define
1. Git workflow
2. Naming conventions for versioning, commits, releases
3. Operations
  3.1. Feature development
  3.2. Releases
  3.3. Hot-fixes
4. CI/CD pipeline

---

## Tasks

- [x] Evaluate and decide on a workflow, naming conventions and ops
- [x] Write a document detailing it
- [ ] Backend team discussion
- [x] Migrate PIS from Travis CI to GitHub Actions
- [x] Migrate ETL from Travis CI to GitHub Actions
- [ ] Migrate POS from Travis CI to GitHub Actions
- [ ] Set up a test-drive of the GitHub automation in one of the repos
- [ ] Lock down main branch
- [ ] Create issue/bug report/PR templates

--- Once the workflow is agreed upon with the backend team ---

- [ ] Set up the workflow for the remaining repositories
- [ ] Show the workflow to data / frontend teams for them to bring in suggestions
- [ ] Update operational docs

**Comment by javfg** [comment]
During the period up to the 25.03 release, we can continue working on this slowly as we improve our repos. We'll focus on it after.

**Comment by javfg** [comment]
It's time to resurrect this!
