### ISSUE TITLE
Refactoring of the docker release process for gentropy

### ISSUE THREAD

**Issue by project-defiant** [opentargets/issues#3384]
As a **developer** I want **to be able to use gentropy docker image on processors with arm64 and amd64 architectures** because **this will be crusial for the developers with Mac M1 (arm64)**.

## Background

The development of the [orchestration pipeline](https://github.com/opentargets/orchestration) requires accessing the gentropy image as a way to run gentropy steps in the [google batch](https://cloud.google.com/batch/docs/reference/rest) job task specification as a part of orchestration DAGs. This means that for the local development requires accessing the docker container generated by the [Build and Push to Artifact Registry](https://github.com/opentargets/gentropy/blob/dev/.github/workflows/artifact.yml) github action that runs on each successful push to the `dev` branch.

> [!Caution]
> The above is not ideal due to couple of reasons. 
> 1. We have only access to the `dev` tag which might be overwritten by the next merge of PR to the dev branch, thus resulting in the unknown version of the gentropy that would be run by the google batch service.
> 2. Gentropy image lacks prover version to follow it's release process to pip (the package is hosted in the pip registry - pushed to the registry by the [Release action](https://github.com/opentargets/gentropy/blob/dev/.github/workflows/release.yaml). 
> 3. The (2) was partially addressed by the #692, which introduced triggering  `Build and Push to Artifact Registry` on push to the tags. This was unsuccessful, as the release action push the release tag generated by `python-semantic-release` with authentication provided by the `GITHUB_TOKEN` which prevents github actions to be triggered in the tag ref. See [triggering-a-workflow-from-a-workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow) for more details.
> 4. Once the gentropy container is build and pushed to the `europe-west1-docker.pkg.dev/open-targets-genetics-dev/gentropy-app/gentropy:{tag}` we also need to be able to use it on processors with `arm64` architecture without building it from source. This means that gentropy docker image needs to be created with [multi architecture build](https://cloud.google.com/kubernetes-engine/docs/how-to/build-multi-arch-for-arm) and versions for all architectures needs to be pushed to artiifact registry
> 5. Finally we can drop the `Google cloud SDK and jq` from the gentropy container, as these tools are not required by gentropy itself and they will be added to the image that overloads current gentropy image for the orchestration pipeline usage.
> 6. Gentropy image requires changing the `JAVA_HOME` env to `/usr/bin`, as otherwise the java11 path installed from the apt repository will vary between different architectures - see offending line [here](https://github.com/opentargets/gentropy/blob/9b2ba40100b8177e0864ea4af748ec00d5e1f0c7/Dockerfile#L27C15-L27C49) which is correct for amd64 is correct, for arm64 it will be `/usr/lib/jvm/java-11-openjdk-arm64`

## Tasks

- [ ] Create Github App and install it in the gentropy repository to allow for the authentication using Github App token that should trigger workflow on push new tag - [usefull tutorial](https://www.youtube.com/watch?v=xtXnIV20XQw),  create `APP_ID` variable and `APP_KEY` secret from the Github App pem key - these are the requirements for authentication.
- [ ] Adjust the [Publish package to Github Release](https://github.com/opentargets/gentropy/blob/9b2ba40100b8177e0864ea4af748ec00d5e1f0c7/.github/workflows/release.yaml#L32) to use the token generated by the [create-github-app-token action](https://github.com/actions/create-github-app-token) ensuring the app token is used instead of the `GITHUB_TOKEN`
- [ ] Refactor the [gentropy Dockerfile](https://github.com/opentargets/gentropy/blob/dev/Dockerfile), drop Google cloud SDK, jq installation, change the JAVA_HOME to `/usr/bin/`.
- [ ] Update the [Build and Push to Artifact Registry](https://github.com/opentargets/gentropy/blob/dev/.github/workflows/artifact.yml) for multi architecture build - can use the [build-push-action](https://github.com/docker/build-push-action) with `platforms` to match [target platforms](https://docs.docker.com/reference/cli/docker/buildx/build/#platform) or use the `docker buildx` command manually.
- [ ] Do above for the VEP image as well.

## Acceptance tests

How do we know the task is complete? 

1. When the push to main branch will trigger the `Build and Push to Artifact Registry` workflow in the tag.
2. When the image build from the tag will have corresponging tag in the registry
3. When the image pulled from the registry after the release will be running on amd64 and arm64 processors respectively.

**Comment by project-defiant** [comment]
After testing approach with using the token generated by the github app, we encountered that the `Build and Push to Artifact Registry` job has not started. 

To solve above issue I checked again that the tag is pushed by the github actions user when running the `Python Semantic Release` rather then `Publish package to GitHub Release`, which is obvious to me now.

I swapped the token usage for the jobs and added additional parameter to the checkout action, as in https://github.com/semantic-release/semantic-release/discussions/1906

**Comment by project-defiant** [comment]
After release v1.7.0 new image for the gentropy can be found under the `europe-west1-docker.pkg.dev/open-targets-genetics-dev/gentropy-app/gentropy:v1.7.0` that corresponds to the poetry tag. The `Build and Push to Artifact Registry` was succesfully triggered from other pipeline downstream.
