### ISSUE TITLE
Pipeline unification

### ISSUE THREAD

**Issue by javfg** [opentargets/issues#3394]
# Pipeline unification
> [!IMPORTANT]
> This is a work in progress. New tasks must be added and others must change.

## Objective
The aim is to unify the pipelines of [Gentropy](https://github.com/opentargets/gentropy), Platform ([PIS](https://github.com/opentargets/platform-input-support), [ETL](https://github.com/opentargets/platform-etl-backend)), and the [Evidence Datasource Parsers](https://github.com/opentargets/evidence_datasource_parsers/).

Gentropy has a sane orchestration layer, based on [Apache Airflow](https://airflow.apache.org/). It is built using modern Python and follows good practices. We can extract this layer into an independent package and then use it to run the whole data processing work of Open Targets. For this, we need to adapt the Platform pipeline and the Evidence Datasource Parsers.

## Tasks
> [!NOTE]
> When work in a task starts, edit this list and add the relevant issue.

- [x] Orchestrator/Gentropy
  - [x] Extract the orchestration layer from Gentropy: opentargets/issues#3349
  - [x] opentargets/orchestration#27
  - [x] Decide on and set up development and production instances of Airflow (Pending) 
  - [x] Submerge genetics_etl with variant_index dag - part of https://github.com/opentargets/orchestration/issues/57
- [ ] Platform 
  - [x] Modernize PIS so it can run on Airflow: opentargets/issues#3382
  - [x] Create a graph for running PIS in Airflow: https://github.com/opentargets/orchestration/commit/124339341ec76a625b9d91b5f0ded92c8d65cca3
  - [x] Migrate the ETL graph to Airflow: opentargets/issues#3396
  - [ ] opentargets/issues#3481
    - [x] opentargets/issues#3495
    - [x] opentargets/issues#3496
    - [ ] opentargets/issues#3497
    - [ ] opentargets/issues#3498
    - [x] opentargets/issues#3506  
    - [x] opentargets/issues#3482
    - [x] opentargets/issues#3483
    - [x] opentargets/issues#3499
    - [x] opentargets/issues#3488
    - [x] opentargets/issues#3489
    - [x] opentargets/issues#3490
    - [x] opentargets/issues#3491
- [ ] Evidence Datasource Parsers (Pending)
- [ ] Documentation
  - [ ] opentargets/issues#3345
  - [ ] More (Pending)
- [x] Output decision, how to handle POS: https://github.com/opentargets/issues/issues/3470
- [x] Unify platform DAG and genetics DAG into one pipeline: https://github.com/opentargets/orchestration/pull/84

## Scope
This not a full rewrite of the Platform pipeline. When Platform ETL can run as Airflow tasks, new possibilities will open to improve it, but those are not part of this undertaking.

## Outcome
For the merge to be valid, these conditions must be met:
* The orchestrator must be able to run Gentropy, Platform pipeline (PIS->ETL) and the Evidence Datasource Parsers
* POS must be able to hook into the orchestrator and generate a valid output
* Using Airflow we must ensure parts of the process can still be run separately in a modular way
