### ISSUE TITLE
Port the ETL launch to Airflow

### ISSUE THREAD

**Issue by javfg** [opentargets/issues#3396]
This task is under the context of the unification of the Gentropy and Platform data pipelines (#3394).

# Description of the work
Extend the [`platform-input-support` graph](https://github.com/opentargets/orchestration/commit/124339341ec76a625b9d91b5f0ded92c8d65cca3) in Airflow with the ETL steps.

Currently, determining the order of execution of the ETL steps is handled by Google Dataproc. To be able to integrate it in the unified pipeline, we must describe this dependency graph in [the orchestrator](https://github.com/opentargets/orchestration).

This is the dependency graph for the ETL steps, including the dependencies from PIS steps:

![etl-dependencies-2](https://github.com/user-attachments/assets/b226b39a-da3c-4960-ba22-0b128d9f99db)

# Tasks and current status
- [x] Determine the dependencies between each step in the ETL
- [x] Determine the dependencies ETL steps have on PIS steps, to be able to plug both parts
- [x] Extend the orchestrator `platform-input-support` graph with tasks for the ETL
