### ISSUE TITLE
Update API dependencies.

### ISSUE THREAD

**Issue by remo87** [opentargets/issues#3419]
As a **developer** I want **the dependencies to work under the latest versions** because **I want to avoid security and compatibility issues**

## Background

The API dependencies have been updating it's versions and the ones we're working on are not the latest. We should move to the latest versions to take advantage of performance and security improvements and check if there's new features available. Once we have moved all of our dependencies to latest versions we can evaluate moving to Scala 3.

## Tasks

- [x] Update dependencies
- [x] Test functionality
- [x] Update to Scala 3
- [x] Test functionality

## Acceptance tests

How do we know the task is complete? 

1. When we check the sbt and all the dependencies are updated
2. When we open the playground and the we can run the queires
3. When we open the platform and we can navigate it without any issues

**Comment by remo87** [comment]
The api has been deployed to a new environment [versions](https://versions.dev.opentargets.xyz/) @prashantuniyal02 @buniello could you help me testing this environment and report any errors you see.

**Comment by prashantuniyal02** [comment]
Issues with the latest dev version:

- [ ] Issue with the search results and suggestions
<img width="1426" alt="image" src="https://github.com/user-attachments/assets/e2aa5315-be19-4267-b95d-93f1f17b5359">

- [ ] ChEMBL widget error
<img width="1390" alt="image" src="https://github.com/user-attachments/assets/4dfb8410-5334-468f-ba40-f45ba4225125">

- [ ] Issue with bibliography chips
<img width="1378" alt="image" src="https://github.com/user-attachments/assets/13a951aa-3431-4fff-9fe2-2875d1748c21">

**Comment by prashantuniyal02** [comment]
@remo87 to update this

**Comment by javfg** [comment]
This is finished and tested in 2503 dev. Some outstanding issues may be undiscovered, but they are now easy to fix.
