### ISSUE TITLE
Finngen r11 susie finemapping ingestion

### ISSUE THREAD

**Issue by project-defiant** [opentargets/issues#3421]
As a **developer** I want **add finngen r11 susie finemapping results and combine the finngen study index with EFOs** because **I want to increase the number of possible features for 24.08 genertics data release.**

## Background

Finngen has released **r11** data freeze [DF11 - June 24 2024](https://www.finngen.fi/en/access_results). The data release contains following structure.

```
gs://finngen-public-data-r11/finngen_R11_pheno_n.tsv
gs://finngen-public-data-r11/annotations/
gs://finngen-public-data-r11/finemap/
gs://finngen-public-data-r11/hla/
gs://finngen-public-data-r11/lof_2.0/
gs://finngen-public-data-r11/meta_analysis/
gs://finngen-public-data-r11/summary_stats/
```
Data release can be accessed by `gs://finngen-public-data-r11` bucket on GCS.

Inside the `/finemap` we can find full susie finemapping loci results, full finemap finemapping results and summaries across all of them. 
There is no README for the r11 data release, but good proxy can be found under `gs://finngen-public-data-r10/finemap/finngen_R10_finemap.md` reference.

For the finemapping we require following datasets from r11  release:
```
gs://finngen-public-data-r11/finemap/summary/*.cred.summary.tsv # credible sets
gs://finngen-public-data-r11/finemap/full/susie/*.snp.bgz # raw variants
```
All of files that are captured by the glob above should be used to ingest the r11 susie finemapping.
While credible sets can be read directly from pyspark (as they are flat tsv files), the bgz - `block gzipped` files can not be read without additional codecs (HTSlib) provided.

One approach to resolve the issue with the `snp` files was to download them and extract block gzipped compressed files to gzipped compressed files and store them on our end under `gs://genetics_etl_python_playground/input/Finngen_susie_finemapping_r10/full/`. This would have to be done every time new release is done by finngen (at most 1 more).

An alternative approach is to use `hail.import_table` as it can read the block gzipped files natively.

There is one more limitation to gzipped files, that they have to be read by a single node, the read is not parallelized, so it is better to use a different compression algorithm for spark. In case of finngen the file sizes does not matter that much.

The outliers for finngen looks like:

```
1.12 GiB     gs://finngen-public-data-r11/finemap/full/susie/finngen_R11_I9_VARICVE.SUSIE.snp.bgz
1.18 GiB     gs://finngen-public-data-r11/finemap/full/susie/finngen_R11_T2D_WIDE.SUSIE.snp.bgz
1.21 GiB     gs://finngen-public-data-r11/finemap/full/susie/finngen_R11_RX_STATIN.SUSIE.snp.bgz
1.3 GiB      gs://finngen-public-data-r11/finemap/full/susie/finngen_R11_E4_HYTHY_AI_STRICT.SUSIE.snp.bgz
1.5 GiB      gs://finngen-public-data-r11/finemap/full/susie/finngen_R11_I9_HYPTENSESS.SUSIE.snp.bgz
1.51 GiB     gs://finngen-public-data-r11/finemap/full/susie/finngen_R11_KELA_DIAB_INSUL_EXMORE.SUSIE.snp.bgz
1.6 GiB      gs://finngen-public-data-r11/finemap/full/susie/finngen_R11_T2D.SUSIE.snp.bgz
1.69 GiB     gs://finngen-public-data-r11/finemap/full/susie/finngen_R11_RX_ANTIHYP.SUSIE.snp.bgz
1.8 GiB      gs://finngen-public-data-r11/finemap/full/susie/finngen_R11_I9_HYPTENS.SUSIE.snp.bgz
2.91 GiB     gs://finngen-public-data-r11/finemap/full/susie/finngen_R11_BMI_IRN.SUSIE.snp.bgz
3.21 GiB     gs://finngen-public-data-r11/finemap/full/susie/finngen_R11_WEIGHT_IRN.SUSIE.snp.bgz
4.84 GiB     gs://finngen-public-data-r11/finemap/full/susie/finngen_R11_HEIGHT_IRN.SUSIE.snp.bgz
```

## Tasks

- [x] Update finngen study_index generation for r11 release
- [x] Update finngen fine_mapping ingestion for r11 release
- [x] Read susie fine mapping variants directly from finngen bucket (skip downloading and unpacking them) with hail
- [x] Drop finngen airflow dags from gentropy
- [x] Update finngnen airflow dags to orchestration
- [x] deprecate finngen sumstat preprocess DAG
- [x] Upload new datasets to `gs://finngen_data/r11` 

## Acceptance tests

Test if reading block gziped file works with hail in gentropy.

**Comment by project-defiant** [comment]
r11 dataset ingested at:
* finngen r11 studyIndex (with EFO terms provided by Jack and Irene -->  gs://finngen_data/r11/study_index
* finngen r11 susie -> gs://finngen_data/r11/finemapping
