### ISSUE TITLE
Unify Gentropy ETL and Variant Index DAGs

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3431]
As a **developer** I want **to define all the Gentropy steps required to produce a data release in a single DAG** because **we currently have dependencies between DAGs that require manual intervention**.

## Background

This is the current `genetics_etl` DAG.
![image](https://github.com/user-attachments/assets/cb13c543-08d0-4449-9b9e-a87f9fc7367c)

The actual DAG that calls Gentropy steps and sets their dependencies was originally defined using a YAML file.
```
# for example
- id: "ot_variant_to_gene"
  prerequisites:
    - "ot_gene_index"
```
The DAG reads this YAML and dynamically creates the tree of nodes. This solution worked because all the steps in this process were actual Gentropy steps that were submitted using the Spark Job operator.

The new version of the variant index has introduced complexities that have required to develop an independent DAG, that calls several types of operators:
<img width="997" alt="image" src="https://github.com/user-attachments/assets/d10fa580-640b-4db0-bee4-a79c16401d77">

**This breaks the independence between DAGs because:**
1. To call the variant index DAG, you need to produce credible sets in the genetics ETL DAG
2. The variant index is a dependence of the V2G step in the genetics ETL DAG

## Tasks

We need to solve this circularity issue by integrating the variant and the genetics DAGs into a single one

- [ ] Ditch `dags/configs/dag.yaml`
- [ ] Update `dags/genetics_etl.py` so that the Dataproc jobs are instantiated in this module
- [ ] Define a task group that stores the logic from `dags/variant_index.py` and move it to `dags/genetics_etl.py`
