### ISSUE TITLE
L2G feature matrix revision

### ISSUE THREAD

**Issue by xyg123** [opentargets/issues#3432]
As a **developer** I want **to revise and refactor some of the logic in the L2G feature matrix generation step** 

## Background

tbd.

## Tasks

- [ ] Refactor logic for assigning potential target genes to studyLocusIds, to include genes in proximity to **all** variants in the studyLocus, instead of just the top hit.
- [ ] Implement logic to assign potential target genes which have a colocalisation result with a studyLocus, but is out of range from the studyLocus.
- [ ] Include additional **distance to footprint** feature in the L2G model, using the latest VEP variant index.
- [ ] Implement logic to save the feature matrix when it is generated.
- [ ] Implement logic to merge features across studies which have the same EFO, to address the missingness rate of features in L2G.
- [ ] Refactor logic for gold standard Negative selection process, to prioritise keeping GSNs with non-distance features, followed by prioritising the closest genes.
- [ ] Implement logic to remove studyLocus where all potential target genes have only distance-based features from the training set.

**Comment by addramir** [comment]
As a general plan looks good to me. @ireneisdoomed and @DSuveges please have a look to, but we need more granular plan on this. In general, the top priority for us is to reach the level of clean credible set level feature matrix as a first step implementing suggestions above.

**Comment by project-defiant** [comment]
@ireneisdoomed which tasks from the list above are going to be implemented in the l2g fm refactoring?

**Comment by ireneisdoomed** [comment]
None. The refactoring I am doing is to solve #3252

**Comment by addramir** [comment]
@xyg123 
> Refactor logic for assigning potential target genes to studyLocusIds, to include genes in proximity to all variants in the studyLocus, instead of just the top hit.

- I guess it should be covered by issue adding tss and footprint based features? https://github.com/opentargets/issues/issues/3258

> Implement logic to assign potential target genes which have a colocalisation result with a studyLocus, but is out of range from the studyLocus.
- I guess it should be covered by issue adding coloc based features? https://github.com/opentargets/issues/issues/3252

> Include additional distance to footprint feature in the L2G model, using the latest VEP variant index.
https://github.com/opentargets/issues/issues/3258

The rest is ok.

**Comment by addramir** [comment]
We need to re-write this issue next week.

**Comment by addramir** [comment]
The issue was spllited on several issues.
