### ISSUE TITLE
Drop V2G step

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3434]
As a **developer** I want **to delete the step that generates a variant to gene dataset** because **it is an auxiliary concept that is only useful in the context of generating features for L2G.**

## Background

Discussed during the Gentropy meeting 29/08.

A variant-to-gene (V2G) evidence is understood as any piece of evidence that supports the association of a variant with a gene. Current V2G sources are:
- Distance of a variant to the gene TSS
- Severity score between a variant and VEP's predicted consequence
- Flag indicating if the variant is predicted to be a loss-of-function variant by the LOFTEE algorithm
- Linkage between genomic regions and genes based on genome interaction studies

These evidence are all scored in a way that higher means a more confident linkage with the gene.

**All features instead of the interval data is variant annotation extracted from VEP that we currently have in the variant index**. This, and the fact that V2G as a concept is only useful as a temporary dataset used to annotate credible sets in L2G, makes us want to remove the generation of this dataset.

## Tasks

- [ ] Remove the `variant_to_gene` step from Gentropy - update docs
- [ ] Move V2G extraction into the L2G feature factories so that these relationships are generated and used  during runtime only
- [ ] Indirect task: because we have seen performance issues in this step, we want to make sure that moving the logic of V2G doesn't affect L2G performance. For that, we want to explore sorting the variant index by chromosome and position as an optimisation of the process

I think I'd still keep the `variant_to_gene` data model because it is useful as a concept and for testing purposes. But maybe we decide in the refactoring that it is not actually needed.

**Comment by project-defiant** [comment]
@xyg123 @addramir FYI

**Comment by addramir** [comment]
Can we close this issue as it duplicates https://github.com/opentargets/issues/issues/3258?
