### ISSUE TITLE
Updating model version of the OpenAI literature summarisation tool

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3437]
## Background

Currently we are using [gpt-3.5-turbo](https://github.com/opentargets/ot-ai-api/blob/705d302540c71d729a29be22c7ae49fdac9bf873/controllers/publicationSummary.js#L14) in the OpenAI literature summarisation tool.

Since the release of the tool, OpenAI has released newer models. The latest [GPT-4o mini](https://platform.openai.com/docs/models/gpt-4o-mini) is cheaper and more capable than the GPT-3.5 Turbo. 

OpenAI recommends choosing `gpt-4o-mini` where one would have previously used `gpt-3.5-turbo` as this model is more capable and cheaper.

## Tasks

- [x] Update `gpt-3.5-turbo` model to `gpt-4o-mini`
- [ ] Check if new authentication tokens are required
- [ ] Check if any backend changes are required
- [x] Test the results
- [x] Update documentation and comms
