### ISSUE TITLE
Add a `category` filter and match all query to the facet search API

### ISSUE THREAD

**Issue by jdhayhurst** [opentargets/issues#3442]
As a user I want to be able to filter facets by category and return all facet labels for a given category.

## Background

Use the `category` field as filter field and the matchAll query when a "*" query is given.

## Tasks

- [x] add a category argument to the facets endpoint
- [x] implement a filter on the `category` field, using the above argument
- [x] implement a matchAll query when the query string == "*"  

## Acceptance tests

How do we know the task is complete? 

1. When I pass a category filter to the facets API, I only receive facets belonging to that category
2. When I pass "*" as the query in the facets API, I receive all facets belonging to that category/all categories
