### ISSUE TITLE
Promote features for new L2G feature matrix

### ISSUE THREAD

**Issue by project-defiant** [opentargets/issues#3456]
As a **user** I want **document and refactor list of features  included in the new feature matrix** because **I want to document them properly and test the feature template interface.**

## Background

Refactoring of the feature matrix https://github.com/opentargets/issues/issues/3252 allows genetics team to revisit the implementation of existing L2G features described in https://github.com/opentargets/issues/issues/3458

## Tasks

This task is the continuation of #3458 to develop new and reimplement old features with new feature matrix template.

- [ ] New features are implemented
- [ ] Old features are reimplemented

## Acceptance tests

- [ ] All L2G features follow the template
- [ ] All L2G features have it's own documentation and explanation

**Comment by addramir** [comment]
This issue overlaps with others. I suggest to start form table created and curated by @xyg123 . Could you please share it?

**Comment by addramir** [comment]
We need to re-write this issue next week.

**Comment by addramir** [comment]
Can we delete this issue as it is a duplication?
