### ISSUE TITLE
Improve disease/target evidence ingestion from uniprot

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3459]
Uniprot provides a curated set of naturally occurring, protein coding variation that are involved in diseases. This dataset has already been captured by the `uniprot_variants` dataset produced by the parser developed by the Uniprot team. However, recent development in the platform and the upcoming integration of the genetics product made it necessary to reconsider the evidence generation process and the data model.

## Consideration

- Evidence generation is not integrated into our pipelines, the codebase is written in java, which makes it harder to implement new features and maintain the code.
- Disease label to EFO mapping is not efficient: we are losing a large number of evidence (eg. on the [BRAF](https://www.uniprot.org/uniprotkb/P15056/entry#disease_variants) page there are 38 disease associated variants reported for 6 diseases, however we only get 7 evidence for two diseases)
- Some of the mappings provided by the java pipeline is inaccurate.
- The current pipeline does not map rs identifiers to the conventional variant identifiers (especially considering multiallelic variations)
- The current pipeline does not consider variant/disease annotation that would inform us about target modulation (eg. `elevated kinase activity; efficiently induces cell transformation` is not parsed all evidence is annotated with the constant: `"targetModulation":"up_or_down"` )
- The current pipeline applies a very crude way to assess disease to target confidence (essentially does a string match for eg. `this entry may act as a disease modifier` would imply a weaker confidence)

## TODOs

- [x] Develop a sparql query to retrieve disease/variant/target triples from uniprot API.
- [x] Parse valuable data from response.
- [x] Develop a robust, incremental way to map rsids to variant identifiers (considering matching substituted amino acids!)
- [x] Integrate with the existing disease mapping pipeline (Ontoma based logic)
- [ ] Parse and classify target modulation data.
- [ ] Parse and classify target/disease confidence.
- [ ] Change disease/target schema if required.
- [ ] Integrate parser into pipeline.

**Comment by DSuveges** [comment]
## SPARQL data retrieval

- The developed query fetches 41,475 entries in ~20sec from the Uniprot API.
- The data contains evidence for 3934 unique proteins and 5248 unique disease labels establised by 26,368 unique rs identifier.
- The number of unmapped associations: 5440. This is the number of unique disease/target pairs in the dataset. This is the theoretical maximum we can get from this dataset assuming 1 to 1 disease to EFO mapping.
- The SPARQL API can also provide the reference and alternative amino acid for each rsid/disease/protein pair. This is required for variant mapping.

## RsID to variant ID mapping

- To get variant data, a pipeline was developed to extract VEP annotation for each overlapping transcript. 
- The VEP API endpoint allows extracting the canonical vcf string (`vcf_string=1`), which is required to normalise indel variants.
- Even the POST endpoint won't allow more than 200 rsids at the same time, so the pipeline needs to loop through the variants and pool the data together at the end.
- Because requesting VEP data for 200 variants takes ~3minutes, which means the mapping the full dataset takes around 7-8 hours, I decided to develop a caching, where only missing variants will be mapped. Upon completing the mapping the new variants are added to the cache. The cache needs to be refreshed from time to time.
- When mapping is done the evidence data is joined to the mapping by the rsid. Then we need to select the right variant identifier.
- To find the right id, we follow this logic: identifier for a biallelic variant is automatically accepted. A variant id of a multiallelic variant is accepted if the substituted amino acid is matching (it means one rsid might have multiple variant ids if they code the same amino acid). If there's no matching amino acid for a variant, all options are accepted. This ensures weird substitutions/indes/stop gains are not lost in mapping.

## Disease mapping

The usual disease mapping pipeline is applied as we use for other parsers:

```python
from common.ontology import add_efo_mapping

mapped_df = add_efo_mapping(unmapped_df, spark, '.')
```

**Comment by DSuveges** [comment]
## Comparison with existing evidence set

These comparisons expects valid EFO mappings:

- New evidence data: evidence: 30,798 associations: 4,428
- Old evidence data: evidence: 41,922 associations: 4,380
- New evidence data -> mapped disease/target pairs: 4,057
- Old evidence data -> mapped disease/target pairs: 3,508

### Conclusions:

- From the original dataset, where we have 5,440 disease/target pairs, we could map 4k however in the previous pipeline this number was only 3.5k. 
- The old pipeline heavily explodes data. 
 
Let's see P05067 vs OMIM:605714. There are four rsids as evidence for this association on the uniprot page. So assuming perfect mapping, it would mean one association and 4 evidence. This is exactly what we see in the new pipeline:

```
+------------------+----------------------------------------+-------------------+-----------+-------------------------+----------------------------------------+
|targetFromSourceId|diseaseFromSource                       |diseaseFromSourceId|variantRsId|diseaseFromSourceMappedId|name                                    |
+------------------+----------------------------------------+-------------------+-----------+-------------------------+----------------------------------------+
|P05067            |Cerebral amyloid angiopathy, APP-related|OMIM:605714        |rs63750579 |MONDO_0011583            |cerebral amyloid angiopathy, APP-related|
|P05067            |Cerebral amyloid angiopathy, APP-related|OMIM:605714        |rs63750921 |MONDO_0011583            |cerebral amyloid angiopathy, APP-related|
|P05067            |Cerebral amyloid angiopathy, APP-related|OMIM:605714        |rs63749810 |MONDO_0011583            |cerebral amyloid angiopathy, APP-related|
+------------------+----------------------------------------+-------------------+-----------+-------------------------+----------------------------------------+

```

However there are 32 evidence in the old pipeline because there's an 8x explosion as that pipeline maps the disease to 8 EFOs:

```
+------------------+----------------------------------------+-------------------+-------------------------+--------------------------------------------------------------+
|targetFromSourceId|diseaseFromSource                       |diseaseFromSourceId|diseaseFromSourceMappedId|name                                                          |
+------------------+----------------------------------------+-------------------+-------------------------+--------------------------------------------------------------+
|P05067            |Cerebral amyloid angiopathy, APP-related|OMIM:605714        |Orphanet_324713          |Hereditary cerebral hemorrhage with amyloidosis, Italian type |
|P05067            |Cerebral amyloid angiopathy, APP-related|OMIM:605714        |Orphanet_100006          |Hereditary cerebral hemorrhage with amyloidosis, Dutch type   |
|P05067            |Cerebral amyloid angiopathy, APP-related|OMIM:605714        |Orphanet_324718          |Hereditary cerebral hemorrhage with amyloidosis, Flemish type |
|P05067            |Cerebral amyloid angiopathy, APP-related|OMIM:605714        |MONDO_0011583            |cerebral amyloid angiopathy, APP-related                      |
|P05067            |Cerebral amyloid angiopathy, APP-related|OMIM:605714        |Orphanet_324708          |Hereditary cerebral hemorrhage with amyloidosis, Iowa type    |
|P05067            |Cerebral amyloid angiopathy, APP-related|OMIM:605714        |Orphanet_324703          |Hereditary cerebral hemorrhage with amyloidosis, Piedmont type|
|P05067            |Cerebral amyloid angiopathy, APP-related|OMIM:605714        |Orphanet_324723          |Hereditary cerebral hemorrhage with amyloidosis, Arctic type  |
|P05067            |Cerebral amyloid angiopathy, APP-related|OMIM:605714        |Orphanet_85458           |Hereditary cerebral hemorrhage with amyloidosis               |
+------------------+----------------------------------------+-------------------+-------------------------+--------------------------------------------------------------+

```

**Comment by prashantuniyal02** [comment]
@DSuveges , can we close this issue as completed?

**Comment by DSuveges** [comment]
No, we are ~75% of the way. Unfortunately in the upcoming weeks, I surely won't have the capacity to push it completion, but aiming for the December release.
