### ISSUE TITLE
Migrate Variant Index dag to orchestration genetics_etl

### ISSUE THREAD

**Issue by project-defiant** [opentargets/issues#3460]
As a **developer** I want **replace old variant_index step in the [genetics_etl dag](https://github.com/opentargets/orchestration/blob/dev/src/ot_orchestration/dags/genetics_etl.py) with new [Variant index dag](https://github.com/opentargets/gentropy/blob/dev/src/airflow/dags/variant_index.py)** because **I want to use vep annotation calculcated directly by VEP downstream the genetics_etl steps**

## Background

This issue is a continuation of https://github.com/opentargets/issues/issues/3333. The new variant_index dag needs to be remerged to the genetics_etl dag. New dag uses `google batch` to orchestrate the automation.

> [!NOTE]
> This task will require passing configuration for the batch job directly from the dag configuration. Due to native usage of the `Dataproc` inside the `genetics_etl` steps we need to accomodate the way do specify what is going to be the infrastructure that runs the task (either dataproc or google batch job)

## Tasks

- [ ] Merge constatnts to DAG configuration
- [ ] Merge steps into the DAG
- [ ] Allow for non-dataproc task definition based on DAG configuration flags.

## Acceptance tests

How do we know the task is complete? 

1. When genetics_etl dag runs the new variant_index step correctly

**Comment by project-defiant** [comment]
Closing it as a duplicate of #3431
