### ISSUE TITLE
The genetic data release 24.11 (early November)

### ISSUE THREAD

**Issue by addramir** [opentargets/issues#3465]
We decided to do an interim genetic release using the new orchestration before the big PPP release in December. If we are able to do this in early November (6th?) it will give us 1 month to test and debug, as well as providing the pre-final version of the data to other teams.

## Background

This release is going to be executed using the new orchestration layer and basically all features we want to see in PPP release. 
There are few more ticket to make. The preliminary plan is below. 

## Tasks

- [x] #3471
- [x] #3472
- [x] Amend the fine-mapper step including the filtering of the locus within it
- [ ] Add postprocessing of PICS and SuSiE credible sets
- [ ] Refactor the feature factory and finalize the list of features
- [ ] Finalize the logic of l2g model training. Current plan is to train the model on EFO-level feature matrix
- [ ] Finalize the logic how the resulting L2G are going to be aggregate in the platform
- [ ] Finish the orchestration layer
- [x] #3473
- [ ] #3474
- [x] #3475
- [ ] Run the release itself

## Acceptance tests

The release is finished when the clean data stored in relevant google buckets.

**Comment by addramir** [comment]
GWAS Catalog finally made a release and added the GWAS for IBD we wanted. We are ready to fix the data for the release. They promised to update their manifest tommorow (we use it to create our list for manual curation). 
@project-defiant could you please make the new table for manual curation (after they update their manifest tommorow)?

**Comment by project-defiant** [comment]
Yes, I will do that

**Comment by project-defiant** [comment]
@addramir, as the data was produced into the 
```
(.venv) ☁  orchestration [dev] ⚡  gsutil ls gs://ot_orchestration/releases/24.10_freeze6
gs://ot_orchestration/releases/24.10_freeze6/
gs://ot_orchestration/releases/24.10_freeze6/biosample_index/
gs://ot_orchestration/releases/24.10_freeze6/colocalisation/
gs://ot_orchestration/releases/24.10_freeze6/credible_set/
gs://ot_orchestration/releases/24.10_freeze6/gene_index/
gs://ot_orchestration/releases/24.10_freeze6/invalid_credible_set/
gs://ot_orchestration/releases/24.10_freeze6/invalid_study_index/
gs://ot_orchestration/releases/24.10_freeze6/locus_to_gene_associations/
gs://ot_orchestration/releases/24.10_freeze6/locus_to_gene_evidence/
gs://ot_orchestration/releases/24.10_freeze6/locus_to_gene_feature_matrix/
gs://ot_orchestration/releases/24.10_freeze6/locus_to_gene_model/
gs://ot_orchestration/releases/24.10_freeze6/locus_to_gene_predictions/
gs://ot_orchestration/releases/24.10_freeze6/study_index/
gs://ot_orchestration/releases/24.10_freeze6/variant_index/
gs://ot_orchestration/releases/24.10_freeze6/variants/
```
Should we close this issue?

**Comment by addramir** [comment]
Freeze10 is ready. 
```gs://ot_orchestration/releases/24.11_freeze10/```
