### ISSUE TITLE
Implement the data transformations removed from PIS

### ISSUE THREAD

**Issue by javfg** [opentargets/issues#3481]
# Implement the data transformations removed from PIS

## Context
With the [remake of PIS](https://github.com/javfg/platform-input-support), we've identified a series of changes in the data that PIS was doing before the ETL. These have been removed, as they do not belong in PIS. Now we must add some changes downstream in the pipeline, either as part of the ETL or as stand-alone tasks that can be run in Airflow, to make up for these out of place changes.

## Tasks
Step by step:
1. Discover if any data transformation was done by PIS
2. Identify what those transformations
3. Decide where and how to implement them
4. Implement the transformations or changes to make up for them
5. Compare the outputs to ensure they match

## Steps
PIS has 18 steps, out of which 6 were doing transformations:

- [x] `baseline_expression` — output matches
- [ ] `disease` — **requires changes**
  - [x] #3496 — for `disease` itself
  - [x] #3495 — for `disease2phenotype`
  - [ ] #3497 — for `disease2phenotype` 
  - [ ] #3498 — for `disease2phenotype`
- [x] `drug` — output matches
- [x] `evidence` — output matches
- [x] `expression` — **requires changes** #3506  
- [x] `go` — output matches
- [x] `homologues` — **requires changes** #3482 
- [x] `interactions` — output matches
- [x] `literature` — output matches
- [x] `mouse_phenotypes` — output matches
- [x] `openfda` — **requires changes** #3483
- [x] `otar` — output matches, except missing EOF newline in all files, which should not matter
- [x] `pharmacogenomics` — output matches
- [x] `ppp_evidence` — output matches
- [x] `reactome` — output matches
- [x] `so` — **requires changes** #3499 
- [x] `target` — **requires changes**
   - [x] #3488
   - [x] #3489
   - [x] #3490
   - [x] #3491
- [x] `target_engine` — output matches

## Expected outcome
To ensure the unified orchestrator produces the same output as our legacy pipeline, all steps should be generating the same output either at the end of PIS or at the end of the whole pipeline (PIS->ETL).

For a step to be considered compatible:
* The orchestrator must be able to run that step from start to finish.
* One of these two:
  * The output of running that step in the legacy PIS and the new PIS must be equal.
  * The output of running that step in the whole legacy pipeline (PIS->ETL) must be equal to running it in the orchestrator, with some limitations (like the order of entries in the output jsonl).
