### ISSUE TITLE
Create gentropy doc pages for the quality control flags

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3541]
There is a growing number of quality flags indicating concerns about studies and study-loci. The interpretation of these quality flags not always trivial, and in general there should be a documentation on them. The scope of this ticket is to create new doc. page for gentropy (`https://opentargets.github.io/gentropy`) to list and explain these flags.

**Tasks**:

- [ ] Review current set of quality control flags.
- [ ] Amend description and docstring wherever it needed.
- [ ] Create new pages in the documentation

**Comment by DSuveges** [comment]
Na, this is not an issue, the documentation is already there:
![image](https://github.com/user-attachments/assets/ac91731e-4b06-473f-a6d4-8685bc9cbfe3)
