### ISSUE TITLE
Biosample index missing cell lines and other ontologies

### ISSUE THREAD

**Issue by Tobi1kenobi** [opentargets/issues#3549]
## Background

The recently implemented Biosample index only contains IDs from Uberon and Cell Ontology. If we intend to use the index outside of the eQTL catalogue it will need to be expanded to other ontologies to cover cell lines, animal tissues/cell types, etc. Even within the eQTL catalogue there are three IDs which are not present in the existing Biosample Index:

- BTO_0000930 (neuroblast)
- EFO_0005292 (lymphoblastoid cell line)
- EFO_0004905 (induced pluripotent stem cell)

## Tasks

- [ ] Find out all possible ontologies used across OpenTargets biosample datasets
- [ ] Develop a strategy to incorporate as few as possible whilst unifying the biosamples
- [ ] Potentially liase with data sources to unify ontology use
- [ ] Add additional ontologies to Biosample Index
