### ISSUE TITLE
Filter_by_study_type is now obsolete and should be removed

### ISSUE THREAD

**Issue by Tobi1kenobi** [opentargets/issues#3579]
As a developed I want studylocus.filter_by_study_type to be removed because it is no longer relevant to the code as this metadata is included in the study locus.

## Background

Study Locus metadata has been updated to make this method obsolete and many additional QTL types have been added which don't fit into the four study types mentioned.

## Tasks

- [ ] Deprecate studylocus.filter_by_study_type
- [ ] Ensure there is still some filtering by study type occuring in gentropy
- [ ] Expand the study types to include new QTLs e.g. sceQTL, sctuQTL, tuQTL, etc

**Comment by d0choa** [comment]
@project-defiant, up to you. Either fix function, remove function or close ticket

**Comment by project-defiant** [comment]
I have searched gentropy, I do not see this function anywhere, closing the ticket now.
