### ISSUE TITLE
New study page clean-up tasks

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3632]
@opentargets/fe-team please find below tasks related to a merge `study page` cleanup:

- [x] change order of the widgets
- [x] validate `source` link behind page header:

When `projectId` is `GCST` -- source is gwas Catalog (link)
When `projectId` is `FINNGEN_R11` -- source is FinnGen (link)
When `projectId` does not contain any of the above (e.g.`Alasoo_2018` - source is eQTL Catalog (link)
When `projectId`  is `UKB_PPP_EUR` -- source is UKB_PPP (hyperlinked to https://www.synapse.org/Synapse:syn51364943/wiki/622119)

- [x] Validate `publicationFirstAuthor` field (we have one example where for a `GCST` study the **first author** shows as 'FINNGEN` (for study GCST90176761)

**metadata session**		

- [x] Show **disease/phenotype** field** (EFO) - `disease name` hyperlinked to Platform disease page through disease `Id`
- [x] Show **background trait** (EFO) - `name` + hyperlinked to `Id`
- [x] Show **has summary statistics** - `hasSumstats` true or false 
- [x] Show **visualisation** on `sumStatQCValues` - see [#3626 ](https://github.com/opentargets/issues/issues/3626) for more info
- [x] Show **sample ancestry** field (place this after the **sample size** field): within `ldPopulationStructure` - `ldpolulation`
- [x] Show **analysis flags**: `analysisFlags`

**credible sets widget**
		
- [x]  add confidence to table -see #3605 
- [ ] add confidence to manhattan tooltip - @gjmcn will do when polishing plots 
- [x] harmonise UI for L2G prediction - see also #3629 (second part of ticket - L2G widget harmonisation)

**shared trait widget**

- [x]  Condense Author, Journal (Year) at the end of table - link to drawer? -- same as new evidence widget (please check)

**Comment by buniello** [comment]
API query for studyId e.g. `GCST90176761`, `FINNGEN_R11_F5_DEMENTIA``, Alasoo_2018_exon_macrophage_IFNg+Salmonella_ENSG00000168994.14_6_3751530_3751532`: 
```
query GWASCredibleSetsQuery($studyId: String!) {
  gwasStudy(studyId: $studyId) {
    studyId
    hasSumstats
    publicationFirstAuthor
    projectId
    diseases{
      id
      name
    }
    backgroundTraits{
      id
      name
    }
    sumStatQCValues{
      QCCheckName
      QCCheckValue
    }
    ldPopulationStructure{
      ldPopulation
      relativeSampleSize
    }
    analysisFlags
    studyType
  }
}
```
