### ISSUE TITLE
List of ids for every widget and its column that cant be disabled

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3633]
## Background

List of ids for every widget and its column that cant be disabled

Format below: 
widget - column to be fixed

## Tasks

**Target profile**

- [ ] Known Drugs - Drug
- [ ] Safety - Safety event 
- [ ] Pharmacogenetics - rsID
- [ ] Chemical Probes - Probe ID
- [ ] Gene Ontology - GO term
- [ ] Genetic Constraint - Category
- [ ] Pathways - Pathway
- [ ] Cancer Hallmarks - Hallmark
- [ ] Mouse Phenotypes - Mouse gene && Allelic composition ??
- [ ] Comparative Genomics - Species && Homologue ??

**Disease profile**

- [ ] Known Drugs - Drug
- [ ] Clinical signs and symptoms - Phenotype && Phenotype ID ??
- [ ] Open Targets Projects - Project Code
- [ ] GWAS Studies - Study ID

**Drug profile**

- [ ] Mechanisms of Action - Mechanism of Action
- [ ] Indications - Indication
- [ ] Clinical Precedence - Disease ??
- [ ] Drug Warnings - ChEMBL warning class?
- [ ] Pharmacogenetics - rsID

**Evidence page:**

- [ ] Open Targets Genetics - ??
- [ ] Gene Burden - ??
- [ ] ClinVar - Variant ID
- [ ] GEL PanelApp - Disease/phenotype && Genomics England Panel
- [ ] Gene2Phenotype - Disease/phenotype && Panel
- [ ] UniProt literature - Disease/phenotype && Reported protein
- [ ] UniProt variants - Disease/phenotype && Variant
- [ ] ClinGen - Disease/phenotype
- [ ] Orphanet - Disease/phenotype && Functional consequence
- [ ] Cancer Gene Census - Disease/phenotype && Mutation type
- [ ] IntOGen - Cohort Information
- [ ] ClinVar (somatic) - Variant ID
- [ ] ChEMBL - Disease/phenotype and Drug
- [ ] Project Score - Disease/phenotype && Reported disease/phenotype
- [ ] CRISPR Screens - Study Identifier
- [ ] Cancer Biomarkers - Biomarker
- [ ] SLAPenrich - Significant pathway
- [ ] PROGENy - Disease/phenotype && Significant pathway
- [ ] Reactome - Reaction
- [ ] Gene signatures - Gene set
- [ ] Expression Atlas - Experiment ID
- [ ] IMPC - Mouse model allelic composition
- [ ] Open Targets CRISPR - Contrast / Study overview
- [ ] Open Targets ENCORE - Anchor gene
- [ ] Open Targets Validation CRISPR - Cell line biomarkers

**Variant profile** 

- [ ] In silico predictors - Method
- [ ] Transcript consequences - Gene && Predicted consequence??
- [ ] ClinVar - Variant ID
- [ ] UniProt variants - Disease/phenotype && Variant
- [ ] GWAS Credible Sets - Details && VariantID?
- [ ] molQTL Credible Sets - Details && Lead Variant?
- [ ] Pharmacogenetics - rsID

**Study profile** 

- [ ] Shared Trait Studies - Study ID
- [ ] GWAS Credible Sets - Details && VariantID?

**Credible set profile** 

- [ ] Variants in Credible Set - Variant ID
- [ ] GWAS Colocalisation - View Credible Set
- [ ] Locus to Gene - Gene

**Comment by d0choa** [comment]
Good stuff, but we might need to revise a few of these.

We are looking for columns that define unique rows in each widget. The point is that we will not allow to hide these columns in the UI.
After hiding all the other columns, we should never have duplicated rows.

For example, `Disease profile` > Known drugs need to have at least the Gene symbol on it. Otherwise you will end up with duplicate rows were you can't tell the difference.

@prashantuniyal02, try to give it a second look and flag the ones you are not 100%. We can check data/BE to understand what you might be missing.

**Comment by buniello** [comment]
@prashantuniyal02 what is the priority for this ticket? is task going to be delivered for PPP 24.12?
If not, i will take a look post-release. If yes, please do let me know and i will work on it this week

**Comment by d0choa** [comment]
Completed
