### ISSUE TITLE
Add patent literature input from SureChEMBL

### ISSUE THREAD

**Issue by remo87** [opentargets/issues#3635]
We need to normalise entities coming from the analysis of pharmaceutical patents. Although the data model is very similar to what EuroPMC provide it not exactly identical, so there might be required changes in the data or the pipeline itself.

## Tasks

- [ ] Add new literature input
- [ ] Verify schema compatibility
- [ ] Do a run of the literature step
- [ ] Verify outputs

## Acceptance tests

1. The dataset goes through the literature pipeline without error.
2. All entity types are handled appropriately.

@nbosc might provide further details.

**Comment by nbosc** [comment]
For now, we will stick to co-occurrences of size 2 (e.g. type1 - type2). We can discuss to include  co-occurrences of size 3 (e.g. type1 - type2 - type3) at a later time.

**Comment by remo87** [comment]
This issue will be
