### ISSUE TITLE
studies endpoint should return count and rows

### ISSUE THREAD

**Issue by jdhayhurst** [opentargets/issues#3639]
As a developer I want the existing `gwasStudy` to return an object that contains `count` and `rows` because that is consistent with the styling of the rest of the API for endpoints that return `[<Type>]`. This will enable the frontend to batch requests with the same protocol. This ties into the scaling issues (opentargets/issues#3611) in that it enables the frontend to perform batch requests.

## Background

`gwasStudy` currently returns a `[GWAS]`. 
Not all the GWAS type objects are actually gwas. A `studyType` field exists for this reason. Therefore, a more correct term would be `Study`.

## Tasks

- [x] rename `gwasStudy` -> `studies`
- [x] rename `GWAS` -> `Study` 
- [x] rename `studyId` -> `id`
- [x] `studies` returns an object with `count` and `rows` where each row is a `Study`
- [x] create a singular endpoint, `study` which takes a single `id` and returns a single `Study` or None.
