### ISSUE TITLE
Enable gentropy to enrich variant in-silico predictors with amino-acid variation consequences (OTAR2081)

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3676]
## Context

There are a number of methods that provide variation consequences at the amino acid resolution. In such cases the method claims that changing position `n` of the sequence of protein represented by Uniprot id `u`  from amino acid `ref` to `alt` there's some predicted consequence eg. effect on protein stability. 

An example of such dataset is the [FoldX](https://home.opentargets.org/OTAR2081) project, where the team was using AlphaFold structures of all proteins to mutate all residues to all other residues and measured the resulting ddG indicating highly destabilising mutations. 

All variants in the variant index that causes amino acid change that were tested in the FoldX project needs to be annotated with the corresponding ddG values and stored in the `inSilicoPredictos` object.

## Tasks

- [x] Given there's a good chance such annotations will increase in the future, a new data model needs to be included in gentropy.
- [x] Add new datasource for FoldX.
- [x] Add logic to normalise FoldX ddG values.
- [x] Add logic to integrate dataset into the variant index.
- [ ] Add test.
- [x] Add new step to ingest data.

## Integration of FoldX dataset

- Some of the large proteins are chunked to build AlphaFold models, but the positions in the dataset are referring to the models not the full-length Uniprot sequence. The chunked Uniprot IDs need to be dropped.
- Developing logic to normalise ddG values.
- Add step to ingest data and save as static asset.

**Comment by DSuveges** [comment]
## Stats

Out of the 6.2 million variants in the variant index, 7% of them (442k) has FoldX ddG values.

**Comment by DSuveges** [comment]
The mean ddG predicted by FoldX for clinVar variants shows a nice correlation with the severity of the assigned clinical significance:

![Image](https://github.com/user-attachments/assets/69737c05-e35a-4836-8366-8a15ce46d34a)

For more severe assessment classes have a higher ddG on average, however it has to be noted that the ddG distribution is very wide for all classes:

![Image](https://github.com/user-attachments/assets/ed1fd9a1-915c-4d6c-b126-33d86cc62dbd)
