### ISSUE TITLE
Allow multiple python versions

### ISSUE THREAD

**Issue by project-defiant** [opentargets/issues#3680]
As a **gentropy developer** I want **be able to use multiple python versions when installing the package** because **the usecases may vary**

## Background

The context to this issue is that currently (v2.0.0) gentropy only supports `python 3.10.8` - see [python version file](https://github.com/opentargets/gentropy/blob/dev/.python-version). This limits the users to fixed python version which can prevent them from using the gentropy.

Another point is that python since 3.10 version got significantly faster due to numerous of performance increasing changes:

https://docs.python.org/3/whatsnew/changelog.html#id124

Also now the JIT support without the GIL is possible when building python
https://medium.com/@mitesh.singh.jat/gil-becomes-optional-in-python-3-13-a-game-changer-for-multithreading-4c5d28856803

## Tasks

- [x] Allow for multiple versions of python (3.11, 3.12, 3.13, possibly p)
~- [ ] Add tox - https://tox.wiki/en/4.23.2/ to test for multiple python versions~
- [x] Streamline the development setup
~- [ ] Test if feasible to run python without GIL~
- [x] Find if google dataproc allows for supporting python 3.13 (if not, then accomodate with new dataproc image)

## Acceptance tests

1. When gentropy test runs on py310, py311, py312, (possbly on py313)
2. When dataproc creates cluster with correct gentropy package installed
3. When the development installation process works correctly

**Comment by project-defiant** [comment]
As in the documentation, the dataproc 2.2 does not allow for running python >= 3.11 https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-2.2#:~:text=5.2.1-,Python%0Ainstalled,-conda%2023.11.0%20with

**Comment by project-defiant** [comment]
* Currently we can not use python3.13, nor pypy due to llvm and scipy dependency issues, thus we can not skip the GIL lock.
* tox was not added, since we can rely for now on github actions tests for multiple python versions. (Code is not specific to any of the supported releases)
