### ISSUE TITLE
Numba performance boosts

### ISSUE THREAD

**Issue by project-defiant** [opentargets/issues#3682]
As a **gentropy developer** I want **increase the performance of pure python functions** because **I want to speed the single threaded processing.**

## Background

There are a number of functions that use numpy arrays in the fine-mapping SuSIE implementation in gentropy. These functions could abuse the nunba acceleration JIT (https://numba.pydata.org/) to speed up the performance.

## Tasks

- [ ] Identify valid methods and functions that use numpy arrays.
- [ ] Decorate the functions.
- [ ] Run the performance tests.

**Comment by d0choa** [comment]
@project-defiant feel free to reopen if necessary. Closing as the issue has stalled

**Comment by project-defiant** [comment]
I have searched through the codebase for the usage of for loops with numpy ndarrays. The only obvious winners here would be to decorate the functions from `SusieFinemapper` and `Carma` methods, as these work without the proper pyspark parallelization. Closing for now, as it would require some efford to benchmark (possible improvement for the future)
